/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Article,
  ArticleRequest,
  PaginatedArticleList,
  PatchedArticleRequest,
} from '../models/index';
import {
    ArticleFromJSON,
    ArticleToJSON,
    ArticleRequestFromJSON,
    ArticleRequestToJSON,
    PaginatedArticleListFromJSON,
    PaginatedArticleListToJSON,
    PatchedArticleRequestFromJSON,
    PatchedArticleRequestToJSON,
} from '../models/index';

export interface ArticlesCreateRequest {
    ArticleRequest: ArticleRequest;
}

export interface ArticlesDestroyRequest {
    id: number;
}

export interface ArticlesListRequest {
    limit?: number;
    offset?: number;
}

export interface ArticlesPartialUpdateRequest {
    id: number;
    PatchedArticleRequest?: PatchedArticleRequest;
}

export interface ArticlesRetrieveRequest {
    id: number;
}

/**
 * 
 */
export class ArticlesApi extends runtime.BaseAPI {

    /**
     * Create a new article
     * Create
     */
    async articlesCreateRaw(requestParameters: ArticlesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Article>> {
        if (requestParameters.ArticleRequest === null || requestParameters.ArticleRequest === undefined) {
            throw new runtime.RequiredError('ArticleRequest','Required parameter requestParameters.ArticleRequest was null or undefined when calling articlesCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/articles/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ArticleRequestToJSON(requestParameters.ArticleRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArticleFromJSON(jsonValue));
    }

    /**
     * Create a new article
     * Create
     */
    async articlesCreate(requestParameters: ArticlesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Article> {
        const response = await this.articlesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an article
     * Destroy
     */
    async articlesDestroyRaw(requestParameters: ArticlesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling articlesDestroy.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/articles/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an article
     * Destroy
     */
    async articlesDestroy(requestParameters: ArticlesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.articlesDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Get a paginated list of articles
     * List
     */
    async articlesListRaw(requestParameters: ArticlesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedArticleList>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/articles/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedArticleListFromJSON(jsonValue));
    }

    /**
     * Get a paginated list of articles
     * List
     */
    async articlesList(requestParameters: ArticlesListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedArticleList> {
        const response = await this.articlesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an article
     * Update
     */
    async articlesPartialUpdateRaw(requestParameters: ArticlesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Article>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling articlesPartialUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/articles/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedArticleRequestToJSON(requestParameters.PatchedArticleRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArticleFromJSON(jsonValue));
    }

    /**
     * Update an article
     * Update
     */
    async articlesPartialUpdate(requestParameters: ArticlesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Article> {
        const response = await this.articlesPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a single article
     * Retrieve
     */
    async articlesRetrieveRaw(requestParameters: ArticlesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Article>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling articlesRetrieve.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/articles/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArticleFromJSON(jsonValue));
    }

    /**
     * Retrieve a single article
     * Retrieve
     */
    async articlesRetrieve(requestParameters: ArticlesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Article> {
        const response = await this.articlesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
