/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime"
import type {
  LearningResourceDepartment,
  PaginatedLearningResourceDepartmentList,
} from "../models/index"
import {
  LearningResourceDepartmentFromJSON,
  LearningResourceDepartmentToJSON,
  PaginatedLearningResourceDepartmentListFromJSON,
  PaginatedLearningResourceDepartmentListToJSON,
} from "../models/index"

export interface DepartmentsListRequest {
  limit?: number
  offset?: number
}

export interface DepartmentsRetrieveRequest {
  department_id: string
}

/**
 *
 */
export class DepartmentsApi extends runtime.BaseAPI {
  /**
   * MIT academic departments
   * List
   */
  async departmentsListRaw(
    requestParameters: DepartmentsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PaginatedLearningResourceDepartmentList>> {
    const queryParameters: any = {}

    if (requestParameters.limit !== undefined) {
      queryParameters["limit"] = requestParameters.limit
    }

    if (requestParameters.offset !== undefined) {
      queryParameters["offset"] = requestParameters.offset
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/departments/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PaginatedLearningResourceDepartmentListFromJSON(jsonValue),
    )
  }

  /**
   * MIT academic departments
   * List
   */
  async departmentsList(
    requestParameters: DepartmentsListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PaginatedLearningResourceDepartmentList> {
    const response = await this.departmentsListRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * MIT academic departments
   * Retrieve
   */
  async departmentsRetrieveRaw(
    requestParameters: DepartmentsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LearningResourceDepartment>> {
    if (
      requestParameters.department_id === null ||
      requestParameters.department_id === undefined
    ) {
      throw new runtime.RequiredError(
        "department_id",
        "Required parameter requestParameters.department_id was null or undefined when calling departmentsRetrieve.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/departments/{department_id}/`.replace(
          `{${"department_id"}}`,
          encodeURIComponent(String(requestParameters.department_id)),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LearningResourceDepartmentFromJSON(jsonValue),
    )
  }

  /**
   * MIT academic departments
   * Retrieve
   */
  async departmentsRetrieve(
    requestParameters: DepartmentsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LearningResourceDepartment> {
    const response = await this.departmentsRetrieveRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }
}
