/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime"
import type {
  PercolateQuery,
  PercolateQuerySubscriptionRequestRequest,
} from "../models/index"
import {
  PercolateQueryFromJSON,
  PercolateQueryToJSON,
  PercolateQuerySubscriptionRequestRequestFromJSON,
  PercolateQuerySubscriptionRequestRequestToJSON,
} from "../models/index"

export interface LearningResourcesUserSubscriptionCheckListRequest {
  aggregations?: Array<LearningResourcesUserSubscriptionCheckListAggregationsEnum>
  certification?: boolean | null
  certification_type?: Array<LearningResourcesUserSubscriptionCheckListCertificationTypeEnum>
  content_file_score_weight?: number | null
  course_feature?: Array<string>
  delivery?: Array<LearningResourcesUserSubscriptionCheckListDeliveryEnum>
  department?: Array<LearningResourcesUserSubscriptionCheckListDepartmentEnum>
  dev_mode?: boolean | null
  free?: boolean | null
  id?: Array<number>
  level?: Array<LearningResourcesUserSubscriptionCheckListLevelEnum>
  limit?: number
  max_incompleteness_penalty?: number | null
  min_score?: number | null
  ocw_topic?: Array<string>
  offered_by?: Array<LearningResourcesUserSubscriptionCheckListOfferedByEnum>
  offset?: number
  platform?: Array<LearningResourcesUserSubscriptionCheckListPlatformEnum>
  professional?: boolean | null
  q?: string
  resource_category?: Array<LearningResourcesUserSubscriptionCheckListResourceCategoryEnum>
  resource_type?: Array<LearningResourcesUserSubscriptionCheckListResourceTypeEnum>
  search_mode?: LearningResourcesUserSubscriptionCheckListSearchModeEnum
  slop?: number | null
  sortby?: LearningResourcesUserSubscriptionCheckListSortbyEnum
  source_type?: LearningResourcesUserSubscriptionCheckListSourceTypeEnum
  topic?: Array<string>
  yearly_decay_percent?: number | null
}

export interface LearningResourcesUserSubscriptionListRequest {
  aggregations?: Array<LearningResourcesUserSubscriptionListAggregationsEnum>
  certification?: boolean | null
  certification_type?: Array<LearningResourcesUserSubscriptionListCertificationTypeEnum>
  content_file_score_weight?: number | null
  course_feature?: Array<string>
  delivery?: Array<LearningResourcesUserSubscriptionListDeliveryEnum>
  department?: Array<LearningResourcesUserSubscriptionListDepartmentEnum>
  dev_mode?: boolean | null
  free?: boolean | null
  id?: Array<number>
  level?: Array<LearningResourcesUserSubscriptionListLevelEnum>
  limit?: number
  max_incompleteness_penalty?: number | null
  min_score?: number | null
  ocw_topic?: Array<string>
  offered_by?: Array<LearningResourcesUserSubscriptionListOfferedByEnum>
  offset?: number
  platform?: Array<LearningResourcesUserSubscriptionListPlatformEnum>
  professional?: boolean | null
  q?: string
  resource_category?: Array<LearningResourcesUserSubscriptionListResourceCategoryEnum>
  resource_type?: Array<LearningResourcesUserSubscriptionListResourceTypeEnum>
  search_mode?: LearningResourcesUserSubscriptionListSearchModeEnum
  slop?: number | null
  sortby?: LearningResourcesUserSubscriptionListSortbyEnum
  topic?: Array<string>
  yearly_decay_percent?: number | null
}

export interface LearningResourcesUserSubscriptionSubscribeCreateRequest {
  aggregations?: Array<LearningResourcesUserSubscriptionSubscribeCreateAggregationsEnum>
  certification?: boolean | null
  certification_type?: Array<LearningResourcesUserSubscriptionSubscribeCreateCertificationTypeEnum>
  content_file_score_weight?: number | null
  course_feature?: Array<string>
  delivery?: Array<LearningResourcesUserSubscriptionSubscribeCreateDeliveryEnum>
  department?: Array<LearningResourcesUserSubscriptionSubscribeCreateDepartmentEnum>
  dev_mode?: boolean | null
  free?: boolean | null
  id?: Array<number>
  level?: Array<LearningResourcesUserSubscriptionSubscribeCreateLevelEnum>
  limit?: number
  max_incompleteness_penalty?: number | null
  min_score?: number | null
  ocw_topic?: Array<string>
  offered_by?: Array<LearningResourcesUserSubscriptionSubscribeCreateOfferedByEnum>
  offset?: number
  platform?: Array<LearningResourcesUserSubscriptionSubscribeCreatePlatformEnum>
  professional?: boolean | null
  q?: string
  resource_category?: Array<LearningResourcesUserSubscriptionSubscribeCreateResourceCategoryEnum>
  resource_type?: Array<LearningResourcesUserSubscriptionSubscribeCreateResourceTypeEnum>
  search_mode?: LearningResourcesUserSubscriptionSubscribeCreateSearchModeEnum
  slop?: number | null
  sortby?: LearningResourcesUserSubscriptionSubscribeCreateSortbyEnum
  source_type?: LearningResourcesUserSubscriptionSubscribeCreateSourceTypeEnum
  topic?: Array<string>
  yearly_decay_percent?: number | null
  PercolateQuerySubscriptionRequestRequest?: PercolateQuerySubscriptionRequestRequest
}

export interface LearningResourcesUserSubscriptionUnsubscribeDestroyRequest {
  id: number
}

/**
 *
 */
export class LearningResourcesUserSubscriptionApi extends runtime.BaseAPI {
  /**
   * View for listing percolate query subscriptions for a user
   * Check if a user is subscribed to a specific query
   */
  async learningResourcesUserSubscriptionCheckListRaw(
    requestParameters: LearningResourcesUserSubscriptionCheckListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PercolateQuery>>> {
    const queryParameters: any = {}

    if (requestParameters.aggregations) {
      queryParameters["aggregations"] = requestParameters.aggregations
    }

    if (requestParameters.certification !== undefined) {
      queryParameters["certification"] = requestParameters.certification
    }

    if (requestParameters.certification_type) {
      queryParameters["certification_type"] =
        requestParameters.certification_type
    }

    if (requestParameters.content_file_score_weight !== undefined) {
      queryParameters["content_file_score_weight"] =
        requestParameters.content_file_score_weight
    }

    if (requestParameters.course_feature) {
      queryParameters["course_feature"] = requestParameters.course_feature
    }

    if (requestParameters.delivery) {
      queryParameters["delivery"] = requestParameters.delivery
    }

    if (requestParameters.department) {
      queryParameters["department"] = requestParameters.department
    }

    if (requestParameters.dev_mode !== undefined) {
      queryParameters["dev_mode"] = requestParameters.dev_mode
    }

    if (requestParameters.free !== undefined) {
      queryParameters["free"] = requestParameters.free
    }

    if (requestParameters.id) {
      queryParameters["id"] = requestParameters.id
    }

    if (requestParameters.level) {
      queryParameters["level"] = requestParameters.level
    }

    if (requestParameters.limit !== undefined) {
      queryParameters["limit"] = requestParameters.limit
    }

    if (requestParameters.max_incompleteness_penalty !== undefined) {
      queryParameters["max_incompleteness_penalty"] =
        requestParameters.max_incompleteness_penalty
    }

    if (requestParameters.min_score !== undefined) {
      queryParameters["min_score"] = requestParameters.min_score
    }

    if (requestParameters.ocw_topic) {
      queryParameters["ocw_topic"] = requestParameters.ocw_topic
    }

    if (requestParameters.offered_by) {
      queryParameters["offered_by"] = requestParameters.offered_by
    }

    if (requestParameters.offset !== undefined) {
      queryParameters["offset"] = requestParameters.offset
    }

    if (requestParameters.platform) {
      queryParameters["platform"] = requestParameters.platform
    }

    if (requestParameters.professional !== undefined) {
      queryParameters["professional"] = requestParameters.professional
    }

    if (requestParameters.q !== undefined) {
      queryParameters["q"] = requestParameters.q
    }

    if (requestParameters.resource_category) {
      queryParameters["resource_category"] = requestParameters.resource_category
    }

    if (requestParameters.resource_type) {
      queryParameters["resource_type"] = requestParameters.resource_type
    }

    if (requestParameters.search_mode !== undefined) {
      queryParameters["search_mode"] = requestParameters.search_mode
    }

    if (requestParameters.slop !== undefined) {
      queryParameters["slop"] = requestParameters.slop
    }

    if (requestParameters.sortby !== undefined) {
      queryParameters["sortby"] = requestParameters.sortby
    }

    if (requestParameters.source_type !== undefined) {
      queryParameters["source_type"] = requestParameters.source_type
    }

    if (requestParameters.topic) {
      queryParameters["topic"] = requestParameters.topic
    }

    if (requestParameters.yearly_decay_percent !== undefined) {
      queryParameters["yearly_decay_percent"] =
        requestParameters.yearly_decay_percent
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/learning_resources_user_subscription/check/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PercolateQueryFromJSON),
    )
  }

  /**
   * View for listing percolate query subscriptions for a user
   * Check if a user is subscribed to a specific query
   */
  async learningResourcesUserSubscriptionCheckList(
    requestParameters: LearningResourcesUserSubscriptionCheckListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PercolateQuery>> {
    const response = await this.learningResourcesUserSubscriptionCheckListRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * View for listing percolate query subscriptions for a user
   * List subscribed queries
   */
  async learningResourcesUserSubscriptionListRaw(
    requestParameters: LearningResourcesUserSubscriptionListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PercolateQuery>>> {
    const queryParameters: any = {}

    if (requestParameters.aggregations) {
      queryParameters["aggregations"] = requestParameters.aggregations
    }

    if (requestParameters.certification !== undefined) {
      queryParameters["certification"] = requestParameters.certification
    }

    if (requestParameters.certification_type) {
      queryParameters["certification_type"] =
        requestParameters.certification_type
    }

    if (requestParameters.content_file_score_weight !== undefined) {
      queryParameters["content_file_score_weight"] =
        requestParameters.content_file_score_weight
    }

    if (requestParameters.course_feature) {
      queryParameters["course_feature"] = requestParameters.course_feature
    }

    if (requestParameters.delivery) {
      queryParameters["delivery"] = requestParameters.delivery
    }

    if (requestParameters.department) {
      queryParameters["department"] = requestParameters.department
    }

    if (requestParameters.dev_mode !== undefined) {
      queryParameters["dev_mode"] = requestParameters.dev_mode
    }

    if (requestParameters.free !== undefined) {
      queryParameters["free"] = requestParameters.free
    }

    if (requestParameters.id) {
      queryParameters["id"] = requestParameters.id
    }

    if (requestParameters.level) {
      queryParameters["level"] = requestParameters.level
    }

    if (requestParameters.limit !== undefined) {
      queryParameters["limit"] = requestParameters.limit
    }

    if (requestParameters.max_incompleteness_penalty !== undefined) {
      queryParameters["max_incompleteness_penalty"] =
        requestParameters.max_incompleteness_penalty
    }

    if (requestParameters.min_score !== undefined) {
      queryParameters["min_score"] = requestParameters.min_score
    }

    if (requestParameters.ocw_topic) {
      queryParameters["ocw_topic"] = requestParameters.ocw_topic
    }

    if (requestParameters.offered_by) {
      queryParameters["offered_by"] = requestParameters.offered_by
    }

    if (requestParameters.offset !== undefined) {
      queryParameters["offset"] = requestParameters.offset
    }

    if (requestParameters.platform) {
      queryParameters["platform"] = requestParameters.platform
    }

    if (requestParameters.professional !== undefined) {
      queryParameters["professional"] = requestParameters.professional
    }

    if (requestParameters.q !== undefined) {
      queryParameters["q"] = requestParameters.q
    }

    if (requestParameters.resource_category) {
      queryParameters["resource_category"] = requestParameters.resource_category
    }

    if (requestParameters.resource_type) {
      queryParameters["resource_type"] = requestParameters.resource_type
    }

    if (requestParameters.search_mode !== undefined) {
      queryParameters["search_mode"] = requestParameters.search_mode
    }

    if (requestParameters.slop !== undefined) {
      queryParameters["slop"] = requestParameters.slop
    }

    if (requestParameters.sortby !== undefined) {
      queryParameters["sortby"] = requestParameters.sortby
    }

    if (requestParameters.topic) {
      queryParameters["topic"] = requestParameters.topic
    }

    if (requestParameters.yearly_decay_percent !== undefined) {
      queryParameters["yearly_decay_percent"] =
        requestParameters.yearly_decay_percent
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/learning_resources_user_subscription/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PercolateQueryFromJSON),
    )
  }

  /**
   * View for listing percolate query subscriptions for a user
   * List subscribed queries
   */
  async learningResourcesUserSubscriptionList(
    requestParameters: LearningResourcesUserSubscriptionListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PercolateQuery>> {
    const response = await this.learningResourcesUserSubscriptionListRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * Subscribe a user to query
   * Subscribe user to query
   */
  async learningResourcesUserSubscriptionSubscribeCreateRaw(
    requestParameters: LearningResourcesUserSubscriptionSubscribeCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PercolateQuery>> {
    const queryParameters: any = {}

    if (requestParameters.aggregations) {
      queryParameters["aggregations"] = requestParameters.aggregations
    }

    if (requestParameters.certification !== undefined) {
      queryParameters["certification"] = requestParameters.certification
    }

    if (requestParameters.certification_type) {
      queryParameters["certification_type"] =
        requestParameters.certification_type
    }

    if (requestParameters.content_file_score_weight !== undefined) {
      queryParameters["content_file_score_weight"] =
        requestParameters.content_file_score_weight
    }

    if (requestParameters.course_feature) {
      queryParameters["course_feature"] = requestParameters.course_feature
    }

    if (requestParameters.delivery) {
      queryParameters["delivery"] = requestParameters.delivery
    }

    if (requestParameters.department) {
      queryParameters["department"] = requestParameters.department
    }

    if (requestParameters.dev_mode !== undefined) {
      queryParameters["dev_mode"] = requestParameters.dev_mode
    }

    if (requestParameters.free !== undefined) {
      queryParameters["free"] = requestParameters.free
    }

    if (requestParameters.id) {
      queryParameters["id"] = requestParameters.id
    }

    if (requestParameters.level) {
      queryParameters["level"] = requestParameters.level
    }

    if (requestParameters.limit !== undefined) {
      queryParameters["limit"] = requestParameters.limit
    }

    if (requestParameters.max_incompleteness_penalty !== undefined) {
      queryParameters["max_incompleteness_penalty"] =
        requestParameters.max_incompleteness_penalty
    }

    if (requestParameters.min_score !== undefined) {
      queryParameters["min_score"] = requestParameters.min_score
    }

    if (requestParameters.ocw_topic) {
      queryParameters["ocw_topic"] = requestParameters.ocw_topic
    }

    if (requestParameters.offered_by) {
      queryParameters["offered_by"] = requestParameters.offered_by
    }

    if (requestParameters.offset !== undefined) {
      queryParameters["offset"] = requestParameters.offset
    }

    if (requestParameters.platform) {
      queryParameters["platform"] = requestParameters.platform
    }

    if (requestParameters.professional !== undefined) {
      queryParameters["professional"] = requestParameters.professional
    }

    if (requestParameters.q !== undefined) {
      queryParameters["q"] = requestParameters.q
    }

    if (requestParameters.resource_category) {
      queryParameters["resource_category"] = requestParameters.resource_category
    }

    if (requestParameters.resource_type) {
      queryParameters["resource_type"] = requestParameters.resource_type
    }

    if (requestParameters.search_mode !== undefined) {
      queryParameters["search_mode"] = requestParameters.search_mode
    }

    if (requestParameters.slop !== undefined) {
      queryParameters["slop"] = requestParameters.slop
    }

    if (requestParameters.sortby !== undefined) {
      queryParameters["sortby"] = requestParameters.sortby
    }

    if (requestParameters.source_type !== undefined) {
      queryParameters["source_type"] = requestParameters.source_type
    }

    if (requestParameters.topic) {
      queryParameters["topic"] = requestParameters.topic
    }

    if (requestParameters.yearly_decay_percent !== undefined) {
      queryParameters["yearly_decay_percent"] =
        requestParameters.yearly_decay_percent
    }

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters["Content-Type"] = "application/json"

    const response = await this.request(
      {
        path: `/api/v1/learning_resources_user_subscription/subscribe/`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: PercolateQuerySubscriptionRequestRequestToJSON(
          requestParameters.PercolateQuerySubscriptionRequestRequest,
        ),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PercolateQueryFromJSON(jsonValue),
    )
  }

  /**
   * Subscribe a user to query
   * Subscribe user to query
   */
  async learningResourcesUserSubscriptionSubscribeCreate(
    requestParameters: LearningResourcesUserSubscriptionSubscribeCreateRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PercolateQuery> {
    const response =
      await this.learningResourcesUserSubscriptionSubscribeCreateRaw(
        requestParameters,
        initOverrides,
      )
    return await response.value()
  }

  /**
   * Unsubscribe a user from a query  Args: pk (integer): The id of the query  Returns: PercolateQuerySerializer: The percolate query
   * Unsubscribe user from query
   */
  async learningResourcesUserSubscriptionUnsubscribeDestroyRaw(
    requestParameters: LearningResourcesUserSubscriptionUnsubscribeDestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling learningResourcesUserSubscriptionUnsubscribeDestroy.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/learning_resources_user_subscription/{id}/unsubscribe/`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id)),
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Unsubscribe a user from a query  Args: pk (integer): The id of the query  Returns: PercolateQuerySerializer: The percolate query
   * Unsubscribe user from query
   */
  async learningResourcesUserSubscriptionUnsubscribeDestroy(
    requestParameters: LearningResourcesUserSubscriptionUnsubscribeDestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.learningResourcesUserSubscriptionUnsubscribeDestroyRaw(
      requestParameters,
      initOverrides,
    )
  }
}

/**
 * @export
 */
export const LearningResourcesUserSubscriptionCheckListAggregationsEnum = {
  ResourceType: "resource_type",
  Certification: "certification",
  CertificationType: "certification_type",
  OfferedBy: "offered_by",
  Platform: "platform",
  Topic: "topic",
  Department: "department",
  Level: "level",
  CourseFeature: "course_feature",
  Professional: "professional",
  Free: "free",
  Delivery: "delivery",
  ResourceCategory: "resource_category",
} as const
export type LearningResourcesUserSubscriptionCheckListAggregationsEnum =
  (typeof LearningResourcesUserSubscriptionCheckListAggregationsEnum)[keyof typeof LearningResourcesUserSubscriptionCheckListAggregationsEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionCheckListCertificationTypeEnum = {
  Micromasters: "micromasters",
  Professional: "professional",
  Completion: "completion",
  None: "none",
} as const
export type LearningResourcesUserSubscriptionCheckListCertificationTypeEnum =
  (typeof LearningResourcesUserSubscriptionCheckListCertificationTypeEnum)[keyof typeof LearningResourcesUserSubscriptionCheckListCertificationTypeEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionCheckListDeliveryEnum = {
  Online: "online",
  Hybrid: "hybrid",
  InPerson: "in_person",
  Offline: "offline",
} as const
export type LearningResourcesUserSubscriptionCheckListDeliveryEnum =
  (typeof LearningResourcesUserSubscriptionCheckListDeliveryEnum)[keyof typeof LearningResourcesUserSubscriptionCheckListDeliveryEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionCheckListDepartmentEnum = {
  _1: "1",
  _2: "2",
  _3: "3",
  _4: "4",
  _5: "5",
  _6: "6",
  _7: "7",
  _8: "8",
  _9: "9",
  _10: "10",
  _11: "11",
  _12: "12",
  _14: "14",
  _15: "15",
  _16: "16",
  _17: "17",
  _18: "18",
  _20: "20",
  _21A: "21A",
  _21G: "21G",
  _21H: "21H",
  _21L: "21L",
  _21M: "21M",
  _22: "22",
  _24: "24",
  Cc: "CC",
  CmsW: "CMS-W",
  Ec: "EC",
  Es: "ES",
  Esd: "ESD",
  Hst: "HST",
  Ids: "IDS",
  Mas: "MAS",
  Pe: "PE",
  Sp: "SP",
  Sts: "STS",
  Wgs: "WGS",
} as const
export type LearningResourcesUserSubscriptionCheckListDepartmentEnum =
  (typeof LearningResourcesUserSubscriptionCheckListDepartmentEnum)[keyof typeof LearningResourcesUserSubscriptionCheckListDepartmentEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionCheckListLevelEnum = {
  Undergraduate: "undergraduate",
  Graduate: "graduate",
  HighSchool: "high_school",
  Noncredit: "noncredit",
  Advanced: "advanced",
  Intermediate: "intermediate",
  Introductory: "introductory",
} as const
export type LearningResourcesUserSubscriptionCheckListLevelEnum =
  (typeof LearningResourcesUserSubscriptionCheckListLevelEnum)[keyof typeof LearningResourcesUserSubscriptionCheckListLevelEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionCheckListOfferedByEnum = {
  Mitx: "mitx",
  Ocw: "ocw",
  Bootcamps: "bootcamps",
  Xpro: "xpro",
  Mitpe: "mitpe",
  See: "see",
} as const
export type LearningResourcesUserSubscriptionCheckListOfferedByEnum =
  (typeof LearningResourcesUserSubscriptionCheckListOfferedByEnum)[keyof typeof LearningResourcesUserSubscriptionCheckListOfferedByEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionCheckListPlatformEnum = {
  Edx: "edx",
  Ocw: "ocw",
  Oll: "oll",
  Mitxonline: "mitxonline",
  Bootcamps: "bootcamps",
  Xpro: "xpro",
  Csail: "csail",
  Mitpe: "mitpe",
  See: "see",
  Scc: "scc",
  Ctl: "ctl",
  Whu: "whu",
  Susskind: "susskind",
  Globalalumni: "globalalumni",
  Simplilearn: "simplilearn",
  Emeritus: "emeritus",
  Podcast: "podcast",
  Youtube: "youtube",
  Canvas: "canvas",
} as const
export type LearningResourcesUserSubscriptionCheckListPlatformEnum =
  (typeof LearningResourcesUserSubscriptionCheckListPlatformEnum)[keyof typeof LearningResourcesUserSubscriptionCheckListPlatformEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionCheckListResourceCategoryEnum = {
  Course: "course",
  Program: "program",
  LearningMaterial: "learning_material",
} as const
export type LearningResourcesUserSubscriptionCheckListResourceCategoryEnum =
  (typeof LearningResourcesUserSubscriptionCheckListResourceCategoryEnum)[keyof typeof LearningResourcesUserSubscriptionCheckListResourceCategoryEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionCheckListResourceTypeEnum = {
  Course: "course",
  Program: "program",
  LearningPath: "learning_path",
  Podcast: "podcast",
  PodcastEpisode: "podcast_episode",
  Video: "video",
  VideoPlaylist: "video_playlist",
} as const
export type LearningResourcesUserSubscriptionCheckListResourceTypeEnum =
  (typeof LearningResourcesUserSubscriptionCheckListResourceTypeEnum)[keyof typeof LearningResourcesUserSubscriptionCheckListResourceTypeEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionCheckListSearchModeEnum = {
  BestFields: "best_fields",
  MostFields: "most_fields",
  Phrase: "phrase",
} as const
export type LearningResourcesUserSubscriptionCheckListSearchModeEnum =
  (typeof LearningResourcesUserSubscriptionCheckListSearchModeEnum)[keyof typeof LearningResourcesUserSubscriptionCheckListSearchModeEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionCheckListSortbyEnum = {
  Featured: "featured",
  Id: "id",
  Id2: "-id",
  ReadableId: "readable_id",
  ReadableId2: "-readable_id",
  LastModified: "last_modified",
  LastModified2: "-last_modified",
  New: "new",
  StartDate: "start_date",
  StartDate2: "-start_date",
  Mitcoursenumber: "mitcoursenumber",
  Mitcoursenumber2: "-mitcoursenumber",
  Views: "views",
  Views2: "-views",
  Upcoming: "upcoming",
} as const
export type LearningResourcesUserSubscriptionCheckListSortbyEnum =
  (typeof LearningResourcesUserSubscriptionCheckListSortbyEnum)[keyof typeof LearningResourcesUserSubscriptionCheckListSortbyEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionCheckListSourceTypeEnum = {
  SearchSubscriptionType: "search_subscription_type",
  ChannelSubscriptionType: "channel_subscription_type",
} as const
export type LearningResourcesUserSubscriptionCheckListSourceTypeEnum =
  (typeof LearningResourcesUserSubscriptionCheckListSourceTypeEnum)[keyof typeof LearningResourcesUserSubscriptionCheckListSourceTypeEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionListAggregationsEnum = {
  ResourceType: "resource_type",
  Certification: "certification",
  CertificationType: "certification_type",
  OfferedBy: "offered_by",
  Platform: "platform",
  Topic: "topic",
  Department: "department",
  Level: "level",
  CourseFeature: "course_feature",
  Professional: "professional",
  Free: "free",
  Delivery: "delivery",
  ResourceCategory: "resource_category",
} as const
export type LearningResourcesUserSubscriptionListAggregationsEnum =
  (typeof LearningResourcesUserSubscriptionListAggregationsEnum)[keyof typeof LearningResourcesUserSubscriptionListAggregationsEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionListCertificationTypeEnum = {
  Micromasters: "micromasters",
  Professional: "professional",
  Completion: "completion",
  None: "none",
} as const
export type LearningResourcesUserSubscriptionListCertificationTypeEnum =
  (typeof LearningResourcesUserSubscriptionListCertificationTypeEnum)[keyof typeof LearningResourcesUserSubscriptionListCertificationTypeEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionListDeliveryEnum = {
  Online: "online",
  Hybrid: "hybrid",
  InPerson: "in_person",
  Offline: "offline",
} as const
export type LearningResourcesUserSubscriptionListDeliveryEnum =
  (typeof LearningResourcesUserSubscriptionListDeliveryEnum)[keyof typeof LearningResourcesUserSubscriptionListDeliveryEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionListDepartmentEnum = {
  _1: "1",
  _2: "2",
  _3: "3",
  _4: "4",
  _5: "5",
  _6: "6",
  _7: "7",
  _8: "8",
  _9: "9",
  _10: "10",
  _11: "11",
  _12: "12",
  _14: "14",
  _15: "15",
  _16: "16",
  _17: "17",
  _18: "18",
  _20: "20",
  _21A: "21A",
  _21G: "21G",
  _21H: "21H",
  _21L: "21L",
  _21M: "21M",
  _22: "22",
  _24: "24",
  Cc: "CC",
  CmsW: "CMS-W",
  Ec: "EC",
  Es: "ES",
  Esd: "ESD",
  Hst: "HST",
  Ids: "IDS",
  Mas: "MAS",
  Pe: "PE",
  Sp: "SP",
  Sts: "STS",
  Wgs: "WGS",
} as const
export type LearningResourcesUserSubscriptionListDepartmentEnum =
  (typeof LearningResourcesUserSubscriptionListDepartmentEnum)[keyof typeof LearningResourcesUserSubscriptionListDepartmentEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionListLevelEnum = {
  Undergraduate: "undergraduate",
  Graduate: "graduate",
  HighSchool: "high_school",
  Noncredit: "noncredit",
  Advanced: "advanced",
  Intermediate: "intermediate",
  Introductory: "introductory",
} as const
export type LearningResourcesUserSubscriptionListLevelEnum =
  (typeof LearningResourcesUserSubscriptionListLevelEnum)[keyof typeof LearningResourcesUserSubscriptionListLevelEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionListOfferedByEnum = {
  Mitx: "mitx",
  Ocw: "ocw",
  Bootcamps: "bootcamps",
  Xpro: "xpro",
  Mitpe: "mitpe",
  See: "see",
} as const
export type LearningResourcesUserSubscriptionListOfferedByEnum =
  (typeof LearningResourcesUserSubscriptionListOfferedByEnum)[keyof typeof LearningResourcesUserSubscriptionListOfferedByEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionListPlatformEnum = {
  Edx: "edx",
  Ocw: "ocw",
  Oll: "oll",
  Mitxonline: "mitxonline",
  Bootcamps: "bootcamps",
  Xpro: "xpro",
  Csail: "csail",
  Mitpe: "mitpe",
  See: "see",
  Scc: "scc",
  Ctl: "ctl",
  Whu: "whu",
  Susskind: "susskind",
  Globalalumni: "globalalumni",
  Simplilearn: "simplilearn",
  Emeritus: "emeritus",
  Podcast: "podcast",
  Youtube: "youtube",
  Canvas: "canvas",
} as const
export type LearningResourcesUserSubscriptionListPlatformEnum =
  (typeof LearningResourcesUserSubscriptionListPlatformEnum)[keyof typeof LearningResourcesUserSubscriptionListPlatformEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionListResourceCategoryEnum = {
  Course: "course",
  Program: "program",
  LearningMaterial: "learning_material",
} as const
export type LearningResourcesUserSubscriptionListResourceCategoryEnum =
  (typeof LearningResourcesUserSubscriptionListResourceCategoryEnum)[keyof typeof LearningResourcesUserSubscriptionListResourceCategoryEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionListResourceTypeEnum = {
  Course: "course",
  Program: "program",
  LearningPath: "learning_path",
  Podcast: "podcast",
  PodcastEpisode: "podcast_episode",
  Video: "video",
  VideoPlaylist: "video_playlist",
} as const
export type LearningResourcesUserSubscriptionListResourceTypeEnum =
  (typeof LearningResourcesUserSubscriptionListResourceTypeEnum)[keyof typeof LearningResourcesUserSubscriptionListResourceTypeEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionListSearchModeEnum = {
  BestFields: "best_fields",
  MostFields: "most_fields",
  Phrase: "phrase",
} as const
export type LearningResourcesUserSubscriptionListSearchModeEnum =
  (typeof LearningResourcesUserSubscriptionListSearchModeEnum)[keyof typeof LearningResourcesUserSubscriptionListSearchModeEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionListSortbyEnum = {
  Featured: "featured",
  Id: "id",
  Id2: "-id",
  ReadableId: "readable_id",
  ReadableId2: "-readable_id",
  LastModified: "last_modified",
  LastModified2: "-last_modified",
  New: "new",
  StartDate: "start_date",
  StartDate2: "-start_date",
  Mitcoursenumber: "mitcoursenumber",
  Mitcoursenumber2: "-mitcoursenumber",
  Views: "views",
  Views2: "-views",
  Upcoming: "upcoming",
} as const
export type LearningResourcesUserSubscriptionListSortbyEnum =
  (typeof LearningResourcesUserSubscriptionListSortbyEnum)[keyof typeof LearningResourcesUserSubscriptionListSortbyEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionSubscribeCreateAggregationsEnum =
  {
    ResourceType: "resource_type",
    Certification: "certification",
    CertificationType: "certification_type",
    OfferedBy: "offered_by",
    Platform: "platform",
    Topic: "topic",
    Department: "department",
    Level: "level",
    CourseFeature: "course_feature",
    Professional: "professional",
    Free: "free",
    Delivery: "delivery",
    ResourceCategory: "resource_category",
  } as const
export type LearningResourcesUserSubscriptionSubscribeCreateAggregationsEnum =
  (typeof LearningResourcesUserSubscriptionSubscribeCreateAggregationsEnum)[keyof typeof LearningResourcesUserSubscriptionSubscribeCreateAggregationsEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionSubscribeCreateCertificationTypeEnum =
  {
    Micromasters: "micromasters",
    Professional: "professional",
    Completion: "completion",
    None: "none",
  } as const
export type LearningResourcesUserSubscriptionSubscribeCreateCertificationTypeEnum =
  (typeof LearningResourcesUserSubscriptionSubscribeCreateCertificationTypeEnum)[keyof typeof LearningResourcesUserSubscriptionSubscribeCreateCertificationTypeEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionSubscribeCreateDeliveryEnum = {
  Online: "online",
  Hybrid: "hybrid",
  InPerson: "in_person",
  Offline: "offline",
} as const
export type LearningResourcesUserSubscriptionSubscribeCreateDeliveryEnum =
  (typeof LearningResourcesUserSubscriptionSubscribeCreateDeliveryEnum)[keyof typeof LearningResourcesUserSubscriptionSubscribeCreateDeliveryEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionSubscribeCreateDepartmentEnum = {
  _1: "1",
  _2: "2",
  _3: "3",
  _4: "4",
  _5: "5",
  _6: "6",
  _7: "7",
  _8: "8",
  _9: "9",
  _10: "10",
  _11: "11",
  _12: "12",
  _14: "14",
  _15: "15",
  _16: "16",
  _17: "17",
  _18: "18",
  _20: "20",
  _21A: "21A",
  _21G: "21G",
  _21H: "21H",
  _21L: "21L",
  _21M: "21M",
  _22: "22",
  _24: "24",
  Cc: "CC",
  CmsW: "CMS-W",
  Ec: "EC",
  Es: "ES",
  Esd: "ESD",
  Hst: "HST",
  Ids: "IDS",
  Mas: "MAS",
  Pe: "PE",
  Sp: "SP",
  Sts: "STS",
  Wgs: "WGS",
} as const
export type LearningResourcesUserSubscriptionSubscribeCreateDepartmentEnum =
  (typeof LearningResourcesUserSubscriptionSubscribeCreateDepartmentEnum)[keyof typeof LearningResourcesUserSubscriptionSubscribeCreateDepartmentEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionSubscribeCreateLevelEnum = {
  Undergraduate: "undergraduate",
  Graduate: "graduate",
  HighSchool: "high_school",
  Noncredit: "noncredit",
  Advanced: "advanced",
  Intermediate: "intermediate",
  Introductory: "introductory",
} as const
export type LearningResourcesUserSubscriptionSubscribeCreateLevelEnum =
  (typeof LearningResourcesUserSubscriptionSubscribeCreateLevelEnum)[keyof typeof LearningResourcesUserSubscriptionSubscribeCreateLevelEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionSubscribeCreateOfferedByEnum = {
  Mitx: "mitx",
  Ocw: "ocw",
  Bootcamps: "bootcamps",
  Xpro: "xpro",
  Mitpe: "mitpe",
  See: "see",
} as const
export type LearningResourcesUserSubscriptionSubscribeCreateOfferedByEnum =
  (typeof LearningResourcesUserSubscriptionSubscribeCreateOfferedByEnum)[keyof typeof LearningResourcesUserSubscriptionSubscribeCreateOfferedByEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionSubscribeCreatePlatformEnum = {
  Edx: "edx",
  Ocw: "ocw",
  Oll: "oll",
  Mitxonline: "mitxonline",
  Bootcamps: "bootcamps",
  Xpro: "xpro",
  Csail: "csail",
  Mitpe: "mitpe",
  See: "see",
  Scc: "scc",
  Ctl: "ctl",
  Whu: "whu",
  Susskind: "susskind",
  Globalalumni: "globalalumni",
  Simplilearn: "simplilearn",
  Emeritus: "emeritus",
  Podcast: "podcast",
  Youtube: "youtube",
  Canvas: "canvas",
} as const
export type LearningResourcesUserSubscriptionSubscribeCreatePlatformEnum =
  (typeof LearningResourcesUserSubscriptionSubscribeCreatePlatformEnum)[keyof typeof LearningResourcesUserSubscriptionSubscribeCreatePlatformEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionSubscribeCreateResourceCategoryEnum =
  {
    Course: "course",
    Program: "program",
    LearningMaterial: "learning_material",
  } as const
export type LearningResourcesUserSubscriptionSubscribeCreateResourceCategoryEnum =
  (typeof LearningResourcesUserSubscriptionSubscribeCreateResourceCategoryEnum)[keyof typeof LearningResourcesUserSubscriptionSubscribeCreateResourceCategoryEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionSubscribeCreateResourceTypeEnum =
  {
    Course: "course",
    Program: "program",
    LearningPath: "learning_path",
    Podcast: "podcast",
    PodcastEpisode: "podcast_episode",
    Video: "video",
    VideoPlaylist: "video_playlist",
  } as const
export type LearningResourcesUserSubscriptionSubscribeCreateResourceTypeEnum =
  (typeof LearningResourcesUserSubscriptionSubscribeCreateResourceTypeEnum)[keyof typeof LearningResourcesUserSubscriptionSubscribeCreateResourceTypeEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionSubscribeCreateSearchModeEnum = {
  BestFields: "best_fields",
  MostFields: "most_fields",
  Phrase: "phrase",
} as const
export type LearningResourcesUserSubscriptionSubscribeCreateSearchModeEnum =
  (typeof LearningResourcesUserSubscriptionSubscribeCreateSearchModeEnum)[keyof typeof LearningResourcesUserSubscriptionSubscribeCreateSearchModeEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionSubscribeCreateSortbyEnum = {
  Featured: "featured",
  Id: "id",
  Id2: "-id",
  ReadableId: "readable_id",
  ReadableId2: "-readable_id",
  LastModified: "last_modified",
  LastModified2: "-last_modified",
  New: "new",
  StartDate: "start_date",
  StartDate2: "-start_date",
  Mitcoursenumber: "mitcoursenumber",
  Mitcoursenumber2: "-mitcoursenumber",
  Views: "views",
  Views2: "-views",
  Upcoming: "upcoming",
} as const
export type LearningResourcesUserSubscriptionSubscribeCreateSortbyEnum =
  (typeof LearningResourcesUserSubscriptionSubscribeCreateSortbyEnum)[keyof typeof LearningResourcesUserSubscriptionSubscribeCreateSortbyEnum]
/**
 * @export
 */
export const LearningResourcesUserSubscriptionSubscribeCreateSourceTypeEnum = {
  SearchSubscriptionType: "search_subscription_type",
  ChannelSubscriptionType: "channel_subscription_type",
} as const
export type LearningResourcesUserSubscriptionSubscribeCreateSourceTypeEnum =
  (typeof LearningResourcesUserSubscriptionSubscribeCreateSourceTypeEnum)[keyof typeof LearningResourcesUserSubscriptionSubscribeCreateSourceTypeEnum]
