/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ContentFile,
  LearningResource,
  LearningResourceRelationship,
  PaginatedContentFileList,
  PaginatedLearningResourceList,
  PaginatedLearningResourceRelationshipList,
  PaginatedLearningResourceSummaryList,
  PatchedLearningResourceRelationshipRequest,
  PatchedUserListRelationshipRequest,
  UserListRelationship,
} from '../models/index';
import {
    ContentFileFromJSON,
    ContentFileToJSON,
    LearningResourceFromJSON,
    LearningResourceToJSON,
    LearningResourceRelationshipFromJSON,
    LearningResourceRelationshipToJSON,
    PaginatedContentFileListFromJSON,
    PaginatedContentFileListToJSON,
    PaginatedLearningResourceListFromJSON,
    PaginatedLearningResourceListToJSON,
    PaginatedLearningResourceRelationshipListFromJSON,
    PaginatedLearningResourceRelationshipListToJSON,
    PaginatedLearningResourceSummaryListFromJSON,
    PaginatedLearningResourceSummaryListToJSON,
    PatchedLearningResourceRelationshipRequestFromJSON,
    PatchedLearningResourceRelationshipRequestToJSON,
    PatchedUserListRelationshipRequestFromJSON,
    PatchedUserListRelationshipRequestToJSON,
    UserListRelationshipFromJSON,
    UserListRelationshipToJSON,
} from '../models/index';

export interface LearningResourcesContentfilesListRequest {
    learning_resource_id: number;
    content_feature_type?: Array<string>;
    edx_module_id?: Array<string>;
    limit?: number;
    offered_by?: Array<LearningResourcesContentfilesListOfferedByEnum>;
    offset?: number;
    platform?: Array<LearningResourcesContentfilesListPlatformEnum>;
    resource_id?: Array<number>;
    run_id?: Array<number>;
}

export interface LearningResourcesContentfilesRetrieveRequest {
    id: number;
    learning_resource_id: number;
}

export interface LearningResourcesItemsListRequest {
    learning_resource_id: number;
    limit?: number;
    offset?: number;
    sortby?: string;
}

export interface LearningResourcesItemsRetrieveRequest {
    id: number;
    learning_resource_id: number;
}

export interface LearningResourcesLearningPathsPartialUpdateRequest {
    id: number;
    learning_path_id?: Array<number>;
    PatchedLearningResourceRelationshipRequest?: PatchedLearningResourceRelationshipRequest;
}

export interface LearningResourcesListRequest {
    certification?: boolean;
    certification_type?: Array<LearningResourcesListCertificationTypeEnum>;
    course_feature?: Array<string>;
    delivery?: Array<Array<LearningResourcesListDeliveryEnum>>;
    department?: Array<LearningResourcesListDepartmentEnum>;
    free?: boolean;
    level?: Array<LearningResourcesListLevelEnum>;
    limit?: number;
    offered_by?: Array<LearningResourcesListOfferedByEnum>;
    offset?: number;
    platform?: Array<LearningResourcesListPlatformEnum>;
    professional?: boolean;
    readable_id?: Array<string>;
    resource_category?: Array<LearningResourcesListResourceCategoryEnum>;
    resource_type?: Array<LearningResourcesListResourceTypeEnum>;
    sortby?: LearningResourcesListSortbyEnum;
    topic?: Array<string>;
}

export interface LearningResourcesRetrieveRequest {
    id: number;
}

export interface LearningResourcesSimilarListRequest {
    id: number;
    certification?: boolean;
    certification_type?: Array<LearningResourcesSimilarListCertificationTypeEnum>;
    course_feature?: Array<string>;
    delivery?: Array<Array<LearningResourcesSimilarListDeliveryEnum>>;
    department?: Array<LearningResourcesSimilarListDepartmentEnum>;
    free?: boolean;
    level?: Array<LearningResourcesSimilarListLevelEnum>;
    limit?: number;
    offered_by?: Array<LearningResourcesSimilarListOfferedByEnum>;
    platform?: Array<LearningResourcesSimilarListPlatformEnum>;
    professional?: boolean;
    readable_id?: Array<string>;
    resource_category?: Array<LearningResourcesSimilarListResourceCategoryEnum>;
    resource_type?: Array<LearningResourcesSimilarListResourceTypeEnum>;
    sortby?: LearningResourcesSimilarListSortbyEnum;
    topic?: Array<string>;
}

export interface LearningResourcesSummaryListRequest {
    certification?: boolean;
    certification_type?: Array<LearningResourcesSummaryListCertificationTypeEnum>;
    course_feature?: Array<string>;
    delivery?: Array<Array<LearningResourcesSummaryListDeliveryEnum>>;
    department?: Array<LearningResourcesSummaryListDepartmentEnum>;
    free?: boolean;
    level?: Array<LearningResourcesSummaryListLevelEnum>;
    limit?: number;
    offered_by?: Array<LearningResourcesSummaryListOfferedByEnum>;
    offset?: number;
    platform?: Array<LearningResourcesSummaryListPlatformEnum>;
    professional?: boolean;
    readable_id?: Array<string>;
    resource_category?: Array<LearningResourcesSummaryListResourceCategoryEnum>;
    resource_type?: Array<LearningResourcesSummaryListResourceTypeEnum>;
    sortby?: LearningResourcesSummaryListSortbyEnum;
    topic?: Array<string>;
}

export interface LearningResourcesUserlistsPartialUpdateRequest {
    id: number;
    userlist_id?: Array<number>;
    PatchedUserListRelationshipRequest?: PatchedUserListRelationshipRequest;
}

export interface LearningResourcesVectorSimilarListRequest {
    id: number;
    certification?: boolean;
    certification_type?: Array<LearningResourcesVectorSimilarListCertificationTypeEnum>;
    course_feature?: Array<string>;
    delivery?: Array<Array<LearningResourcesVectorSimilarListDeliveryEnum>>;
    department?: Array<LearningResourcesVectorSimilarListDepartmentEnum>;
    free?: boolean;
    level?: Array<LearningResourcesVectorSimilarListLevelEnum>;
    limit?: number;
    offered_by?: Array<LearningResourcesVectorSimilarListOfferedByEnum>;
    platform?: Array<LearningResourcesVectorSimilarListPlatformEnum>;
    professional?: boolean;
    readable_id?: Array<string>;
    resource_category?: Array<LearningResourcesVectorSimilarListResourceCategoryEnum>;
    resource_type?: Array<LearningResourcesVectorSimilarListResourceTypeEnum>;
    sortby?: LearningResourcesVectorSimilarListSortbyEnum;
    topic?: Array<string>;
}

/**
 * 
 */
export class LearningResourcesApi extends runtime.BaseAPI {

    /**
     * Show content files for a learning resource
     * Learning Resource Content File List
     */
    async learningResourcesContentfilesListRaw(requestParameters: LearningResourcesContentfilesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedContentFileList>> {
        if (requestParameters.learning_resource_id === null || requestParameters.learning_resource_id === undefined) {
            throw new runtime.RequiredError('learning_resource_id','Required parameter requestParameters.learning_resource_id was null or undefined when calling learningResourcesContentfilesList.');
        }

        const queryParameters: any = {};

        if (requestParameters.content_feature_type) {
            queryParameters['content_feature_type'] = requestParameters.content_feature_type.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.edx_module_id) {
            queryParameters['edx_module_id'] = requestParameters.edx_module_id.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offered_by) {
            queryParameters['offered_by'] = requestParameters.offered_by;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.platform) {
            queryParameters['platform'] = requestParameters.platform;
        }

        if (requestParameters.resource_id) {
            queryParameters['resource_id'] = requestParameters.resource_id.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.run_id) {
            queryParameters['run_id'] = requestParameters.run_id.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/learning_resources/{learning_resource_id}/contentfiles/`.replace(`{${"learning_resource_id"}}`, encodeURIComponent(String(requestParameters.learning_resource_id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedContentFileListFromJSON(jsonValue));
    }

    /**
     * Show content files for a learning resource
     * Learning Resource Content File List
     */
    async learningResourcesContentfilesList(requestParameters: LearningResourcesContentfilesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedContentFileList> {
        const response = await this.learningResourcesContentfilesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Show content files for a learning resource
     * Learning Resource Content File Retrieve
     */
    async learningResourcesContentfilesRetrieveRaw(requestParameters: LearningResourcesContentfilesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContentFile>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling learningResourcesContentfilesRetrieve.');
        }

        if (requestParameters.learning_resource_id === null || requestParameters.learning_resource_id === undefined) {
            throw new runtime.RequiredError('learning_resource_id','Required parameter requestParameters.learning_resource_id was null or undefined when calling learningResourcesContentfilesRetrieve.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/learning_resources/{learning_resource_id}/contentfiles/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"learning_resource_id"}}`, encodeURIComponent(String(requestParameters.learning_resource_id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContentFileFromJSON(jsonValue));
    }

    /**
     * Show content files for a learning resource
     * Learning Resource Content File Retrieve
     */
    async learningResourcesContentfilesRetrieve(requestParameters: LearningResourcesContentfilesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContentFile> {
        const response = await this.learningResourcesContentfilesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a list of related learning resources for a learning resource.
     * Nested Learning Resource List
     */
    async learningResourcesItemsListRaw(requestParameters: LearningResourcesItemsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedLearningResourceRelationshipList>> {
        if (requestParameters.learning_resource_id === null || requestParameters.learning_resource_id === undefined) {
            throw new runtime.RequiredError('learning_resource_id','Required parameter requestParameters.learning_resource_id was null or undefined when calling learningResourcesItemsList.');
        }

        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.sortby !== undefined) {
            queryParameters['sortby'] = requestParameters.sortby;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/learning_resources/{learning_resource_id}/items/`.replace(`{${"learning_resource_id"}}`, encodeURIComponent(String(requestParameters.learning_resource_id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedLearningResourceRelationshipListFromJSON(jsonValue));
    }

    /**
     * Get a list of related learning resources for a learning resource.
     * Nested Learning Resource List
     */
    async learningResourcesItemsList(requestParameters: LearningResourcesItemsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedLearningResourceRelationshipList> {
        const response = await this.learningResourcesItemsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a singe related learning resource for a learning resource.
     * Nested Learning Resource Retrieve
     */
    async learningResourcesItemsRetrieveRaw(requestParameters: LearningResourcesItemsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LearningResourceRelationship>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling learningResourcesItemsRetrieve.');
        }

        if (requestParameters.learning_resource_id === null || requestParameters.learning_resource_id === undefined) {
            throw new runtime.RequiredError('learning_resource_id','Required parameter requestParameters.learning_resource_id was null or undefined when calling learningResourcesItemsRetrieve.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/learning_resources/{learning_resource_id}/items/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"learning_resource_id"}}`, encodeURIComponent(String(requestParameters.learning_resource_id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LearningResourceRelationshipFromJSON(jsonValue));
    }

    /**
     * Get a singe related learning resource for a learning resource.
     * Nested Learning Resource Retrieve
     */
    async learningResourcesItemsRetrieve(requestParameters: LearningResourcesItemsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LearningResourceRelationship> {
        const response = await this.learningResourcesItemsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set Learning Path Relationships on a given Learning Resource.
     * Set Learning Path Relationships
     */
    async learningResourcesLearningPathsPartialUpdateRaw(requestParameters: LearningResourcesLearningPathsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LearningResourceRelationship>>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling learningResourcesLearningPathsPartialUpdate.');
        }

        const queryParameters: any = {};

        if (requestParameters.learning_path_id) {
            queryParameters['learning_path_id'] = requestParameters.learning_path_id;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/learning_resources/{id}/learning_paths/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedLearningResourceRelationshipRequestToJSON(requestParameters.PatchedLearningResourceRelationshipRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LearningResourceRelationshipFromJSON));
    }

    /**
     * Set Learning Path Relationships on a given Learning Resource.
     * Set Learning Path Relationships
     */
    async learningResourcesLearningPathsPartialUpdate(requestParameters: LearningResourcesLearningPathsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LearningResourceRelationship>> {
        const response = await this.learningResourcesLearningPathsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a paginated list of learning resources.
     * List
     */
    async learningResourcesListRaw(requestParameters: LearningResourcesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedLearningResourceList>> {
        const queryParameters: any = {};

        if (requestParameters.certification !== undefined) {
            queryParameters['certification'] = requestParameters.certification;
        }

        if (requestParameters.certification_type) {
            queryParameters['certification_type'] = requestParameters.certification_type;
        }

        if (requestParameters.course_feature) {
            queryParameters['course_feature'] = requestParameters.course_feature.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.delivery) {
            queryParameters['delivery'] = requestParameters.delivery;
        }

        if (requestParameters.department) {
            queryParameters['department'] = requestParameters.department;
        }

        if (requestParameters.free !== undefined) {
            queryParameters['free'] = requestParameters.free;
        }

        if (requestParameters.level) {
            queryParameters['level'] = requestParameters.level;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offered_by) {
            queryParameters['offered_by'] = requestParameters.offered_by;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.platform) {
            queryParameters['platform'] = requestParameters.platform;
        }

        if (requestParameters.professional !== undefined) {
            queryParameters['professional'] = requestParameters.professional;
        }

        if (requestParameters.readable_id) {
            queryParameters['readable_id'] = requestParameters.readable_id.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.resource_category) {
            queryParameters['resource_category'] = requestParameters.resource_category;
        }

        if (requestParameters.resource_type) {
            queryParameters['resource_type'] = requestParameters.resource_type;
        }

        if (requestParameters.sortby !== undefined) {
            queryParameters['sortby'] = requestParameters.sortby;
        }

        if (requestParameters.topic) {
            queryParameters['topic'] = requestParameters.topic.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/learning_resources/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedLearningResourceListFromJSON(jsonValue));
    }

    /**
     * Get a paginated list of learning resources.
     * List
     */
    async learningResourcesList(requestParameters: LearningResourcesListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedLearningResourceList> {
        const response = await this.learningResourcesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a single learning resource.
     * Retrieve
     */
    async learningResourcesRetrieveRaw(requestParameters: LearningResourcesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LearningResource>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling learningResourcesRetrieve.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/learning_resources/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LearningResourceFromJSON(jsonValue));
    }

    /**
     * Retrieve a single learning resource.
     * Retrieve
     */
    async learningResourcesRetrieve(requestParameters: LearningResourcesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LearningResource> {
        const response = await this.learningResourcesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch similar learning resources  Args: id (integer): The id of the learning resource  Returns: QuerySet of similar LearningResource for the resource matching the id parameter
     * Get similar resources
     */
    async learningResourcesSimilarListRaw(requestParameters: LearningResourcesSimilarListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LearningResource>>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling learningResourcesSimilarList.');
        }

        const queryParameters: any = {};

        if (requestParameters.certification !== undefined) {
            queryParameters['certification'] = requestParameters.certification;
        }

        if (requestParameters.certification_type) {
            queryParameters['certification_type'] = requestParameters.certification_type;
        }

        if (requestParameters.course_feature) {
            queryParameters['course_feature'] = requestParameters.course_feature.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.delivery) {
            queryParameters['delivery'] = requestParameters.delivery;
        }

        if (requestParameters.department) {
            queryParameters['department'] = requestParameters.department;
        }

        if (requestParameters.free !== undefined) {
            queryParameters['free'] = requestParameters.free;
        }

        if (requestParameters.level) {
            queryParameters['level'] = requestParameters.level;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offered_by) {
            queryParameters['offered_by'] = requestParameters.offered_by;
        }

        if (requestParameters.platform) {
            queryParameters['platform'] = requestParameters.platform;
        }

        if (requestParameters.professional !== undefined) {
            queryParameters['professional'] = requestParameters.professional;
        }

        if (requestParameters.readable_id) {
            queryParameters['readable_id'] = requestParameters.readable_id.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.resource_category) {
            queryParameters['resource_category'] = requestParameters.resource_category;
        }

        if (requestParameters.resource_type) {
            queryParameters['resource_type'] = requestParameters.resource_type;
        }

        if (requestParameters.sortby !== undefined) {
            queryParameters['sortby'] = requestParameters.sortby;
        }

        if (requestParameters.topic) {
            queryParameters['topic'] = requestParameters.topic.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/learning_resources/{id}/similar/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LearningResourceFromJSON));
    }

    /**
     * Fetch similar learning resources  Args: id (integer): The id of the learning resource  Returns: QuerySet of similar LearningResource for the resource matching the id parameter
     * Get similar resources
     */
    async learningResourcesSimilarList(requestParameters: LearningResourcesSimilarListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LearningResource>> {
        const response = await this.learningResourcesSimilarListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a paginated list of learning resources with summary fields
     * Get learning resources summary
     */
    async learningResourcesSummaryListRaw(requestParameters: LearningResourcesSummaryListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedLearningResourceSummaryList>> {
        const queryParameters: any = {};

        if (requestParameters.certification !== undefined) {
            queryParameters['certification'] = requestParameters.certification;
        }

        if (requestParameters.certification_type) {
            queryParameters['certification_type'] = requestParameters.certification_type;
        }

        if (requestParameters.course_feature) {
            queryParameters['course_feature'] = requestParameters.course_feature.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.delivery) {
            queryParameters['delivery'] = requestParameters.delivery;
        }

        if (requestParameters.department) {
            queryParameters['department'] = requestParameters.department;
        }

        if (requestParameters.free !== undefined) {
            queryParameters['free'] = requestParameters.free;
        }

        if (requestParameters.level) {
            queryParameters['level'] = requestParameters.level;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offered_by) {
            queryParameters['offered_by'] = requestParameters.offered_by;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.platform) {
            queryParameters['platform'] = requestParameters.platform;
        }

        if (requestParameters.professional !== undefined) {
            queryParameters['professional'] = requestParameters.professional;
        }

        if (requestParameters.readable_id) {
            queryParameters['readable_id'] = requestParameters.readable_id.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.resource_category) {
            queryParameters['resource_category'] = requestParameters.resource_category;
        }

        if (requestParameters.resource_type) {
            queryParameters['resource_type'] = requestParameters.resource_type;
        }

        if (requestParameters.sortby !== undefined) {
            queryParameters['sortby'] = requestParameters.sortby;
        }

        if (requestParameters.topic) {
            queryParameters['topic'] = requestParameters.topic.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/learning_resources/summary/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedLearningResourceSummaryListFromJSON(jsonValue));
    }

    /**
     * Get a paginated list of learning resources with summary fields
     * Get learning resources summary
     */
    async learningResourcesSummaryList(requestParameters: LearningResourcesSummaryListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedLearningResourceSummaryList> {
        const response = await this.learningResourcesSummaryListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set User List Relationships on a given Learning Resource.
     * Set User List Relationships
     */
    async learningResourcesUserlistsPartialUpdateRaw(requestParameters: LearningResourcesUserlistsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserListRelationship>>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling learningResourcesUserlistsPartialUpdate.');
        }

        const queryParameters: any = {};

        if (requestParameters.userlist_id) {
            queryParameters['userlist_id'] = requestParameters.userlist_id;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/learning_resources/{id}/userlists/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedUserListRelationshipRequestToJSON(requestParameters.PatchedUserListRelationshipRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserListRelationshipFromJSON));
    }

    /**
     * Set User List Relationships on a given Learning Resource.
     * Set User List Relationships
     */
    async learningResourcesUserlistsPartialUpdate(requestParameters: LearningResourcesUserlistsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserListRelationship>> {
        const response = await this.learningResourcesUserlistsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch similar learning resources  Args: id (integer): The id of the learning resource  Returns: QuerySet of similar LearningResource for the resource matching the id parameter
     * Get similar resources using vector embeddings
     */
    async learningResourcesVectorSimilarListRaw(requestParameters: LearningResourcesVectorSimilarListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LearningResource>>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling learningResourcesVectorSimilarList.');
        }

        const queryParameters: any = {};

        if (requestParameters.certification !== undefined) {
            queryParameters['certification'] = requestParameters.certification;
        }

        if (requestParameters.certification_type) {
            queryParameters['certification_type'] = requestParameters.certification_type;
        }

        if (requestParameters.course_feature) {
            queryParameters['course_feature'] = requestParameters.course_feature.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.delivery) {
            queryParameters['delivery'] = requestParameters.delivery;
        }

        if (requestParameters.department) {
            queryParameters['department'] = requestParameters.department;
        }

        if (requestParameters.free !== undefined) {
            queryParameters['free'] = requestParameters.free;
        }

        if (requestParameters.level) {
            queryParameters['level'] = requestParameters.level;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offered_by) {
            queryParameters['offered_by'] = requestParameters.offered_by;
        }

        if (requestParameters.platform) {
            queryParameters['platform'] = requestParameters.platform;
        }

        if (requestParameters.professional !== undefined) {
            queryParameters['professional'] = requestParameters.professional;
        }

        if (requestParameters.readable_id) {
            queryParameters['readable_id'] = requestParameters.readable_id.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.resource_category) {
            queryParameters['resource_category'] = requestParameters.resource_category;
        }

        if (requestParameters.resource_type) {
            queryParameters['resource_type'] = requestParameters.resource_type;
        }

        if (requestParameters.sortby !== undefined) {
            queryParameters['sortby'] = requestParameters.sortby;
        }

        if (requestParameters.topic) {
            queryParameters['topic'] = requestParameters.topic.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/learning_resources/{id}/vector_similar/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LearningResourceFromJSON));
    }

    /**
     * Fetch similar learning resources  Args: id (integer): The id of the learning resource  Returns: QuerySet of similar LearningResource for the resource matching the id parameter
     * Get similar resources using vector embeddings
     */
    async learningResourcesVectorSimilarList(requestParameters: LearningResourcesVectorSimilarListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LearningResource>> {
        const response = await this.learningResourcesVectorSimilarListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const LearningResourcesContentfilesListOfferedByEnum = {
    Bootcamps: 'bootcamps',
    Mitpe: 'mitpe',
    Mitx: 'mitx',
    Ocw: 'ocw',
    See: 'see',
    Xpro: 'xpro'
} as const;
export type LearningResourcesContentfilesListOfferedByEnum = typeof LearningResourcesContentfilesListOfferedByEnum[keyof typeof LearningResourcesContentfilesListOfferedByEnum];
/**
 * @export
 */
export const LearningResourcesContentfilesListPlatformEnum = {
    Bootcamps: 'bootcamps',
    Canvas: 'canvas',
    Csail: 'csail',
    Ctl: 'ctl',
    Edx: 'edx',
    Emeritus: 'emeritus',
    Globalalumni: 'globalalumni',
    Mitpe: 'mitpe',
    Mitxonline: 'mitxonline',
    Ocw: 'ocw',
    Oll: 'oll',
    Podcast: 'podcast',
    Scc: 'scc',
    See: 'see',
    Simplilearn: 'simplilearn',
    Susskind: 'susskind',
    Whu: 'whu',
    Xpro: 'xpro',
    Youtube: 'youtube'
} as const;
export type LearningResourcesContentfilesListPlatformEnum = typeof LearningResourcesContentfilesListPlatformEnum[keyof typeof LearningResourcesContentfilesListPlatformEnum];
/**
 * @export
 */
export const LearningResourcesListCertificationTypeEnum = {
    Completion: 'completion',
    Micromasters: 'micromasters',
    None: 'none',
    Professional: 'professional'
} as const;
export type LearningResourcesListCertificationTypeEnum = typeof LearningResourcesListCertificationTypeEnum[keyof typeof LearningResourcesListCertificationTypeEnum];
/**
 * @export
 */
export const LearningResourcesListDeliveryEnum = {
    Online: 'online',
    Hybrid: 'hybrid',
    InPerson: 'in_person',
    Offline: 'offline'
} as const;
export type LearningResourcesListDeliveryEnum = typeof LearningResourcesListDeliveryEnum[keyof typeof LearningResourcesListDeliveryEnum];
/**
 * @export
 */
export const LearningResourcesListDepartmentEnum = {
    _1: '1',
    _10: '10',
    _11: '11',
    _12: '12',
    _14: '14',
    _15: '15',
    _16: '16',
    _17: '17',
    _18: '18',
    _2: '2',
    _20: '20',
    _21A: '21A',
    _21G: '21G',
    _21H: '21H',
    _21L: '21L',
    _21M: '21M',
    _22: '22',
    _24: '24',
    _3: '3',
    _4: '4',
    _5: '5',
    _6: '6',
    _7: '7',
    _8: '8',
    _9: '9',
    Cc: 'CC',
    CmsW: 'CMS-W',
    Ec: 'EC',
    Es: 'ES',
    Esd: 'ESD',
    Hst: 'HST',
    Ids: 'IDS',
    Mas: 'MAS',
    Pe: 'PE',
    Sp: 'SP',
    Sts: 'STS',
    Wgs: 'WGS'
} as const;
export type LearningResourcesListDepartmentEnum = typeof LearningResourcesListDepartmentEnum[keyof typeof LearningResourcesListDepartmentEnum];
/**
 * @export
 */
export const LearningResourcesListLevelEnum = {
    Advanced: 'advanced',
    Graduate: 'graduate',
    HighSchool: 'high_school',
    Intermediate: 'intermediate',
    Introductory: 'introductory',
    Noncredit: 'noncredit',
    Undergraduate: 'undergraduate'
} as const;
export type LearningResourcesListLevelEnum = typeof LearningResourcesListLevelEnum[keyof typeof LearningResourcesListLevelEnum];
/**
 * @export
 */
export const LearningResourcesListOfferedByEnum = {
    Bootcamps: 'bootcamps',
    Mitpe: 'mitpe',
    Mitx: 'mitx',
    Ocw: 'ocw',
    See: 'see',
    Xpro: 'xpro'
} as const;
export type LearningResourcesListOfferedByEnum = typeof LearningResourcesListOfferedByEnum[keyof typeof LearningResourcesListOfferedByEnum];
/**
 * @export
 */
export const LearningResourcesListPlatformEnum = {
    Bootcamps: 'bootcamps',
    Canvas: 'canvas',
    Csail: 'csail',
    Ctl: 'ctl',
    Edx: 'edx',
    Emeritus: 'emeritus',
    Globalalumni: 'globalalumni',
    Mitpe: 'mitpe',
    Mitxonline: 'mitxonline',
    Ocw: 'ocw',
    Oll: 'oll',
    Podcast: 'podcast',
    Scc: 'scc',
    See: 'see',
    Simplilearn: 'simplilearn',
    Susskind: 'susskind',
    Whu: 'whu',
    Xpro: 'xpro',
    Youtube: 'youtube'
} as const;
export type LearningResourcesListPlatformEnum = typeof LearningResourcesListPlatformEnum[keyof typeof LearningResourcesListPlatformEnum];
/**
 * @export
 */
export const LearningResourcesListResourceCategoryEnum = {
    Course: 'course',
    LearningMaterial: 'learning_material',
    Program: 'program'
} as const;
export type LearningResourcesListResourceCategoryEnum = typeof LearningResourcesListResourceCategoryEnum[keyof typeof LearningResourcesListResourceCategoryEnum];
/**
 * @export
 */
export const LearningResourcesListResourceTypeEnum = {
    Course: 'course',
    LearningPath: 'learning_path',
    Podcast: 'podcast',
    PodcastEpisode: 'podcast_episode',
    Program: 'program',
    Video: 'video',
    VideoPlaylist: 'video_playlist'
} as const;
export type LearningResourcesListResourceTypeEnum = typeof LearningResourcesListResourceTypeEnum[keyof typeof LearningResourcesListResourceTypeEnum];
/**
 * @export
 */
export const LearningResourcesListSortbyEnum = {
    Id: '-id',
    LastModified: '-last_modified',
    Mitcoursenumber: '-mitcoursenumber',
    ReadableId: '-readable_id',
    StartDate: '-start_date',
    Views: '-views',
    Id2: 'id',
    LastModified2: 'last_modified',
    Mitcoursenumber2: 'mitcoursenumber',
    New: 'new',
    ReadableId2: 'readable_id',
    StartDate2: 'start_date',
    Upcoming: 'upcoming',
    Views2: 'views'
} as const;
export type LearningResourcesListSortbyEnum = typeof LearningResourcesListSortbyEnum[keyof typeof LearningResourcesListSortbyEnum];
/**
 * @export
 */
export const LearningResourcesSimilarListCertificationTypeEnum = {
    Completion: 'completion',
    Micromasters: 'micromasters',
    None: 'none',
    Professional: 'professional'
} as const;
export type LearningResourcesSimilarListCertificationTypeEnum = typeof LearningResourcesSimilarListCertificationTypeEnum[keyof typeof LearningResourcesSimilarListCertificationTypeEnum];
/**
 * @export
 */
export const LearningResourcesSimilarListDeliveryEnum = {
    Online: 'online',
    Hybrid: 'hybrid',
    InPerson: 'in_person',
    Offline: 'offline'
} as const;
export type LearningResourcesSimilarListDeliveryEnum = typeof LearningResourcesSimilarListDeliveryEnum[keyof typeof LearningResourcesSimilarListDeliveryEnum];
/**
 * @export
 */
export const LearningResourcesSimilarListDepartmentEnum = {
    _1: '1',
    _10: '10',
    _11: '11',
    _12: '12',
    _14: '14',
    _15: '15',
    _16: '16',
    _17: '17',
    _18: '18',
    _2: '2',
    _20: '20',
    _21A: '21A',
    _21G: '21G',
    _21H: '21H',
    _21L: '21L',
    _21M: '21M',
    _22: '22',
    _24: '24',
    _3: '3',
    _4: '4',
    _5: '5',
    _6: '6',
    _7: '7',
    _8: '8',
    _9: '9',
    Cc: 'CC',
    CmsW: 'CMS-W',
    Ec: 'EC',
    Es: 'ES',
    Esd: 'ESD',
    Hst: 'HST',
    Ids: 'IDS',
    Mas: 'MAS',
    Pe: 'PE',
    Sp: 'SP',
    Sts: 'STS',
    Wgs: 'WGS'
} as const;
export type LearningResourcesSimilarListDepartmentEnum = typeof LearningResourcesSimilarListDepartmentEnum[keyof typeof LearningResourcesSimilarListDepartmentEnum];
/**
 * @export
 */
export const LearningResourcesSimilarListLevelEnum = {
    Advanced: 'advanced',
    Graduate: 'graduate',
    HighSchool: 'high_school',
    Intermediate: 'intermediate',
    Introductory: 'introductory',
    Noncredit: 'noncredit',
    Undergraduate: 'undergraduate'
} as const;
export type LearningResourcesSimilarListLevelEnum = typeof LearningResourcesSimilarListLevelEnum[keyof typeof LearningResourcesSimilarListLevelEnum];
/**
 * @export
 */
export const LearningResourcesSimilarListOfferedByEnum = {
    Bootcamps: 'bootcamps',
    Mitpe: 'mitpe',
    Mitx: 'mitx',
    Ocw: 'ocw',
    See: 'see',
    Xpro: 'xpro'
} as const;
export type LearningResourcesSimilarListOfferedByEnum = typeof LearningResourcesSimilarListOfferedByEnum[keyof typeof LearningResourcesSimilarListOfferedByEnum];
/**
 * @export
 */
export const LearningResourcesSimilarListPlatformEnum = {
    Bootcamps: 'bootcamps',
    Canvas: 'canvas',
    Csail: 'csail',
    Ctl: 'ctl',
    Edx: 'edx',
    Emeritus: 'emeritus',
    Globalalumni: 'globalalumni',
    Mitpe: 'mitpe',
    Mitxonline: 'mitxonline',
    Ocw: 'ocw',
    Oll: 'oll',
    Podcast: 'podcast',
    Scc: 'scc',
    See: 'see',
    Simplilearn: 'simplilearn',
    Susskind: 'susskind',
    Whu: 'whu',
    Xpro: 'xpro',
    Youtube: 'youtube'
} as const;
export type LearningResourcesSimilarListPlatformEnum = typeof LearningResourcesSimilarListPlatformEnum[keyof typeof LearningResourcesSimilarListPlatformEnum];
/**
 * @export
 */
export const LearningResourcesSimilarListResourceCategoryEnum = {
    Course: 'course',
    LearningMaterial: 'learning_material',
    Program: 'program'
} as const;
export type LearningResourcesSimilarListResourceCategoryEnum = typeof LearningResourcesSimilarListResourceCategoryEnum[keyof typeof LearningResourcesSimilarListResourceCategoryEnum];
/**
 * @export
 */
export const LearningResourcesSimilarListResourceTypeEnum = {
    Course: 'course',
    LearningPath: 'learning_path',
    Podcast: 'podcast',
    PodcastEpisode: 'podcast_episode',
    Program: 'program',
    Video: 'video',
    VideoPlaylist: 'video_playlist'
} as const;
export type LearningResourcesSimilarListResourceTypeEnum = typeof LearningResourcesSimilarListResourceTypeEnum[keyof typeof LearningResourcesSimilarListResourceTypeEnum];
/**
 * @export
 */
export const LearningResourcesSimilarListSortbyEnum = {
    Id: '-id',
    LastModified: '-last_modified',
    Mitcoursenumber: '-mitcoursenumber',
    ReadableId: '-readable_id',
    StartDate: '-start_date',
    Views: '-views',
    Id2: 'id',
    LastModified2: 'last_modified',
    Mitcoursenumber2: 'mitcoursenumber',
    New: 'new',
    ReadableId2: 'readable_id',
    StartDate2: 'start_date',
    Upcoming: 'upcoming',
    Views2: 'views'
} as const;
export type LearningResourcesSimilarListSortbyEnum = typeof LearningResourcesSimilarListSortbyEnum[keyof typeof LearningResourcesSimilarListSortbyEnum];
/**
 * @export
 */
export const LearningResourcesSummaryListCertificationTypeEnum = {
    Completion: 'completion',
    Micromasters: 'micromasters',
    None: 'none',
    Professional: 'professional'
} as const;
export type LearningResourcesSummaryListCertificationTypeEnum = typeof LearningResourcesSummaryListCertificationTypeEnum[keyof typeof LearningResourcesSummaryListCertificationTypeEnum];
/**
 * @export
 */
export const LearningResourcesSummaryListDeliveryEnum = {
    Online: 'online',
    Hybrid: 'hybrid',
    InPerson: 'in_person',
    Offline: 'offline'
} as const;
export type LearningResourcesSummaryListDeliveryEnum = typeof LearningResourcesSummaryListDeliveryEnum[keyof typeof LearningResourcesSummaryListDeliveryEnum];
/**
 * @export
 */
export const LearningResourcesSummaryListDepartmentEnum = {
    _1: '1',
    _10: '10',
    _11: '11',
    _12: '12',
    _14: '14',
    _15: '15',
    _16: '16',
    _17: '17',
    _18: '18',
    _2: '2',
    _20: '20',
    _21A: '21A',
    _21G: '21G',
    _21H: '21H',
    _21L: '21L',
    _21M: '21M',
    _22: '22',
    _24: '24',
    _3: '3',
    _4: '4',
    _5: '5',
    _6: '6',
    _7: '7',
    _8: '8',
    _9: '9',
    Cc: 'CC',
    CmsW: 'CMS-W',
    Ec: 'EC',
    Es: 'ES',
    Esd: 'ESD',
    Hst: 'HST',
    Ids: 'IDS',
    Mas: 'MAS',
    Pe: 'PE',
    Sp: 'SP',
    Sts: 'STS',
    Wgs: 'WGS'
} as const;
export type LearningResourcesSummaryListDepartmentEnum = typeof LearningResourcesSummaryListDepartmentEnum[keyof typeof LearningResourcesSummaryListDepartmentEnum];
/**
 * @export
 */
export const LearningResourcesSummaryListLevelEnum = {
    Advanced: 'advanced',
    Graduate: 'graduate',
    HighSchool: 'high_school',
    Intermediate: 'intermediate',
    Introductory: 'introductory',
    Noncredit: 'noncredit',
    Undergraduate: 'undergraduate'
} as const;
export type LearningResourcesSummaryListLevelEnum = typeof LearningResourcesSummaryListLevelEnum[keyof typeof LearningResourcesSummaryListLevelEnum];
/**
 * @export
 */
export const LearningResourcesSummaryListOfferedByEnum = {
    Bootcamps: 'bootcamps',
    Mitpe: 'mitpe',
    Mitx: 'mitx',
    Ocw: 'ocw',
    See: 'see',
    Xpro: 'xpro'
} as const;
export type LearningResourcesSummaryListOfferedByEnum = typeof LearningResourcesSummaryListOfferedByEnum[keyof typeof LearningResourcesSummaryListOfferedByEnum];
/**
 * @export
 */
export const LearningResourcesSummaryListPlatformEnum = {
    Bootcamps: 'bootcamps',
    Canvas: 'canvas',
    Csail: 'csail',
    Ctl: 'ctl',
    Edx: 'edx',
    Emeritus: 'emeritus',
    Globalalumni: 'globalalumni',
    Mitpe: 'mitpe',
    Mitxonline: 'mitxonline',
    Ocw: 'ocw',
    Oll: 'oll',
    Podcast: 'podcast',
    Scc: 'scc',
    See: 'see',
    Simplilearn: 'simplilearn',
    Susskind: 'susskind',
    Whu: 'whu',
    Xpro: 'xpro',
    Youtube: 'youtube'
} as const;
export type LearningResourcesSummaryListPlatformEnum = typeof LearningResourcesSummaryListPlatformEnum[keyof typeof LearningResourcesSummaryListPlatformEnum];
/**
 * @export
 */
export const LearningResourcesSummaryListResourceCategoryEnum = {
    Course: 'course',
    LearningMaterial: 'learning_material',
    Program: 'program'
} as const;
export type LearningResourcesSummaryListResourceCategoryEnum = typeof LearningResourcesSummaryListResourceCategoryEnum[keyof typeof LearningResourcesSummaryListResourceCategoryEnum];
/**
 * @export
 */
export const LearningResourcesSummaryListResourceTypeEnum = {
    Course: 'course',
    LearningPath: 'learning_path',
    Podcast: 'podcast',
    PodcastEpisode: 'podcast_episode',
    Program: 'program',
    Video: 'video',
    VideoPlaylist: 'video_playlist'
} as const;
export type LearningResourcesSummaryListResourceTypeEnum = typeof LearningResourcesSummaryListResourceTypeEnum[keyof typeof LearningResourcesSummaryListResourceTypeEnum];
/**
 * @export
 */
export const LearningResourcesSummaryListSortbyEnum = {
    Id: '-id',
    LastModified: '-last_modified',
    Mitcoursenumber: '-mitcoursenumber',
    ReadableId: '-readable_id',
    StartDate: '-start_date',
    Views: '-views',
    Id2: 'id',
    LastModified2: 'last_modified',
    Mitcoursenumber2: 'mitcoursenumber',
    New: 'new',
    ReadableId2: 'readable_id',
    StartDate2: 'start_date',
    Upcoming: 'upcoming',
    Views2: 'views'
} as const;
export type LearningResourcesSummaryListSortbyEnum = typeof LearningResourcesSummaryListSortbyEnum[keyof typeof LearningResourcesSummaryListSortbyEnum];
/**
 * @export
 */
export const LearningResourcesVectorSimilarListCertificationTypeEnum = {
    Completion: 'completion',
    Micromasters: 'micromasters',
    None: 'none',
    Professional: 'professional'
} as const;
export type LearningResourcesVectorSimilarListCertificationTypeEnum = typeof LearningResourcesVectorSimilarListCertificationTypeEnum[keyof typeof LearningResourcesVectorSimilarListCertificationTypeEnum];
/**
 * @export
 */
export const LearningResourcesVectorSimilarListDeliveryEnum = {
    Online: 'online',
    Hybrid: 'hybrid',
    InPerson: 'in_person',
    Offline: 'offline'
} as const;
export type LearningResourcesVectorSimilarListDeliveryEnum = typeof LearningResourcesVectorSimilarListDeliveryEnum[keyof typeof LearningResourcesVectorSimilarListDeliveryEnum];
/**
 * @export
 */
export const LearningResourcesVectorSimilarListDepartmentEnum = {
    _1: '1',
    _10: '10',
    _11: '11',
    _12: '12',
    _14: '14',
    _15: '15',
    _16: '16',
    _17: '17',
    _18: '18',
    _2: '2',
    _20: '20',
    _21A: '21A',
    _21G: '21G',
    _21H: '21H',
    _21L: '21L',
    _21M: '21M',
    _22: '22',
    _24: '24',
    _3: '3',
    _4: '4',
    _5: '5',
    _6: '6',
    _7: '7',
    _8: '8',
    _9: '9',
    Cc: 'CC',
    CmsW: 'CMS-W',
    Ec: 'EC',
    Es: 'ES',
    Esd: 'ESD',
    Hst: 'HST',
    Ids: 'IDS',
    Mas: 'MAS',
    Pe: 'PE',
    Sp: 'SP',
    Sts: 'STS',
    Wgs: 'WGS'
} as const;
export type LearningResourcesVectorSimilarListDepartmentEnum = typeof LearningResourcesVectorSimilarListDepartmentEnum[keyof typeof LearningResourcesVectorSimilarListDepartmentEnum];
/**
 * @export
 */
export const LearningResourcesVectorSimilarListLevelEnum = {
    Advanced: 'advanced',
    Graduate: 'graduate',
    HighSchool: 'high_school',
    Intermediate: 'intermediate',
    Introductory: 'introductory',
    Noncredit: 'noncredit',
    Undergraduate: 'undergraduate'
} as const;
export type LearningResourcesVectorSimilarListLevelEnum = typeof LearningResourcesVectorSimilarListLevelEnum[keyof typeof LearningResourcesVectorSimilarListLevelEnum];
/**
 * @export
 */
export const LearningResourcesVectorSimilarListOfferedByEnum = {
    Bootcamps: 'bootcamps',
    Mitpe: 'mitpe',
    Mitx: 'mitx',
    Ocw: 'ocw',
    See: 'see',
    Xpro: 'xpro'
} as const;
export type LearningResourcesVectorSimilarListOfferedByEnum = typeof LearningResourcesVectorSimilarListOfferedByEnum[keyof typeof LearningResourcesVectorSimilarListOfferedByEnum];
/**
 * @export
 */
export const LearningResourcesVectorSimilarListPlatformEnum = {
    Bootcamps: 'bootcamps',
    Canvas: 'canvas',
    Csail: 'csail',
    Ctl: 'ctl',
    Edx: 'edx',
    Emeritus: 'emeritus',
    Globalalumni: 'globalalumni',
    Mitpe: 'mitpe',
    Mitxonline: 'mitxonline',
    Ocw: 'ocw',
    Oll: 'oll',
    Podcast: 'podcast',
    Scc: 'scc',
    See: 'see',
    Simplilearn: 'simplilearn',
    Susskind: 'susskind',
    Whu: 'whu',
    Xpro: 'xpro',
    Youtube: 'youtube'
} as const;
export type LearningResourcesVectorSimilarListPlatformEnum = typeof LearningResourcesVectorSimilarListPlatformEnum[keyof typeof LearningResourcesVectorSimilarListPlatformEnum];
/**
 * @export
 */
export const LearningResourcesVectorSimilarListResourceCategoryEnum = {
    Course: 'course',
    LearningMaterial: 'learning_material',
    Program: 'program'
} as const;
export type LearningResourcesVectorSimilarListResourceCategoryEnum = typeof LearningResourcesVectorSimilarListResourceCategoryEnum[keyof typeof LearningResourcesVectorSimilarListResourceCategoryEnum];
/**
 * @export
 */
export const LearningResourcesVectorSimilarListResourceTypeEnum = {
    Course: 'course',
    LearningPath: 'learning_path',
    Podcast: 'podcast',
    PodcastEpisode: 'podcast_episode',
    Program: 'program',
    Video: 'video',
    VideoPlaylist: 'video_playlist'
} as const;
export type LearningResourcesVectorSimilarListResourceTypeEnum = typeof LearningResourcesVectorSimilarListResourceTypeEnum[keyof typeof LearningResourcesVectorSimilarListResourceTypeEnum];
/**
 * @export
 */
export const LearningResourcesVectorSimilarListSortbyEnum = {
    Id: '-id',
    LastModified: '-last_modified',
    Mitcoursenumber: '-mitcoursenumber',
    ReadableId: '-readable_id',
    StartDate: '-start_date',
    Views: '-views',
    Id2: 'id',
    LastModified2: 'last_modified',
    Mitcoursenumber2: 'mitcoursenumber',
    New: 'new',
    ReadableId2: 'readable_id',
    StartDate2: 'start_date',
    Upcoming: 'upcoming',
    Views2: 'views'
} as const;
export type LearningResourcesVectorSimilarListSortbyEnum = typeof LearningResourcesVectorSimilarListSortbyEnum[keyof typeof LearningResourcesVectorSimilarListSortbyEnum];
