/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime"
import type {
  LearningPathRelationship,
  LearningPathRelationshipRequest,
  LearningPathResource,
  LearningPathResourceRequest,
  MicroLearningPathRelationship,
  PaginatedLearningPathRelationshipList,
  PaginatedLearningPathResourceList,
  PatchedLearningPathRelationshipRequest,
  PatchedLearningPathResourceRequest,
} from "../models/index"
import {
  LearningPathRelationshipFromJSON,
  LearningPathRelationshipToJSON,
  LearningPathRelationshipRequestFromJSON,
  LearningPathRelationshipRequestToJSON,
  LearningPathResourceFromJSON,
  LearningPathResourceToJSON,
  LearningPathResourceRequestFromJSON,
  LearningPathResourceRequestToJSON,
  MicroLearningPathRelationshipFromJSON,
  MicroLearningPathRelationshipToJSON,
  PaginatedLearningPathRelationshipListFromJSON,
  PaginatedLearningPathRelationshipListToJSON,
  PaginatedLearningPathResourceListFromJSON,
  PaginatedLearningPathResourceListToJSON,
  PatchedLearningPathRelationshipRequestFromJSON,
  PatchedLearningPathRelationshipRequestToJSON,
  PatchedLearningPathResourceRequestFromJSON,
  PatchedLearningPathResourceRequestToJSON,
} from "../models/index"

export interface LearningpathsCreateRequest {
  LearningPathResourceRequest: LearningPathResourceRequest
}

export interface LearningpathsDestroyRequest {
  id: number
}

export interface LearningpathsItemsCreateRequest {
  learning_resource_id: number
  LearningPathRelationshipRequest: LearningPathRelationshipRequest
}

export interface LearningpathsItemsDestroyRequest {
  id: number
  learning_resource_id: number
}

export interface LearningpathsItemsListRequest {
  learning_resource_id: number
  limit?: number
  offset?: number
  sortby?: string
}

export interface LearningpathsItemsPartialUpdateRequest {
  id: number
  learning_resource_id: number
  PatchedLearningPathRelationshipRequest?: PatchedLearningPathRelationshipRequest
}

export interface LearningpathsItemsRetrieveRequest {
  id: number
  learning_resource_id: number
}

export interface LearningpathsListRequest {
  certification?: boolean
  certification_type?: Array<LearningpathsListCertificationTypeEnum>
  course_feature?: Array<string>
  delivery?: Array<Array<LearningpathsListDeliveryEnum>>
  department?: Array<LearningpathsListDepartmentEnum>
  free?: boolean
  level?: Array<LearningpathsListLevelEnum>
  limit?: number
  offered_by?: Array<LearningpathsListOfferedByEnum>
  offset?: number
  platform?: Array<LearningpathsListPlatformEnum>
  professional?: boolean
  readable_id?: Array<string>
  resource_category?: Array<LearningpathsListResourceCategoryEnum>
  resource_type?: Array<LearningpathsListResourceTypeEnum>
  sortby?: LearningpathsListSortbyEnum
  topic?: Array<string>
}

export interface LearningpathsPartialUpdateRequest {
  id: number
  PatchedLearningPathResourceRequest?: PatchedLearningPathResourceRequest
}

export interface LearningpathsRetrieveRequest {
  id: number
}

/**
 *
 */
export class LearningpathsApi extends runtime.BaseAPI {
  /**
   * Create a learning path
   * Create
   */
  async learningpathsCreateRaw(
    requestParameters: LearningpathsCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LearningPathResource>> {
    if (
      requestParameters.LearningPathResourceRequest === null ||
      requestParameters.LearningPathResourceRequest === undefined
    ) {
      throw new runtime.RequiredError(
        "LearningPathResourceRequest",
        "Required parameter requestParameters.LearningPathResourceRequest was null or undefined when calling learningpathsCreate.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters["Content-Type"] = "application/json"

    const response = await this.request(
      {
        path: `/api/v1/learningpaths/`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: LearningPathResourceRequestToJSON(
          requestParameters.LearningPathResourceRequest,
        ),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LearningPathResourceFromJSON(jsonValue),
    )
  }

  /**
   * Create a learning path
   * Create
   */
  async learningpathsCreate(
    requestParameters: LearningpathsCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LearningPathResource> {
    const response = await this.learningpathsCreateRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * Remove a learning path
   * Destroy
   */
  async learningpathsDestroyRaw(
    requestParameters: LearningpathsDestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling learningpathsDestroy.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/learningpaths/{id}/`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id)),
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Remove a learning path
   * Destroy
   */
  async learningpathsDestroy(
    requestParameters: LearningpathsDestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.learningpathsDestroyRaw(requestParameters, initOverrides)
  }

  /**
   * Viewset for LearningPath related resources
   * Learning Path Resource Relationship Add
   */
  async learningpathsItemsCreateRaw(
    requestParameters: LearningpathsItemsCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LearningPathRelationship>> {
    if (
      requestParameters.learning_resource_id === null ||
      requestParameters.learning_resource_id === undefined
    ) {
      throw new runtime.RequiredError(
        "learning_resource_id",
        "Required parameter requestParameters.learning_resource_id was null or undefined when calling learningpathsItemsCreate.",
      )
    }

    if (
      requestParameters.LearningPathRelationshipRequest === null ||
      requestParameters.LearningPathRelationshipRequest === undefined
    ) {
      throw new runtime.RequiredError(
        "LearningPathRelationshipRequest",
        "Required parameter requestParameters.LearningPathRelationshipRequest was null or undefined when calling learningpathsItemsCreate.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters["Content-Type"] = "application/json"

    const response = await this.request(
      {
        path: `/api/v1/learningpaths/{learning_resource_id}/items/`.replace(
          `{${"learning_resource_id"}}`,
          encodeURIComponent(String(requestParameters.learning_resource_id)),
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: LearningPathRelationshipRequestToJSON(
          requestParameters.LearningPathRelationshipRequest,
        ),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LearningPathRelationshipFromJSON(jsonValue),
    )
  }

  /**
   * Viewset for LearningPath related resources
   * Learning Path Resource Relationship Add
   */
  async learningpathsItemsCreate(
    requestParameters: LearningpathsItemsCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LearningPathRelationship> {
    const response = await this.learningpathsItemsCreateRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * Viewset for LearningPath related resources
   * Learning Path Resource Relationship Remove
   */
  async learningpathsItemsDestroyRaw(
    requestParameters: LearningpathsItemsDestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling learningpathsItemsDestroy.",
      )
    }

    if (
      requestParameters.learning_resource_id === null ||
      requestParameters.learning_resource_id === undefined
    ) {
      throw new runtime.RequiredError(
        "learning_resource_id",
        "Required parameter requestParameters.learning_resource_id was null or undefined when calling learningpathsItemsDestroy.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/learningpaths/{learning_resource_id}/items/{id}/`
          .replace(
            `{${"id"}}`,
            encodeURIComponent(String(requestParameters.id)),
          )
          .replace(
            `{${"learning_resource_id"}}`,
            encodeURIComponent(String(requestParameters.learning_resource_id)),
          ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Viewset for LearningPath related resources
   * Learning Path Resource Relationship Remove
   */
  async learningpathsItemsDestroy(
    requestParameters: LearningpathsItemsDestroyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.learningpathsItemsDestroyRaw(requestParameters, initOverrides)
  }

  /**
   * Viewset for LearningPath related resources
   */
  async learningpathsItemsListRaw(
    requestParameters: LearningpathsItemsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PaginatedLearningPathRelationshipList>> {
    if (
      requestParameters.learning_resource_id === null ||
      requestParameters.learning_resource_id === undefined
    ) {
      throw new runtime.RequiredError(
        "learning_resource_id",
        "Required parameter requestParameters.learning_resource_id was null or undefined when calling learningpathsItemsList.",
      )
    }

    const queryParameters: any = {}

    if (requestParameters.limit !== undefined) {
      queryParameters["limit"] = requestParameters.limit
    }

    if (requestParameters.offset !== undefined) {
      queryParameters["offset"] = requestParameters.offset
    }

    if (requestParameters.sortby !== undefined) {
      queryParameters["sortby"] = requestParameters.sortby
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/learningpaths/{learning_resource_id}/items/`.replace(
          `{${"learning_resource_id"}}`,
          encodeURIComponent(String(requestParameters.learning_resource_id)),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PaginatedLearningPathRelationshipListFromJSON(jsonValue),
    )
  }

  /**
   * Viewset for LearningPath related resources
   */
  async learningpathsItemsList(
    requestParameters: LearningpathsItemsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PaginatedLearningPathRelationshipList> {
    const response = await this.learningpathsItemsListRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * Viewset for LearningPath related resources
   * Learning Path Resource Relationship Update
   */
  async learningpathsItemsPartialUpdateRaw(
    requestParameters: LearningpathsItemsPartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LearningPathRelationship>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling learningpathsItemsPartialUpdate.",
      )
    }

    if (
      requestParameters.learning_resource_id === null ||
      requestParameters.learning_resource_id === undefined
    ) {
      throw new runtime.RequiredError(
        "learning_resource_id",
        "Required parameter requestParameters.learning_resource_id was null or undefined when calling learningpathsItemsPartialUpdate.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters["Content-Type"] = "application/json"

    const response = await this.request(
      {
        path: `/api/v1/learningpaths/{learning_resource_id}/items/{id}/`
          .replace(
            `{${"id"}}`,
            encodeURIComponent(String(requestParameters.id)),
          )
          .replace(
            `{${"learning_resource_id"}}`,
            encodeURIComponent(String(requestParameters.learning_resource_id)),
          ),
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: PatchedLearningPathRelationshipRequestToJSON(
          requestParameters.PatchedLearningPathRelationshipRequest,
        ),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LearningPathRelationshipFromJSON(jsonValue),
    )
  }

  /**
   * Viewset for LearningPath related resources
   * Learning Path Resource Relationship Update
   */
  async learningpathsItemsPartialUpdate(
    requestParameters: LearningpathsItemsPartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LearningPathRelationship> {
    const response = await this.learningpathsItemsPartialUpdateRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * Get a singe related learning resource for a learning resource.
   * Nested Learning Resource Retrieve
   */
  async learningpathsItemsRetrieveRaw(
    requestParameters: LearningpathsItemsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LearningPathRelationship>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling learningpathsItemsRetrieve.",
      )
    }

    if (
      requestParameters.learning_resource_id === null ||
      requestParameters.learning_resource_id === undefined
    ) {
      throw new runtime.RequiredError(
        "learning_resource_id",
        "Required parameter requestParameters.learning_resource_id was null or undefined when calling learningpathsItemsRetrieve.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/learningpaths/{learning_resource_id}/items/{id}/`
          .replace(
            `{${"id"}}`,
            encodeURIComponent(String(requestParameters.id)),
          )
          .replace(
            `{${"learning_resource_id"}}`,
            encodeURIComponent(String(requestParameters.learning_resource_id)),
          ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LearningPathRelationshipFromJSON(jsonValue),
    )
  }

  /**
   * Get a singe related learning resource for a learning resource.
   * Nested Learning Resource Retrieve
   */
  async learningpathsItemsRetrieve(
    requestParameters: LearningpathsItemsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LearningPathRelationship> {
    const response = await this.learningpathsItemsRetrieveRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * Get a paginated list of learning paths
   * List
   */
  async learningpathsListRaw(
    requestParameters: LearningpathsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PaginatedLearningPathResourceList>> {
    const queryParameters: any = {}

    if (requestParameters.certification !== undefined) {
      queryParameters["certification"] = requestParameters.certification
    }

    if (requestParameters.certification_type) {
      queryParameters["certification_type"] =
        requestParameters.certification_type
    }

    if (requestParameters.course_feature) {
      queryParameters["course_feature"] = requestParameters.course_feature.join(
        runtime.COLLECTION_FORMATS["csv"],
      )
    }

    if (requestParameters.delivery) {
      queryParameters["delivery"] = requestParameters.delivery
    }

    if (requestParameters.department) {
      queryParameters["department"] = requestParameters.department
    }

    if (requestParameters.free !== undefined) {
      queryParameters["free"] = requestParameters.free
    }

    if (requestParameters.level) {
      queryParameters["level"] = requestParameters.level
    }

    if (requestParameters.limit !== undefined) {
      queryParameters["limit"] = requestParameters.limit
    }

    if (requestParameters.offered_by) {
      queryParameters["offered_by"] = requestParameters.offered_by
    }

    if (requestParameters.offset !== undefined) {
      queryParameters["offset"] = requestParameters.offset
    }

    if (requestParameters.platform) {
      queryParameters["platform"] = requestParameters.platform
    }

    if (requestParameters.professional !== undefined) {
      queryParameters["professional"] = requestParameters.professional
    }

    if (requestParameters.readable_id) {
      queryParameters["readable_id"] = requestParameters.readable_id.join(
        runtime.COLLECTION_FORMATS["csv"],
      )
    }

    if (requestParameters.resource_category) {
      queryParameters["resource_category"] = requestParameters.resource_category
    }

    if (requestParameters.resource_type) {
      queryParameters["resource_type"] = requestParameters.resource_type
    }

    if (requestParameters.sortby !== undefined) {
      queryParameters["sortby"] = requestParameters.sortby
    }

    if (requestParameters.topic) {
      queryParameters["topic"] = requestParameters.topic.join(
        runtime.COLLECTION_FORMATS["csv"],
      )
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/learningpaths/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PaginatedLearningPathResourceListFromJSON(jsonValue),
    )
  }

  /**
   * Get a paginated list of learning paths
   * List
   */
  async learningpathsList(
    requestParameters: LearningpathsListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PaginatedLearningPathResourceList> {
    const response = await this.learningpathsListRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * Get a list of all learning path items
   * List
   */
  async learningpathsMembershipListRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<MicroLearningPathRelationship>>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/learningpaths/membership/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(MicroLearningPathRelationshipFromJSON),
    )
  }

  /**
   * Get a list of all learning path items
   * List
   */
  async learningpathsMembershipList(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<MicroLearningPathRelationship>> {
    const response = await this.learningpathsMembershipListRaw(initOverrides)
    return await response.value()
  }

  /**
   * Update individual fields of a learning path
   * Update
   */
  async learningpathsPartialUpdateRaw(
    requestParameters: LearningpathsPartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LearningPathResource>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling learningpathsPartialUpdate.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters["Content-Type"] = "application/json"

    const response = await this.request(
      {
        path: `/api/v1/learningpaths/{id}/`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id)),
        ),
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: PatchedLearningPathResourceRequestToJSON(
          requestParameters.PatchedLearningPathResourceRequest,
        ),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LearningPathResourceFromJSON(jsonValue),
    )
  }

  /**
   * Update individual fields of a learning path
   * Update
   */
  async learningpathsPartialUpdate(
    requestParameters: LearningpathsPartialUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LearningPathResource> {
    const response = await this.learningpathsPartialUpdateRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * Retrive a single learning path
   * Retrieve
   */
  async learningpathsRetrieveRaw(
    requestParameters: LearningpathsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LearningPathResource>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling learningpathsRetrieve.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/learningpaths/{id}/`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id)),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LearningPathResourceFromJSON(jsonValue),
    )
  }

  /**
   * Retrive a single learning path
   * Retrieve
   */
  async learningpathsRetrieve(
    requestParameters: LearningpathsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LearningPathResource> {
    const response = await this.learningpathsRetrieveRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }
}

/**
 * @export
 */
export const LearningpathsListCertificationTypeEnum = {
  Completion: "completion",
  Micromasters: "micromasters",
  None: "none",
  Professional: "professional",
} as const
export type LearningpathsListCertificationTypeEnum =
  (typeof LearningpathsListCertificationTypeEnum)[keyof typeof LearningpathsListCertificationTypeEnum]
/**
 * @export
 */
export const LearningpathsListDeliveryEnum = {
  Online: "online",
  Hybrid: "hybrid",
  InPerson: "in_person",
  Offline: "offline",
} as const
export type LearningpathsListDeliveryEnum =
  (typeof LearningpathsListDeliveryEnum)[keyof typeof LearningpathsListDeliveryEnum]
/**
 * @export
 */
export const LearningpathsListDepartmentEnum = {
  _1: "1",
  _10: "10",
  _11: "11",
  _12: "12",
  _14: "14",
  _15: "15",
  _16: "16",
  _17: "17",
  _18: "18",
  _2: "2",
  _20: "20",
  _21A: "21A",
  _21G: "21G",
  _21H: "21H",
  _21L: "21L",
  _21M: "21M",
  _22: "22",
  _24: "24",
  _3: "3",
  _4: "4",
  _5: "5",
  _6: "6",
  _7: "7",
  _8: "8",
  _9: "9",
  Cc: "CC",
  CmsW: "CMS-W",
  Ec: "EC",
  Es: "ES",
  Esd: "ESD",
  Hst: "HST",
  Ids: "IDS",
  Mas: "MAS",
  Pe: "PE",
  Sp: "SP",
  Sts: "STS",
  Wgs: "WGS",
} as const
export type LearningpathsListDepartmentEnum =
  (typeof LearningpathsListDepartmentEnum)[keyof typeof LearningpathsListDepartmentEnum]
/**
 * @export
 */
export const LearningpathsListLevelEnum = {
  Advanced: "advanced",
  Graduate: "graduate",
  HighSchool: "high_school",
  Intermediate: "intermediate",
  Introductory: "introductory",
  Noncredit: "noncredit",
  Undergraduate: "undergraduate",
} as const
export type LearningpathsListLevelEnum =
  (typeof LearningpathsListLevelEnum)[keyof typeof LearningpathsListLevelEnum]
/**
 * @export
 */
export const LearningpathsListOfferedByEnum = {
  Bootcamps: "bootcamps",
  Mitpe: "mitpe",
  Mitx: "mitx",
  Ocw: "ocw",
  See: "see",
  Xpro: "xpro",
} as const
export type LearningpathsListOfferedByEnum =
  (typeof LearningpathsListOfferedByEnum)[keyof typeof LearningpathsListOfferedByEnum]
/**
 * @export
 */
export const LearningpathsListPlatformEnum = {
  Bootcamps: "bootcamps",
  Canvas: "canvas",
  Csail: "csail",
  Ctl: "ctl",
  Edx: "edx",
  Emeritus: "emeritus",
  Globalalumni: "globalalumni",
  Mitpe: "mitpe",
  Mitxonline: "mitxonline",
  Ocw: "ocw",
  Oll: "oll",
  Podcast: "podcast",
  Scc: "scc",
  See: "see",
  Simplilearn: "simplilearn",
  Susskind: "susskind",
  Whu: "whu",
  Xpro: "xpro",
  Youtube: "youtube",
} as const
export type LearningpathsListPlatformEnum =
  (typeof LearningpathsListPlatformEnum)[keyof typeof LearningpathsListPlatformEnum]
/**
 * @export
 */
export const LearningpathsListResourceCategoryEnum = {
  Course: "course",
  LearningMaterial: "learning_material",
  Program: "program",
} as const
export type LearningpathsListResourceCategoryEnum =
  (typeof LearningpathsListResourceCategoryEnum)[keyof typeof LearningpathsListResourceCategoryEnum]
/**
 * @export
 */
export const LearningpathsListResourceTypeEnum = {
  Course: "course",
  LearningPath: "learning_path",
  Podcast: "podcast",
  PodcastEpisode: "podcast_episode",
  Program: "program",
  Video: "video",
  VideoPlaylist: "video_playlist",
} as const
export type LearningpathsListResourceTypeEnum =
  (typeof LearningpathsListResourceTypeEnum)[keyof typeof LearningpathsListResourceTypeEnum]
/**
 * @export
 */
export const LearningpathsListSortbyEnum = {
  Id: "-id",
  LastModified: "-last_modified",
  Mitcoursenumber: "-mitcoursenumber",
  ReadableId: "-readable_id",
  StartDate: "-start_date",
  Views: "-views",
  Id2: "id",
  LastModified2: "last_modified",
  Mitcoursenumber2: "mitcoursenumber",
  New: "new",
  ReadableId2: "readable_id",
  StartDate2: "start_date",
  Upcoming: "upcoming",
  Views2: "views",
} as const
export type LearningpathsListSortbyEnum =
  (typeof LearningpathsListSortbyEnum)[keyof typeof LearningpathsListSortbyEnum]
