/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LearningResourceRelationship,
  PaginatedLearningResourceRelationshipList,
  PaginatedPodcastResourceList,
  PodcastResource,
} from '../models/index';
import {
    LearningResourceRelationshipFromJSON,
    LearningResourceRelationshipToJSON,
    PaginatedLearningResourceRelationshipListFromJSON,
    PaginatedLearningResourceRelationshipListToJSON,
    PaginatedPodcastResourceListFromJSON,
    PaginatedPodcastResourceListToJSON,
    PodcastResourceFromJSON,
    PodcastResourceToJSON,
} from '../models/index';

export interface PodcastsItemsListRequest {
    learning_resource_id: number;
    limit?: number;
    offset?: number;
    sortby?: string;
}

export interface PodcastsItemsRetrieveRequest {
    id: number;
    learning_resource_id: number;
}

export interface PodcastsListRequest {
    certification?: boolean;
    certification_type?: Array<PodcastsListCertificationTypeEnum>;
    course_feature?: Array<string>;
    delivery?: Array<Array<PodcastsListDeliveryEnum>>;
    department?: Array<PodcastsListDepartmentEnum>;
    free?: boolean;
    level?: Array<PodcastsListLevelEnum>;
    limit?: number;
    offered_by?: Array<PodcastsListOfferedByEnum>;
    offset?: number;
    platform?: Array<PodcastsListPlatformEnum>;
    professional?: boolean;
    readable_id?: Array<string>;
    resource_category?: Array<PodcastsListResourceCategoryEnum>;
    resource_type?: Array<PodcastsListResourceTypeEnum>;
    sortby?: PodcastsListSortbyEnum;
    topic?: Array<string>;
}

export interface PodcastsRetrieveRequest {
    id: number;
}

/**
 * 
 */
export class PodcastsApi extends runtime.BaseAPI {

    /**
     * Get a list of related learning resources for a learning resource.
     * Nested Learning Resource List
     */
    async podcastsItemsListRaw(requestParameters: PodcastsItemsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedLearningResourceRelationshipList>> {
        if (requestParameters.learning_resource_id === null || requestParameters.learning_resource_id === undefined) {
            throw new runtime.RequiredError('learning_resource_id','Required parameter requestParameters.learning_resource_id was null or undefined when calling podcastsItemsList.');
        }

        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.sortby !== undefined) {
            queryParameters['sortby'] = requestParameters.sortby;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/podcasts/{learning_resource_id}/items/`.replace(`{${"learning_resource_id"}}`, encodeURIComponent(String(requestParameters.learning_resource_id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedLearningResourceRelationshipListFromJSON(jsonValue));
    }

    /**
     * Get a list of related learning resources for a learning resource.
     * Nested Learning Resource List
     */
    async podcastsItemsList(requestParameters: PodcastsItemsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedLearningResourceRelationshipList> {
        const response = await this.podcastsItemsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a singe related learning resource for a learning resource.
     * Nested Learning Resource Retrieve
     */
    async podcastsItemsRetrieveRaw(requestParameters: PodcastsItemsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LearningResourceRelationship>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling podcastsItemsRetrieve.');
        }

        if (requestParameters.learning_resource_id === null || requestParameters.learning_resource_id === undefined) {
            throw new runtime.RequiredError('learning_resource_id','Required parameter requestParameters.learning_resource_id was null or undefined when calling podcastsItemsRetrieve.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/podcasts/{learning_resource_id}/items/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"learning_resource_id"}}`, encodeURIComponent(String(requestParameters.learning_resource_id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LearningResourceRelationshipFromJSON(jsonValue));
    }

    /**
     * Get a singe related learning resource for a learning resource.
     * Nested Learning Resource Retrieve
     */
    async podcastsItemsRetrieve(requestParameters: PodcastsItemsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LearningResourceRelationship> {
        const response = await this.podcastsItemsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a paginated list of podcasts
     * List
     */
    async podcastsListRaw(requestParameters: PodcastsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedPodcastResourceList>> {
        const queryParameters: any = {};

        if (requestParameters.certification !== undefined) {
            queryParameters['certification'] = requestParameters.certification;
        }

        if (requestParameters.certification_type) {
            queryParameters['certification_type'] = requestParameters.certification_type;
        }

        if (requestParameters.course_feature) {
            queryParameters['course_feature'] = requestParameters.course_feature.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.delivery) {
            queryParameters['delivery'] = requestParameters.delivery;
        }

        if (requestParameters.department) {
            queryParameters['department'] = requestParameters.department;
        }

        if (requestParameters.free !== undefined) {
            queryParameters['free'] = requestParameters.free;
        }

        if (requestParameters.level) {
            queryParameters['level'] = requestParameters.level;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offered_by) {
            queryParameters['offered_by'] = requestParameters.offered_by;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.platform) {
            queryParameters['platform'] = requestParameters.platform;
        }

        if (requestParameters.professional !== undefined) {
            queryParameters['professional'] = requestParameters.professional;
        }

        if (requestParameters.readable_id) {
            queryParameters['readable_id'] = requestParameters.readable_id.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.resource_category) {
            queryParameters['resource_category'] = requestParameters.resource_category;
        }

        if (requestParameters.resource_type) {
            queryParameters['resource_type'] = requestParameters.resource_type;
        }

        if (requestParameters.sortby !== undefined) {
            queryParameters['sortby'] = requestParameters.sortby;
        }

        if (requestParameters.topic) {
            queryParameters['topic'] = requestParameters.topic.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/podcasts/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedPodcastResourceListFromJSON(jsonValue));
    }

    /**
     * Get a paginated list of podcasts
     * List
     */
    async podcastsList(requestParameters: PodcastsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedPodcastResourceList> {
        const response = await this.podcastsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a single podcast
     * Retrieve
     */
    async podcastsRetrieveRaw(requestParameters: PodcastsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PodcastResource>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling podcastsRetrieve.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/podcasts/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PodcastResourceFromJSON(jsonValue));
    }

    /**
     * Retrieve a single podcast
     * Retrieve
     */
    async podcastsRetrieve(requestParameters: PodcastsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PodcastResource> {
        const response = await this.podcastsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const PodcastsListCertificationTypeEnum = {
    Completion: 'completion',
    Micromasters: 'micromasters',
    None: 'none',
    Professional: 'professional'
} as const;
export type PodcastsListCertificationTypeEnum = typeof PodcastsListCertificationTypeEnum[keyof typeof PodcastsListCertificationTypeEnum];
/**
 * @export
 */
export const PodcastsListDeliveryEnum = {
    Online: 'online',
    Hybrid: 'hybrid',
    InPerson: 'in_person',
    Offline: 'offline'
} as const;
export type PodcastsListDeliveryEnum = typeof PodcastsListDeliveryEnum[keyof typeof PodcastsListDeliveryEnum];
/**
 * @export
 */
export const PodcastsListDepartmentEnum = {
    _1: '1',
    _10: '10',
    _11: '11',
    _12: '12',
    _14: '14',
    _15: '15',
    _16: '16',
    _17: '17',
    _18: '18',
    _2: '2',
    _20: '20',
    _21A: '21A',
    _21G: '21G',
    _21H: '21H',
    _21L: '21L',
    _21M: '21M',
    _22: '22',
    _24: '24',
    _3: '3',
    _4: '4',
    _5: '5',
    _6: '6',
    _7: '7',
    _8: '8',
    _9: '9',
    Cc: 'CC',
    CmsW: 'CMS-W',
    Ec: 'EC',
    Es: 'ES',
    Esd: 'ESD',
    Hst: 'HST',
    Ids: 'IDS',
    Mas: 'MAS',
    Pe: 'PE',
    Sp: 'SP',
    Sts: 'STS',
    Wgs: 'WGS'
} as const;
export type PodcastsListDepartmentEnum = typeof PodcastsListDepartmentEnum[keyof typeof PodcastsListDepartmentEnum];
/**
 * @export
 */
export const PodcastsListLevelEnum = {
    Advanced: 'advanced',
    Graduate: 'graduate',
    HighSchool: 'high_school',
    Intermediate: 'intermediate',
    Introductory: 'introductory',
    Noncredit: 'noncredit',
    Undergraduate: 'undergraduate'
} as const;
export type PodcastsListLevelEnum = typeof PodcastsListLevelEnum[keyof typeof PodcastsListLevelEnum];
/**
 * @export
 */
export const PodcastsListOfferedByEnum = {
    Bootcamps: 'bootcamps',
    Mitpe: 'mitpe',
    Mitx: 'mitx',
    Ocw: 'ocw',
    See: 'see',
    Xpro: 'xpro'
} as const;
export type PodcastsListOfferedByEnum = typeof PodcastsListOfferedByEnum[keyof typeof PodcastsListOfferedByEnum];
/**
 * @export
 */
export const PodcastsListPlatformEnum = {
    Bootcamps: 'bootcamps',
    Canvas: 'canvas',
    Csail: 'csail',
    Ctl: 'ctl',
    Edx: 'edx',
    Emeritus: 'emeritus',
    Globalalumni: 'globalalumni',
    Mitpe: 'mitpe',
    Mitxonline: 'mitxonline',
    Ocw: 'ocw',
    Oll: 'oll',
    Podcast: 'podcast',
    Scc: 'scc',
    See: 'see',
    Simplilearn: 'simplilearn',
    Susskind: 'susskind',
    Whu: 'whu',
    Xpro: 'xpro',
    Youtube: 'youtube'
} as const;
export type PodcastsListPlatformEnum = typeof PodcastsListPlatformEnum[keyof typeof PodcastsListPlatformEnum];
/**
 * @export
 */
export const PodcastsListResourceCategoryEnum = {
    Course: 'course',
    LearningMaterial: 'learning_material',
    Program: 'program'
} as const;
export type PodcastsListResourceCategoryEnum = typeof PodcastsListResourceCategoryEnum[keyof typeof PodcastsListResourceCategoryEnum];
/**
 * @export
 */
export const PodcastsListResourceTypeEnum = {
    Course: 'course',
    LearningPath: 'learning_path',
    Podcast: 'podcast',
    PodcastEpisode: 'podcast_episode',
    Program: 'program',
    Video: 'video',
    VideoPlaylist: 'video_playlist'
} as const;
export type PodcastsListResourceTypeEnum = typeof PodcastsListResourceTypeEnum[keyof typeof PodcastsListResourceTypeEnum];
/**
 * @export
 */
export const PodcastsListSortbyEnum = {
    Id: '-id',
    LastModified: '-last_modified',
    Mitcoursenumber: '-mitcoursenumber',
    ReadableId: '-readable_id',
    StartDate: '-start_date',
    Views: '-views',
    Id2: 'id',
    LastModified2: 'last_modified',
    Mitcoursenumber2: 'mitcoursenumber',
    New: 'new',
    ReadableId2: 'readable_id',
    StartDate2: 'start_date',
    Upcoming: 'upcoming',
    Views2: 'views'
} as const;
export type PodcastsListSortbyEnum = typeof PodcastsListSortbyEnum[keyof typeof PodcastsListSortbyEnum];
