/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime"
import type {
  PaginatedProgramResourceList,
  ProgramResource,
} from "../models/index"
import {
  PaginatedProgramResourceListFromJSON,
  PaginatedProgramResourceListToJSON,
  ProgramResourceFromJSON,
  ProgramResourceToJSON,
} from "../models/index"

export interface ProgramsListRequest {
  certification?: boolean
  certification_type?: Array<ProgramsListCertificationTypeEnum>
  course_feature?: Array<string>
  delivery?: Array<Array<ProgramsListDeliveryEnum>>
  department?: Array<ProgramsListDepartmentEnum>
  free?: boolean
  level?: Array<ProgramsListLevelEnum>
  limit?: number
  offered_by?: Array<ProgramsListOfferedByEnum>
  offset?: number
  platform?: Array<ProgramsListPlatformEnum>
  professional?: boolean
  readable_id?: Array<string>
  resource_category?: Array<ProgramsListResourceCategoryEnum>
  resource_type?: Array<ProgramsListResourceTypeEnum>
  sortby?: ProgramsListSortbyEnum
  topic?: Array<string>
}

export interface ProgramsRetrieveRequest {
  id: number
}

/**
 *
 */
export class ProgramsApi extends runtime.BaseAPI {
  /**
   * Get a paginated list of programs
   * List
   */
  async programsListRaw(
    requestParameters: ProgramsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PaginatedProgramResourceList>> {
    const queryParameters: any = {}

    if (requestParameters.certification !== undefined) {
      queryParameters["certification"] = requestParameters.certification
    }

    if (requestParameters.certification_type) {
      queryParameters["certification_type"] =
        requestParameters.certification_type
    }

    if (requestParameters.course_feature) {
      queryParameters["course_feature"] = requestParameters.course_feature.join(
        runtime.COLLECTION_FORMATS["csv"],
      )
    }

    if (requestParameters.delivery) {
      queryParameters["delivery"] = requestParameters.delivery
    }

    if (requestParameters.department) {
      queryParameters["department"] = requestParameters.department
    }

    if (requestParameters.free !== undefined) {
      queryParameters["free"] = requestParameters.free
    }

    if (requestParameters.level) {
      queryParameters["level"] = requestParameters.level
    }

    if (requestParameters.limit !== undefined) {
      queryParameters["limit"] = requestParameters.limit
    }

    if (requestParameters.offered_by) {
      queryParameters["offered_by"] = requestParameters.offered_by
    }

    if (requestParameters.offset !== undefined) {
      queryParameters["offset"] = requestParameters.offset
    }

    if (requestParameters.platform) {
      queryParameters["platform"] = requestParameters.platform
    }

    if (requestParameters.professional !== undefined) {
      queryParameters["professional"] = requestParameters.professional
    }

    if (requestParameters.readable_id) {
      queryParameters["readable_id"] = requestParameters.readable_id.join(
        runtime.COLLECTION_FORMATS["csv"],
      )
    }

    if (requestParameters.resource_category) {
      queryParameters["resource_category"] = requestParameters.resource_category
    }

    if (requestParameters.resource_type) {
      queryParameters["resource_type"] = requestParameters.resource_type
    }

    if (requestParameters.sortby !== undefined) {
      queryParameters["sortby"] = requestParameters.sortby
    }

    if (requestParameters.topic) {
      queryParameters["topic"] = requestParameters.topic.join(
        runtime.COLLECTION_FORMATS["csv"],
      )
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/programs/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PaginatedProgramResourceListFromJSON(jsonValue),
    )
  }

  /**
   * Get a paginated list of programs
   * List
   */
  async programsList(
    requestParameters: ProgramsListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PaginatedProgramResourceList> {
    const response = await this.programsListRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }

  /**
   * Retrieve a single program
   * Retrieve
   */
  async programsRetrieveRaw(
    requestParameters: ProgramsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProgramResource>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling programsRetrieve.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/programs/{id}/`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id)),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProgramResourceFromJSON(jsonValue),
    )
  }

  /**
   * Retrieve a single program
   * Retrieve
   */
  async programsRetrieve(
    requestParameters: ProgramsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ProgramResource> {
    const response = await this.programsRetrieveRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }
}

/**
 * @export
 */
export const ProgramsListCertificationTypeEnum = {
  Completion: "completion",
  Micromasters: "micromasters",
  None: "none",
  Professional: "professional",
} as const
export type ProgramsListCertificationTypeEnum =
  (typeof ProgramsListCertificationTypeEnum)[keyof typeof ProgramsListCertificationTypeEnum]
/**
 * @export
 */
export const ProgramsListDeliveryEnum = {
  Online: "online",
  Hybrid: "hybrid",
  InPerson: "in_person",
  Offline: "offline",
} as const
export type ProgramsListDeliveryEnum =
  (typeof ProgramsListDeliveryEnum)[keyof typeof ProgramsListDeliveryEnum]
/**
 * @export
 */
export const ProgramsListDepartmentEnum = {
  _1: "1",
  _10: "10",
  _11: "11",
  _12: "12",
  _14: "14",
  _15: "15",
  _16: "16",
  _17: "17",
  _18: "18",
  _2: "2",
  _20: "20",
  _21A: "21A",
  _21G: "21G",
  _21H: "21H",
  _21L: "21L",
  _21M: "21M",
  _22: "22",
  _24: "24",
  _3: "3",
  _4: "4",
  _5: "5",
  _6: "6",
  _7: "7",
  _8: "8",
  _9: "9",
  Cc: "CC",
  CmsW: "CMS-W",
  Ec: "EC",
  Es: "ES",
  Esd: "ESD",
  Hst: "HST",
  Ids: "IDS",
  Mas: "MAS",
  Pe: "PE",
  Sp: "SP",
  Sts: "STS",
  Wgs: "WGS",
} as const
export type ProgramsListDepartmentEnum =
  (typeof ProgramsListDepartmentEnum)[keyof typeof ProgramsListDepartmentEnum]
/**
 * @export
 */
export const ProgramsListLevelEnum = {
  Advanced: "advanced",
  Graduate: "graduate",
  HighSchool: "high_school",
  Intermediate: "intermediate",
  Introductory: "introductory",
  Noncredit: "noncredit",
  Undergraduate: "undergraduate",
} as const
export type ProgramsListLevelEnum =
  (typeof ProgramsListLevelEnum)[keyof typeof ProgramsListLevelEnum]
/**
 * @export
 */
export const ProgramsListOfferedByEnum = {
  Bootcamps: "bootcamps",
  Mitpe: "mitpe",
  Mitx: "mitx",
  Ocw: "ocw",
  See: "see",
  Xpro: "xpro",
} as const
export type ProgramsListOfferedByEnum =
  (typeof ProgramsListOfferedByEnum)[keyof typeof ProgramsListOfferedByEnum]
/**
 * @export
 */
export const ProgramsListPlatformEnum = {
  Bootcamps: "bootcamps",
  Canvas: "canvas",
  Csail: "csail",
  Ctl: "ctl",
  Edx: "edx",
  Emeritus: "emeritus",
  Globalalumni: "globalalumni",
  Mitpe: "mitpe",
  Mitxonline: "mitxonline",
  Ocw: "ocw",
  Oll: "oll",
  Podcast: "podcast",
  Scc: "scc",
  See: "see",
  Simplilearn: "simplilearn",
  Susskind: "susskind",
  Whu: "whu",
  Xpro: "xpro",
  Youtube: "youtube",
} as const
export type ProgramsListPlatformEnum =
  (typeof ProgramsListPlatformEnum)[keyof typeof ProgramsListPlatformEnum]
/**
 * @export
 */
export const ProgramsListResourceCategoryEnum = {
  Course: "course",
  LearningMaterial: "learning_material",
  Program: "program",
} as const
export type ProgramsListResourceCategoryEnum =
  (typeof ProgramsListResourceCategoryEnum)[keyof typeof ProgramsListResourceCategoryEnum]
/**
 * @export
 */
export const ProgramsListResourceTypeEnum = {
  Course: "course",
  LearningPath: "learning_path",
  Podcast: "podcast",
  PodcastEpisode: "podcast_episode",
  Program: "program",
  Video: "video",
  VideoPlaylist: "video_playlist",
} as const
export type ProgramsListResourceTypeEnum =
  (typeof ProgramsListResourceTypeEnum)[keyof typeof ProgramsListResourceTypeEnum]
/**
 * @export
 */
export const ProgramsListSortbyEnum = {
  Id: "-id",
  LastModified: "-last_modified",
  Mitcoursenumber: "-mitcoursenumber",
  ReadableId: "-readable_id",
  StartDate: "-start_date",
  Views: "-views",
  Id2: "id",
  LastModified2: "last_modified",
  Mitcoursenumber2: "mitcoursenumber",
  New: "new",
  ReadableId2: "readable_id",
  StartDate2: "start_date",
  Upcoming: "upcoming",
  Views2: "views",
} as const
export type ProgramsListSortbyEnum =
  (typeof ProgramsListSortbyEnum)[keyof typeof ProgramsListSortbyEnum]
