/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime"
import type {
  LearningResourceSchool,
  PaginatedLearningResourceSchoolList,
} from "../models/index"
import {
  LearningResourceSchoolFromJSON,
  LearningResourceSchoolToJSON,
  PaginatedLearningResourceSchoolListFromJSON,
  PaginatedLearningResourceSchoolListToJSON,
} from "../models/index"

export interface SchoolsListRequest {
  limit?: number
  offset?: number
}

export interface SchoolsRetrieveRequest {
  id: number
}

/**
 *
 */
export class SchoolsApi extends runtime.BaseAPI {
  /**
   * MIT schools
   * List
   */
  async schoolsListRaw(
    requestParameters: SchoolsListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PaginatedLearningResourceSchoolList>> {
    const queryParameters: any = {}

    if (requestParameters.limit !== undefined) {
      queryParameters["limit"] = requestParameters.limit
    }

    if (requestParameters.offset !== undefined) {
      queryParameters["offset"] = requestParameters.offset
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/schools/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PaginatedLearningResourceSchoolListFromJSON(jsonValue),
    )
  }

  /**
   * MIT schools
   * List
   */
  async schoolsList(
    requestParameters: SchoolsListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PaginatedLearningResourceSchoolList> {
    const response = await this.schoolsListRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * MIT schools
   * Retrieve
   */
  async schoolsRetrieveRaw(
    requestParameters: SchoolsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LearningResourceSchool>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling schoolsRetrieve.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v1/schools/{id}/`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id)),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LearningResourceSchoolFromJSON(jsonValue),
    )
  }

  /**
   * MIT schools
   * Retrieve
   */
  async schoolsRetrieve(
    requestParameters: SchoolsRetrieveRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LearningResourceSchool> {
    const response = await this.schoolsRetrieveRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }
}
