/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ContentFileWebHookRequest,
  ContentFileWebHookRequestRequest,
  WebhookResponse,
} from '../models/index';
import {
    ContentFileWebHookRequestFromJSON,
    ContentFileWebHookRequestToJSON,
    ContentFileWebHookRequestRequestFromJSON,
    ContentFileWebHookRequestRequestToJSON,
    WebhookResponseFromJSON,
    WebhookResponseToJSON,
} from '../models/index';

export interface WebhooksContentFilesCreateRequest {
    source: WebhooksContentFilesCreateSourceEnum;
    ContentFileWebHookRequestRequest: ContentFileWebHookRequestRequest;
    content_path?: string;
    course_id?: string;
}

export interface WebhooksContentFilesDeleteCreateRequest {
    ContentFileWebHookRequestRequest: ContentFileWebHookRequestRequest;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Webhook handler for ContentFile updates
     */
    async webhooksContentFilesCreateRaw(requestParameters: WebhooksContentFilesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookResponse>> {
        if (requestParameters.source === null || requestParameters.source === undefined) {
            throw new runtime.RequiredError('source','Required parameter requestParameters.source was null or undefined when calling webhooksContentFilesCreate.');
        }

        if (requestParameters.ContentFileWebHookRequestRequest === null || requestParameters.ContentFileWebHookRequestRequest === undefined) {
            throw new runtime.RequiredError('ContentFileWebHookRequestRequest','Required parameter requestParameters.ContentFileWebHookRequestRequest was null or undefined when calling webhooksContentFilesCreate.');
        }

        const queryParameters: any = {};

        if (requestParameters.content_path !== undefined) {
            queryParameters['content_path'] = requestParameters.content_path;
        }

        if (requestParameters.course_id !== undefined) {
            queryParameters['course_id'] = requestParameters.course_id;
        }

        if (requestParameters.source !== undefined) {
            queryParameters['source'] = requestParameters.source;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/webhooks/content_files/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ContentFileWebHookRequestRequestToJSON(requestParameters.ContentFileWebHookRequestRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookResponseFromJSON(jsonValue));
    }

    /**
     * Webhook handler for ContentFile updates
     */
    async webhooksContentFilesCreate(requestParameters: WebhooksContentFilesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookResponse> {
        const response = await this.webhooksContentFilesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Webhook handler for ContentFile DELETE requests
     */
    async webhooksContentFilesDeleteCreateRaw(requestParameters: WebhooksContentFilesDeleteCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContentFileWebHookRequest>> {
        if (requestParameters.ContentFileWebHookRequestRequest === null || requestParameters.ContentFileWebHookRequestRequest === undefined) {
            throw new runtime.RequiredError('ContentFileWebHookRequestRequest','Required parameter requestParameters.ContentFileWebHookRequestRequest was null or undefined when calling webhooksContentFilesDeleteCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/webhooks/content_files/delete/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ContentFileWebHookRequestRequestToJSON(requestParameters.ContentFileWebHookRequestRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContentFileWebHookRequestFromJSON(jsonValue));
    }

    /**
     * Webhook handler for ContentFile DELETE requests
     */
    async webhooksContentFilesDeleteCreate(requestParameters: WebhooksContentFilesDeleteCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContentFileWebHookRequest> {
        const response = await this.webhooksContentFilesDeleteCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const WebhooksContentFilesCreateSourceEnum = {
    Micromasters: 'micromasters',
    MitEdx: 'mit_edx',
    Mitpe: 'mitpe',
    Mitxonline: 'mitxonline',
    Oll: 'oll',
    Ocw: 'ocw',
    Podcast: 'podcast',
    See: 'see',
    Xpro: 'xpro',
    Youtube: 'youtube',
    Canvas: 'canvas'
} as const;
export type WebhooksContentFilesCreateSourceEnum = typeof WebhooksContentFilesCreateSourceEnum[keyof typeof WebhooksContentFilesCreateSourceEnum];
