/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `yes` - Yes, I am looking for a certificate
 * * `no` - No, I am not looking for a certificate
 * * `not-sure-yet` - Not Sure
 * @export
 */
export const CertificateDesiredEnum = {
    Yes: 'yes',
    No: 'no',
    NotSureYet: 'not-sure-yet'
} as const;
export type CertificateDesiredEnum = typeof CertificateDesiredEnum[keyof typeof CertificateDesiredEnum];


export function CertificateDesiredEnumFromJSON(json: any): CertificateDesiredEnum {
    return CertificateDesiredEnumFromJSONTyped(json, false);
}

export function CertificateDesiredEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificateDesiredEnum {
    return json as CertificateDesiredEnum;
}

export function CertificateDesiredEnumToJSON(value?: CertificateDesiredEnum | null): any {
    return value as any;
}

