/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 * Serializer for the ChannelDepartmentDetail model
 * @export
 * @interface ChannelDepartmentDetail
 */
export interface ChannelDepartmentDetail {
  /**
   *
   * @type {string}
   * @memberof ChannelDepartmentDetail
   */
  department?: string | null
}

/**
 * Check if a given object implements the ChannelDepartmentDetail interface.
 */
export function instanceOfChannelDepartmentDetail(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChannelDepartmentDetailFromJSON(
  json: any,
): ChannelDepartmentDetail {
  return ChannelDepartmentDetailFromJSONTyped(json, false)
}

export function ChannelDepartmentDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChannelDepartmentDetail {
  if (json === undefined || json === null) {
    return json
  }
  return {
    department: !exists(json, "department") ? undefined : json["department"],
  }
}

export function ChannelDepartmentDetailToJSON(
  value?: ChannelDepartmentDetail | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    department: value.department,
  }
}
