/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for the ChannelTopicDetail model
 * @export
 * @interface ChannelTopicDetailRequest
 */
export interface ChannelTopicDetailRequest {
    /**
     * 
     * @type {number}
     * @memberof ChannelTopicDetailRequest
     */
    topic?: number | null;
}

/**
 * Check if a given object implements the ChannelTopicDetailRequest interface.
 */
export function instanceOfChannelTopicDetailRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChannelTopicDetailRequestFromJSON(json: any): ChannelTopicDetailRequest {
    return ChannelTopicDetailRequestFromJSONTyped(json, false);
}

export function ChannelTopicDetailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelTopicDetailRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topic': !exists(json, 'topic') ? undefined : json['topic'],
    };
}

export function ChannelTopicDetailRequestToJSON(value?: ChannelTopicDetailRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topic': value.topic,
    };
}

