/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for the ChannelDepartmentDetail model
 * @export
 * @interface ChannelDepartmentDetailRequest
 */
export interface ChannelDepartmentDetailRequest {
    /**
     * 
     * @type {string}
     * @memberof ChannelDepartmentDetailRequest
     */
    department?: string | null;
}

/**
 * Check if a given object implements the ChannelDepartmentDetailRequest interface.
 */
export function instanceOfChannelDepartmentDetailRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChannelDepartmentDetailRequestFromJSON(json: any): ChannelDepartmentDetailRequest {
    return ChannelDepartmentDetailRequestFromJSONTyped(json, false);
}

export function ChannelDepartmentDetailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelDepartmentDetailRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'department': !exists(json, 'department') ? undefined : json['department'],
    };
}

export function ChannelDepartmentDetailRequestToJSON(value?: ChannelDepartmentDetailRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'department': value.department,
    };
}

