/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { ChannelTypeEnum } from "./ChannelTypeEnum"
import {
  ChannelTypeEnumFromJSON,
  ChannelTypeEnumFromJSONTyped,
  ChannelTypeEnumToJSON,
} from "./ChannelTypeEnum"
import type { Counts } from "./Counts"
import { CountsFromJSON, CountsFromJSONTyped, CountsToJSON } from "./Counts"

/**
 * Serializer for resource counts associated with Channel
 * @export
 * @interface ChannelCounts
 */
export interface ChannelCounts {
  /**
   *
   * @type {number}
   * @memberof ChannelCounts
   */
  readonly id: number
  /**
   *
   * @type {Counts}
   * @memberof ChannelCounts
   */
  readonly counts: Counts
  /**
   * Get the URL for the channel
   * @type {string}
   * @memberof ChannelCounts
   */
  readonly channelUrl: string
  /**
   *
   * @type {Date}
   * @memberof ChannelCounts
   */
  readonly createdOn: Date
  /**
   *
   * @type {Date}
   * @memberof ChannelCounts
   */
  readonly updatedOn: Date
  /**
   *
   * @type {string}
   * @memberof ChannelCounts
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof ChannelCounts
   */
  title: string
  /**
   *
   * @type {ChannelTypeEnum}
   * @memberof ChannelCounts
   */
  channelType: ChannelTypeEnum
  /**
   *
   * @type {string}
   * @memberof ChannelCounts
   */
  searchFilter?: string
}

/**
 * Check if a given object implements the ChannelCounts interface.
 */
export function instanceOfChannelCounts(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "counts" in value
  isInstance = isInstance && "channelUrl" in value
  isInstance = isInstance && "createdOn" in value
  isInstance = isInstance && "updatedOn" in value
  isInstance = isInstance && "name" in value
  isInstance = isInstance && "title" in value
  isInstance = isInstance && "channelType" in value

  return isInstance
}

export function ChannelCountsFromJSON(json: any): ChannelCounts {
  return ChannelCountsFromJSONTyped(json, false)
}

export function ChannelCountsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChannelCounts {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json["id"],
    counts: CountsFromJSON(json["counts"]),
    channelUrl: json["channel_url"],
    createdOn: new Date(json["created_on"]),
    updatedOn: new Date(json["updated_on"]),
    name: json["name"],
    title: json["title"],
    channelType: ChannelTypeEnumFromJSON(json["channel_type"]),
    searchFilter: !exists(json, "search_filter")
      ? undefined
      : json["search_filter"],
  }
}

export function ChannelCountsToJSON(value?: ChannelCounts | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    name: value.name,
    title: value.title,
    channel_type: ChannelTypeEnumToJSON(value.channelType),
    search_filter: value.searchFilter,
  }
}
