/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 * Serializer for the ChannelTopicDetail model
 * @export
 * @interface ChannelTopicDetail
 */
export interface ChannelTopicDetail {
  /**
   *
   * @type {number}
   * @memberof ChannelTopicDetail
   */
  topic?: number | null
}

/**
 * Check if a given object implements the ChannelTopicDetail interface.
 */
export function instanceOfChannelTopicDetail(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChannelTopicDetailFromJSON(json: any): ChannelTopicDetail {
  return ChannelTopicDetailFromJSONTyped(json, false)
}

export function ChannelTopicDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChannelTopicDetail {
  if (json === undefined || json === null) {
    return json
  }
  return {
    topic: !exists(json, "topic") ? undefined : json["topic"],
  }
}

export function ChannelTopicDetailToJSON(
  value?: ChannelTopicDetail | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    topic: value.topic,
  }
}
