/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LearningResourceOfferorDetail } from './LearningResourceOfferorDetail';
import {
    LearningResourceOfferorDetailFromJSON,
    LearningResourceOfferorDetailFromJSONTyped,
    LearningResourceOfferorDetailToJSON,
} from './LearningResourceOfferorDetail';

/**
 * Serializer for the ChannelOfferorDetail model
 * @export
 * @interface ChannelUnitDetail
 */
export interface ChannelUnitDetail {
    /**
     * 
     * @type {LearningResourceOfferorDetail}
     * @memberof ChannelUnitDetail
     */
    readonly unit: LearningResourceOfferorDetail;
}

/**
 * Check if a given object implements the ChannelUnitDetail interface.
 */
export function instanceOfChannelUnitDetail(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "unit" in value;

    return isInstance;
}

export function ChannelUnitDetailFromJSON(json: any): ChannelUnitDetail {
    return ChannelUnitDetailFromJSONTyped(json, false);
}

export function ChannelUnitDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelUnitDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'unit': LearningResourceOfferorDetailFromJSON(json['unit']),
    };
}

export function ChannelUnitDetailToJSON(value?: ChannelUnitDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

