/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `page` - page
 * * `file` - file
 * * `video` - video
 * * `pdf` - pdf
 * @export
 */
export const ContentTypeEnum = {
  Page: "page",
  File: "file",
  Video: "video",
  Pdf: "pdf",
} as const
export type ContentTypeEnum =
  (typeof ContentTypeEnum)[keyof typeof ContentTypeEnum]

export function ContentTypeEnumFromJSON(json: any): ContentTypeEnum {
  return ContentTypeEnumFromJSONTyped(json, false)
}

export function ContentTypeEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ContentTypeEnum {
  return json as ContentTypeEnum
}

export function ContentTypeEnumToJSON(value?: ContentTypeEnum | null): any {
  return value as any
}
