/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentFileVectorSearchResponseMetadataAggregationsValueInner
 */
export interface ContentFileVectorSearchResponseMetadataAggregationsValueInner {
    /**
     * 
     * @type {string}
     * @memberof ContentFileVectorSearchResponseMetadataAggregationsValueInner
     */
    key: string;
    /**
     * 
     * @type {number}
     * @memberof ContentFileVectorSearchResponseMetadataAggregationsValueInner
     */
    docCount: number;
}

/**
 * Check if a given object implements the ContentFileVectorSearchResponseMetadataAggregationsValueInner interface.
 */
export function instanceOfContentFileVectorSearchResponseMetadataAggregationsValueInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "docCount" in value;

    return isInstance;
}

export function ContentFileVectorSearchResponseMetadataAggregationsValueInnerFromJSON(json: any): ContentFileVectorSearchResponseMetadataAggregationsValueInner {
    return ContentFileVectorSearchResponseMetadataAggregationsValueInnerFromJSONTyped(json, false);
}

export function ContentFileVectorSearchResponseMetadataAggregationsValueInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentFileVectorSearchResponseMetadataAggregationsValueInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'docCount': json['doc_count'],
    };
}

export function ContentFileVectorSearchResponseMetadataAggregationsValueInnerToJSON(value?: ContentFileVectorSearchResponseMetadataAggregationsValueInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'doc_count': value.docCount,
    };
}

