/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentFile } from './ContentFile';
import {
    ContentFileFromJSON,
    ContentFileFromJSONTyped,
    ContentFileToJSON,
} from './ContentFile';
import type { ContentFileVectorSearchResponseMetadata } from './ContentFileVectorSearchResponseMetadata';
import {
    ContentFileVectorSearchResponseMetadataFromJSON,
    ContentFileVectorSearchResponseMetadataFromJSONTyped,
    ContentFileVectorSearchResponseMetadataToJSON,
} from './ContentFileVectorSearchResponseMetadata';

/**
 * SearchResponseSerializer with OpenAPI annotations for Content Files search
 * @export
 * @interface ContentFileVectorSearchResponse
 */
export interface ContentFileVectorSearchResponse {
    /**
     * 
     * @type {number}
     * @memberof ContentFileVectorSearchResponse
     */
    readonly count: number;
    /**
     * 
     * @type {string}
     * @memberof ContentFileVectorSearchResponse
     */
    readonly next: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentFileVectorSearchResponse
     */
    readonly previous: string | null;
    /**
     * 
     * @type {Array<ContentFile>}
     * @memberof ContentFileVectorSearchResponse
     */
    readonly results: Array<ContentFile>;
    /**
     * 
     * @type {ContentFileVectorSearchResponseMetadata}
     * @memberof ContentFileVectorSearchResponse
     */
    metadata: ContentFileVectorSearchResponseMetadata;
}

/**
 * Check if a given object implements the ContentFileVectorSearchResponse interface.
 */
export function instanceOfContentFileVectorSearchResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "next" in value;
    isInstance = isInstance && "previous" in value;
    isInstance = isInstance && "results" in value;
    isInstance = isInstance && "metadata" in value;

    return isInstance;
}

export function ContentFileVectorSearchResponseFromJSON(json: any): ContentFileVectorSearchResponse {
    return ContentFileVectorSearchResponseFromJSONTyped(json, false);
}

export function ContentFileVectorSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentFileVectorSearchResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'results': ((json['results'] as Array<any>).map(ContentFileFromJSON)),
        'metadata': ContentFileVectorSearchResponseMetadataFromJSON(json['metadata']),
    };
}

export function ContentFileVectorSearchResponseToJSON(value?: ContentFileVectorSearchResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ContentFileVectorSearchResponseMetadataToJSON(value.metadata),
    };
}

