/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface Counts
 */
export interface Counts {
  /**
   *
   * @type {number}
   * @memberof Counts
   */
  courses: number
  /**
   *
   * @type {number}
   * @memberof Counts
   */
  programs: number
}

/**
 * Check if a given object implements the Counts interface.
 */
export function instanceOfCounts(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "courses" in value
  isInstance = isInstance && "programs" in value

  return isInstance
}

export function CountsFromJSON(json: any): Counts {
  return CountsFromJSONTyped(json, false)
}

export function CountsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Counts {
  if (json === undefined || json === null) {
    return json
  }
  return {
    courses: json["courses"],
    programs: json["programs"],
  }
}

export function CountsToJSON(value?: Counts | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    courses: value.courses,
    programs: value.programs,
  }
}
