/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourseNumber } from './CourseNumber';
import {
    CourseNumberFromJSON,
    CourseNumberFromJSONTyped,
    CourseNumberToJSON,
} from './CourseNumber';

/**
 * Serializer for the Course model
 * @export
 * @interface Course
 */
export interface Course {
    /**
     * 
     * @type {Array<CourseNumber>}
     * @memberof Course
     */
    courseNumbers: Array<CourseNumber> | null;
}

/**
 * Check if a given object implements the Course interface.
 */
export function instanceOfCourse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "courseNumbers" in value;

    return isInstance;
}

export function CourseFromJSON(json: any): Course {
    return CourseFromJSONTyped(json, false);
}

export function CourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Course {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courseNumbers': (json['course_numbers'] === null ? null : (json['course_numbers'] as Array<any>).map(CourseNumberFromJSON)),
    };
}

export function CourseToJSON(value?: Course | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'course_numbers': (value.courseNumbers === null ? null : (value.courseNumbers as Array<any>).map(CourseNumberToJSON)),
    };
}

