/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 * Learning path featured in this channel.
 * @export
 * @interface DepartmentChannelFeaturedList
 */
export interface DepartmentChannelFeaturedList {
  /**
   *
   * @type {string}
   * @memberof DepartmentChannelFeaturedList
   */
  title: string
  /**
   *
   * @type {string}
   * @memberof DepartmentChannelFeaturedList
   */
  url?: string | null
  /**
   *
   * @type {number}
   * @memberof DepartmentChannelFeaturedList
   */
  readonly id: number
}

/**
 * Check if a given object implements the DepartmentChannelFeaturedList interface.
 */
export function instanceOfDepartmentChannelFeaturedList(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "title" in value
  isInstance = isInstance && "id" in value

  return isInstance
}

export function DepartmentChannelFeaturedListFromJSON(
  json: any,
): DepartmentChannelFeaturedList {
  return DepartmentChannelFeaturedListFromJSONTyped(json, false)
}

export function DepartmentChannelFeaturedListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DepartmentChannelFeaturedList {
  if (json === undefined || json === null) {
    return json
  }
  return {
    title: json["title"],
    url: !exists(json, "url") ? undefined : json["url"],
    id: json["id"],
  }
}

export function DepartmentChannelFeaturedListToJSON(
  value?: DepartmentChannelFeaturedList | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    title: value.title,
    url: value.url,
  }
}
