/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EventFeedItemFeedTypeEnum = {
    Events: 'events'
} as const;
export type EventFeedItemFeedTypeEnum = typeof EventFeedItemFeedTypeEnum[keyof typeof EventFeedItemFeedTypeEnum];


export function EventFeedItemFeedTypeEnumFromJSON(json: any): EventFeedItemFeedTypeEnum {
    return EventFeedItemFeedTypeEnumFromJSONTyped(json, false);
}

export function EventFeedItemFeedTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventFeedItemFeedTypeEnum {
    return json as EventFeedItemFeedTypeEnum;
}

export function EventFeedItemFeedTypeEnumToJSON(value?: EventFeedItemFeedTypeEnum | null): any {
    return value as any;
}

