/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EventFeedItemFeedTypeEnum } from './EventFeedItemFeedTypeEnum';
import {
    EventFeedItemFeedTypeEnumFromJSON,
    EventFeedItemFeedTypeEnumFromJSONTyped,
    EventFeedItemFeedTypeEnumToJSON,
} from './EventFeedItemFeedTypeEnum';
import type { FeedEventDetail } from './FeedEventDetail';
import {
    FeedEventDetailFromJSON,
    FeedEventDetailFromJSONTyped,
    FeedEventDetailToJSON,
} from './FeedEventDetail';
import type { FeedImage } from './FeedImage';
import {
    FeedImageFromJSON,
    FeedImageFromJSONTyped,
    FeedImageToJSON,
} from './FeedImage';

/**
 * Serializer for News FeedItem
 * @export
 * @interface EventFeedItem
 */
export interface EventFeedItem {
    /**
     * 
     * @type {number}
     * @memberof EventFeedItem
     */
    readonly id: number;
    /**
     * 
     * @type {EventFeedItemFeedTypeEnum}
     * @memberof EventFeedItem
     */
    readonly feedType: EventFeedItemFeedTypeEnum;
    /**
     * 
     * @type {FeedImage}
     * @memberof EventFeedItem
     */
    image: FeedImage;
    /**
     * 
     * @type {FeedEventDetail}
     * @memberof EventFeedItem
     */
    eventDetails: FeedEventDetail;
    /**
     * 
     * @type {string}
     * @memberof EventFeedItem
     */
    guid: string;
    /**
     * 
     * @type {string}
     * @memberof EventFeedItem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof EventFeedItem
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof EventFeedItem
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof EventFeedItem
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof EventFeedItem
     */
    source: number;
}

/**
 * Check if a given object implements the EventFeedItem interface.
 */
export function instanceOfEventFeedItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "feedType" in value;
    isInstance = isInstance && "image" in value;
    isInstance = isInstance && "eventDetails" in value;
    isInstance = isInstance && "guid" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "source" in value;

    return isInstance;
}

export function EventFeedItemFromJSON(json: any): EventFeedItem {
    return EventFeedItemFromJSONTyped(json, false);
}

export function EventFeedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventFeedItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'feedType': EventFeedItemFeedTypeEnumFromJSON(json['feed_type']),
        'image': FeedImageFromJSON(json['image']),
        'eventDetails': FeedEventDetailFromJSON(json['event_details']),
        'guid': json['guid'],
        'title': json['title'],
        'url': json['url'],
        'summary': !exists(json, 'summary') ? undefined : json['summary'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'source': json['source'],
    };
}

export function EventFeedItemToJSON(value?: EventFeedItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image': FeedImageToJSON(value.image),
        'event_details': FeedEventDetailToJSON(value.eventDetails),
        'guid': value.guid,
        'title': value.title,
        'url': value.url,
        'summary': value.summary,
        'content': value.content,
        'source': value.source,
    };
}

