/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EventFeedItem } from './EventFeedItem';
import {
    instanceOfEventFeedItem,
    EventFeedItemFromJSON,
    EventFeedItemFromJSONTyped,
    EventFeedItemToJSON,
} from './EventFeedItem';
import type { NewsFeedItem } from './NewsFeedItem';
import {
    instanceOfNewsFeedItem,
    NewsFeedItemFromJSON,
    NewsFeedItemFromJSONTyped,
    NewsFeedItemToJSON,
} from './NewsFeedItem';

/**
 * @type FeedItem
 * 
 * @export
 */
export type FeedItem = { resourceType: 'events' } & EventFeedItem | { resourceType: 'news' } & NewsFeedItem;

export function FeedItemFromJSON(json: any): FeedItem {
    return FeedItemFromJSONTyped(json, false);
}

export function FeedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['resource_type']) {
        case 'events':
            return {...EventFeedItemFromJSONTyped(json, true), resourceType: 'events'};
        case 'news':
            return {...NewsFeedItemFromJSONTyped(json, true), resourceType: 'news'};
        default:
            throw new Error(`No variant of FeedItem exists with 'resourceType=${json['resourceType']}'`);
    }
}

export function FeedItemToJSON(value?: FeedItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['resourceType']) {
        case 'events':
            return EventFeedItemToJSON(value);
        case 'news':
            return NewsFeedItemToJSON(value);
        default:
            throw new Error(`No variant of FeedItem exists with 'resourceType=${value['resourceType']}'`);
    }

}

