/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for FeedImage
 * @export
 * @interface FeedImage
 */
export interface FeedImage {
    /**
     * 
     * @type {number}
     * @memberof FeedImage
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof FeedImage
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedImage
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedImage
     */
    alt?: string;
}

/**
 * Check if a given object implements the FeedImage interface.
 */
export function instanceOfFeedImage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function FeedImageFromJSON(json: any): FeedImage {
    return FeedImageFromJSONTyped(json, false);
}

export function FeedImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'alt': !exists(json, 'alt') ? undefined : json['alt'],
    };
}

export function FeedImageToJSON(value?: FeedImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'description': value.description,
        'alt': value.alt,
    };
}

