/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 * FeedEventDetail serializer
 * @export
 * @interface FeedEventDetail
 */
export interface FeedEventDetail {
  /**
   *
   * @type {number}
   * @memberof FeedEventDetail
   */
  readonly id: number
  /**
   *
   * @type {Array<string>}
   * @memberof FeedEventDetail
   */
  audience: Array<string>
  /**
   *
   * @type {Array<string>}
   * @memberof FeedEventDetail
   */
  location: Array<string>
  /**
   *
   * @type {Array<string>}
   * @memberof FeedEventDetail
   */
  eventType: Array<string>
  /**
   *
   * @type {Date}
   * @memberof FeedEventDetail
   */
  eventDatetime: Date
  /**
   *
   * @type {Date}
   * @memberof FeedEventDetail
   */
  eventEndDatetime?: Date | null
}

/**
 * Check if a given object implements the FeedEventDetail interface.
 */
export function instanceOfFeedEventDetail(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "audience" in value
  isInstance = isInstance && "location" in value
  isInstance = isInstance && "eventType" in value
  isInstance = isInstance && "eventDatetime" in value

  return isInstance
}

export function FeedEventDetailFromJSON(json: any): FeedEventDetail {
  return FeedEventDetailFromJSONTyped(json, false)
}

export function FeedEventDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FeedEventDetail {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json["id"],
    audience: json["audience"],
    location: json["location"],
    eventType: json["event_type"],
    eventDatetime: new Date(json["event_datetime"]),
    eventEndDatetime: !exists(json, "event_end_datetime")
      ? undefined
      : json["event_end_datetime"] === null
        ? null
        : new Date(json["event_end_datetime"]),
  }
}

export function FeedEventDetailToJSON(value?: FeedEventDetail | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    audience: value.audience,
    location: value.location,
    event_type: value.eventType,
    event_datetime: value.eventDatetime.toISOString(),
    event_end_datetime:
      value.eventEndDatetime === undefined
        ? undefined
        : value.eventEndDatetime === null
          ? null
          : value.eventEndDatetime.toISOString(),
  }
}
