/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `academic-excellence` - Academic Boost
 * * `career-growth` - Career Growth
 * * `lifelong-learning` - Lifelong Learning
 * @export
 */
export const GoalsEnum = {
    AcademicExcellence: 'academic-excellence',
    CareerGrowth: 'career-growth',
    LifelongLearning: 'lifelong-learning'
} as const;
export type GoalsEnum = typeof GoalsEnum[keyof typeof GoalsEnum];


export function GoalsEnumFromJSON(json: any): GoalsEnum {
    return GoalsEnumFromJSONTyped(json, false);
}

export function GoalsEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoalsEnum {
    return json as GoalsEnum;
}

export function GoalsEnumToJSON(value?: GoalsEnum | null): any {
    return value as any;
}

