/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for LearningResourceOfferor with basic details
 * @export
 * @interface LearningResourceOfferor
 */
export interface LearningResourceOfferor {
    /**
     * 
     * @type {string}
     * @memberof LearningResourceOfferor
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof LearningResourceOfferor
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LearningResourceOfferor
     */
    readonly channelUrl: string | null;
}

/**
 * Check if a given object implements the LearningResourceOfferor interface.
 */
export function instanceOfLearningResourceOfferor(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "channelUrl" in value;

    return isInstance;
}

export function LearningResourceOfferorFromJSON(json: any): LearningResourceOfferor {
    return LearningResourceOfferorFromJSONTyped(json, false);
}

export function LearningResourceOfferorFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningResourceOfferor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
        'channelUrl': json['channel_url'],
    };
}

export function LearningResourceOfferorToJSON(value?: LearningResourceOfferor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'name': value.name,
    };
}

