/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for LearningResourcePrice model
 * @export
 * @interface LearningResourcePrice
 */
export interface LearningResourcePrice {
    /**
     * 
     * @type {string}
     * @memberof LearningResourcePrice
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof LearningResourcePrice
     */
    currency: string;
}

/**
 * Check if a given object implements the LearningResourcePrice interface.
 */
export function instanceOfLearningResourcePrice(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "currency" in value;

    return isInstance;
}

export function LearningResourcePriceFromJSON(json: any): LearningResourcePrice {
    return LearningResourcePriceFromJSONTyped(json, false);
}

export function LearningResourcePriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningResourcePrice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'currency': json['currency'],
    };
}

export function LearningResourcePriceToJSON(value?: LearningResourcePrice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'currency': value.currency,
    };
}

