/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const LearningPathResourceResourceTypeEnum = {
  LearningPath: "learning_path",
} as const
export type LearningPathResourceResourceTypeEnum =
  (typeof LearningPathResourceResourceTypeEnum)[keyof typeof LearningPathResourceResourceTypeEnum]

export function LearningPathResourceResourceTypeEnumFromJSON(
  json: any,
): LearningPathResourceResourceTypeEnum {
  return LearningPathResourceResourceTypeEnumFromJSONTyped(json, false)
}

export function LearningPathResourceResourceTypeEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LearningPathResourceResourceTypeEnum {
  return json as LearningPathResourceResourceTypeEnum
}

export function LearningPathResourceResourceTypeEnumToJSON(
  value?: LearningPathResourceResourceTypeEnum | null,
): any {
  return value as any
}
