/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for the LearningPath model
 * @export
 * @interface LearningPath
 */
export interface LearningPath {
    /**
     * 
     * @type {number}
     * @memberof LearningPath
     */
    readonly id: number;
    /**
     * Return the number of items in the list
     * @type {number}
     * @memberof LearningPath
     */
    readonly itemCount: number;
}

/**
 * Check if a given object implements the LearningPath interface.
 */
export function instanceOfLearningPath(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "itemCount" in value;

    return isInstance;
}

export function LearningPathFromJSON(json: any): LearningPath {
    return LearningPathFromJSONTyped(json, false);
}

export function LearningPathFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningPath {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'itemCount': json['item_count'],
    };
}

export function LearningPathToJSON(value?: LearningPath | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

