/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NewsFeedItemFeedTypeEnum = {
    News: 'news'
} as const;
export type NewsFeedItemFeedTypeEnum = typeof NewsFeedItemFeedTypeEnum[keyof typeof NewsFeedItemFeedTypeEnum];


export function NewsFeedItemFeedTypeEnumFromJSON(json: any): NewsFeedItemFeedTypeEnum {
    return NewsFeedItemFeedTypeEnumFromJSONTyped(json, false);
}

export function NewsFeedItemFeedTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewsFeedItemFeedTypeEnum {
    return json as NewsFeedItemFeedTypeEnum;
}

export function NewsFeedItemFeedTypeEnumToJSON(value?: NewsFeedItemFeedTypeEnum | null): any {
    return value as any;
}

