/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { FeedItem } from "./FeedItem"
import {
  FeedItemFromJSON,
  FeedItemFromJSONTyped,
  FeedItemToJSON,
} from "./FeedItem"

/**
 *
 * @export
 * @interface PaginatedFeedItemList
 */
export interface PaginatedFeedItemList {
  /**
   *
   * @type {number}
   * @memberof PaginatedFeedItemList
   */
  count: number
  /**
   *
   * @type {string}
   * @memberof PaginatedFeedItemList
   */
  next?: string | null
  /**
   *
   * @type {string}
   * @memberof PaginatedFeedItemList
   */
  previous?: string | null
  /**
   *
   * @type {Array<FeedItem>}
   * @memberof PaginatedFeedItemList
   */
  results: Array<FeedItem>
}

/**
 * Check if a given object implements the PaginatedFeedItemList interface.
 */
export function instanceOfPaginatedFeedItemList(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "count" in value
  isInstance = isInstance && "results" in value

  return isInstance
}

export function PaginatedFeedItemListFromJSON(
  json: any,
): PaginatedFeedItemList {
  return PaginatedFeedItemListFromJSONTyped(json, false)
}

export function PaginatedFeedItemListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaginatedFeedItemList {
  if (json === undefined || json === null) {
    return json
  }
  return {
    count: json["count"],
    next: !exists(json, "next") ? undefined : json["next"],
    previous: !exists(json, "previous") ? undefined : json["previous"],
    results: (json["results"] as Array<any>).map(FeedItemFromJSON),
  }
}

export function PaginatedFeedItemListToJSON(
  value?: PaginatedFeedItemList | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    count: value.count,
    next: value.next,
    previous: value.previous,
    results: (value.results as Array<any>).map(FeedItemToJSON),
  }
}
