/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FeedSource } from './FeedSource';
import {
    FeedSourceFromJSON,
    FeedSourceFromJSONTyped,
    FeedSourceToJSON,
} from './FeedSource';

/**
 * 
 * @export
 * @interface PaginatedFeedSourceList
 */
export interface PaginatedFeedSourceList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedFeedSourceList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFeedSourceList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFeedSourceList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<FeedSource>}
     * @memberof PaginatedFeedSourceList
     */
    results: Array<FeedSource>;
}

/**
 * Check if a given object implements the PaginatedFeedSourceList interface.
 */
export function instanceOfPaginatedFeedSourceList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function PaginatedFeedSourceListFromJSON(json: any): PaginatedFeedSourceList {
    return PaginatedFeedSourceListFromJSONTyped(json, false);
}

export function PaginatedFeedSourceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFeedSourceList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(FeedSourceFromJSON)),
    };
}

export function PaginatedFeedSourceListToJSON(value?: PaginatedFeedSourceList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(FeedSourceToJSON)),
    };
}

