/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Channel } from './Channel';
import {
    ChannelFromJSON,
    ChannelFromJSONTyped,
    ChannelToJSON,
} from './Channel';

/**
 * 
 * @export
 * @interface PaginatedChannelList
 */
export interface PaginatedChannelList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedChannelList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedChannelList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedChannelList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Channel>}
     * @memberof PaginatedChannelList
     */
    results: Array<Channel>;
}

/**
 * Check if a given object implements the PaginatedChannelList interface.
 */
export function instanceOfPaginatedChannelList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function PaginatedChannelListFromJSON(json: any): PaginatedChannelList {
    return PaginatedChannelListFromJSONTyped(json, false);
}

export function PaginatedChannelListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedChannelList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ChannelFromJSON)),
    };
}

export function PaginatedChannelListToJSON(value?: PaginatedChannelList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(ChannelToJSON)),
    };
}

