/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlankEnum } from './BlankEnum';
import {
    instanceOfBlankEnum,
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { CertificateDesiredEnum } from './CertificateDesiredEnum';
import {
    instanceOfCertificateDesiredEnum,
    CertificateDesiredEnumFromJSON,
    CertificateDesiredEnumFromJSONTyped,
    CertificateDesiredEnumToJSON,
} from './CertificateDesiredEnum';

/**
 * @type PatchedProfileRequestCertificateDesired
 * 
 * @export
 */
export type PatchedProfileRequestCertificateDesired = BlankEnum | CertificateDesiredEnum;

export function PatchedProfileRequestCertificateDesiredFromJSON(json: any): PatchedProfileRequestCertificateDesired {
    return PatchedProfileRequestCertificateDesiredFromJSONTyped(json, false);
}

export function PatchedProfileRequestCertificateDesiredFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProfileRequestCertificateDesired {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...BlankEnumFromJSONTyped(json, true), ...CertificateDesiredEnumFromJSONTyped(json, true) };
}

export function PatchedProfileRequestCertificateDesiredToJSON(value?: PatchedProfileRequestCertificateDesired | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfBlankEnum(value)) {
        return BlankEnumToJSON(value as BlankEnum);
    }
    if (instanceOfCertificateDesiredEnum(value)) {
        return CertificateDesiredEnumToJSON(value as CertificateDesiredEnum);
    }

    return {};
}

