/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { ChannelDepartmentDetailRequest } from "./ChannelDepartmentDetailRequest"
import {
  ChannelDepartmentDetailRequestFromJSON,
  ChannelDepartmentDetailRequestFromJSONTyped,
  ChannelDepartmentDetailRequestToJSON,
} from "./ChannelDepartmentDetailRequest"
import type { ChannelTopicDetailRequest } from "./ChannelTopicDetailRequest"
import {
  ChannelTopicDetailRequestFromJSON,
  ChannelTopicDetailRequestFromJSONTyped,
  ChannelTopicDetailRequestToJSON,
} from "./ChannelTopicDetailRequest"
import type { ChannelTypeEnum } from "./ChannelTypeEnum"
import {
  ChannelTypeEnumFromJSON,
  ChannelTypeEnumFromJSONTyped,
  ChannelTypeEnumToJSON,
} from "./ChannelTypeEnum"

/**
 * Similar to ChannelCreateSerializer, with read-only name
 * @export
 * @interface PatchedChannelWriteRequest
 */
export interface PatchedChannelWriteRequest {
  /**
   *
   * @type {string}
   * @memberof PatchedChannelWriteRequest
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof PatchedChannelWriteRequest
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof PatchedChannelWriteRequest
   */
  publicDescription?: string
  /**
   *
   * @type {Array<string>}
   * @memberof PatchedChannelWriteRequest
   */
  subChannels?: Array<string>
  /**
   * Learning path featured in this channel.
   * @type {number}
   * @memberof PatchedChannelWriteRequest
   */
  featuredList?: number | null
  /**
   * Learning paths in this channel.
   * @type {Array<number>}
   * @memberof PatchedChannelWriteRequest
   */
  lists?: Array<number>
  /**
   * Get the avatar image URL
   * @type {string}
   * @memberof PatchedChannelWriteRequest
   */
  avatar?: string | null
  /**
   * Get the banner image URL
   * @type {string}
   * @memberof PatchedChannelWriteRequest
   */
  banner?: string | null
  /**
   *
   * @type {any}
   * @memberof PatchedChannelWriteRequest
   */
  about?: any | null
  /**
   *
   * @type {ChannelTypeEnum}
   * @memberof PatchedChannelWriteRequest
   */
  channelType?: ChannelTypeEnum
  /**
   *
   * @type {string}
   * @memberof PatchedChannelWriteRequest
   */
  searchFilter?: string
  /**
   *
   * @type {ChannelTopicDetailRequest}
   * @memberof PatchedChannelWriteRequest
   */
  topicDetail?: ChannelTopicDetailRequest | null
  /**
   *
   * @type {ChannelDepartmentDetailRequest}
   * @memberof PatchedChannelWriteRequest
   */
  departmentDetail?: ChannelDepartmentDetailRequest | null
}

/**
 * Check if a given object implements the PatchedChannelWriteRequest interface.
 */
export function instanceOfPatchedChannelWriteRequest(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function PatchedChannelWriteRequestFromJSON(
  json: any,
): PatchedChannelWriteRequest {
  return PatchedChannelWriteRequestFromJSONTyped(json, false)
}

export function PatchedChannelWriteRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PatchedChannelWriteRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    title: !exists(json, "title") ? undefined : json["title"],
    publicDescription: !exists(json, "public_description")
      ? undefined
      : json["public_description"],
    subChannels: !exists(json, "sub_channels")
      ? undefined
      : json["sub_channels"],
    featuredList: !exists(json, "featured_list")
      ? undefined
      : json["featured_list"],
    lists: !exists(json, "lists") ? undefined : json["lists"],
    avatar: !exists(json, "avatar") ? undefined : json["avatar"],
    banner: !exists(json, "banner") ? undefined : json["banner"],
    about: !exists(json, "about") ? undefined : json["about"],
    channelType: !exists(json, "channel_type")
      ? undefined
      : ChannelTypeEnumFromJSON(json["channel_type"]),
    searchFilter: !exists(json, "search_filter")
      ? undefined
      : json["search_filter"],
    topicDetail: !exists(json, "topic_detail")
      ? undefined
      : ChannelTopicDetailRequestFromJSON(json["topic_detail"]),
    departmentDetail: !exists(json, "department_detail")
      ? undefined
      : ChannelDepartmentDetailRequestFromJSON(json["department_detail"]),
  }
}

export function PatchedChannelWriteRequestToJSON(
  value?: PatchedChannelWriteRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    name: value.name,
    title: value.title,
    public_description: value.publicDescription,
    sub_channels: value.subChannels,
    featured_list: value.featuredList,
    lists: value.lists,
    avatar: value.avatar,
    banner: value.banner,
    about: value.about,
    channel_type: ChannelTypeEnumToJSON(value.channelType),
    search_filter: value.searchFilter,
    topic_detail: ChannelTopicDetailRequestToJSON(value.topicDetail),
    department_detail: ChannelDepartmentDetailRequestToJSON(
      value.departmentDetail,
    ),
  }
}
