/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeliveryEnum } from './DeliveryEnum';
import {
    DeliveryEnumFromJSON,
    DeliveryEnumFromJSONTyped,
    DeliveryEnumToJSON,
} from './DeliveryEnum';
import type { GoalsEnum } from './GoalsEnum';
import {
    GoalsEnumFromJSON,
    GoalsEnumFromJSONTyped,
    GoalsEnumToJSON,
} from './GoalsEnum';
import type { PatchedProfileRequestCertificateDesired } from './PatchedProfileRequestCertificateDesired';
import {
    PatchedProfileRequestCertificateDesiredFromJSON,
    PatchedProfileRequestCertificateDesiredFromJSONTyped,
    PatchedProfileRequestCertificateDesiredToJSON,
} from './PatchedProfileRequestCertificateDesired';
import type { PatchedProfileRequestCurrentEducation } from './PatchedProfileRequestCurrentEducation';
import {
    PatchedProfileRequestCurrentEducationFromJSON,
    PatchedProfileRequestCurrentEducationFromJSONTyped,
    PatchedProfileRequestCurrentEducationToJSON,
} from './PatchedProfileRequestCurrentEducation';
import type { PatchedProfileRequestTimeCommitment } from './PatchedProfileRequestTimeCommitment';
import {
    PatchedProfileRequestTimeCommitmentFromJSON,
    PatchedProfileRequestTimeCommitmentFromJSONTyped,
    PatchedProfileRequestTimeCommitmentToJSON,
} from './PatchedProfileRequestTimeCommitment';

/**
 * Serializer for Profile
 * @export
 * @interface PatchedProfileRequest
 */
export interface PatchedProfileRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedProfileRequest
     */
    image?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProfileRequest
     */
    imageSmall?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProfileRequest
     */
    imageMedium?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProfileRequest
     */
    emailOptin?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProfileRequest
     */
    tocOptin?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedProfileRequest
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProfileRequest
     */
    headline?: string | null;
    /**
     * 
     * @type {any}
     * @memberof PatchedProfileRequest
     */
    location?: any | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchedProfileRequest
     */
    topicInterests?: Array<number>;
    /**
     * 
     * @type {Array<GoalsEnum>}
     * @memberof PatchedProfileRequest
     */
    goals?: Array<GoalsEnum>;
    /**
     * 
     * @type {PatchedProfileRequestCurrentEducation}
     * @memberof PatchedProfileRequest
     */
    currentEducation?: PatchedProfileRequestCurrentEducation;
    /**
     * 
     * @type {PatchedProfileRequestCertificateDesired}
     * @memberof PatchedProfileRequest
     */
    certificateDesired?: PatchedProfileRequestCertificateDesired;
    /**
     * 
     * @type {PatchedProfileRequestTimeCommitment}
     * @memberof PatchedProfileRequest
     */
    timeCommitment?: PatchedProfileRequestTimeCommitment;
    /**
     * 
     * @type {Array<DeliveryEnum>}
     * @memberof PatchedProfileRequest
     */
    delivery?: Array<DeliveryEnum>;
}

/**
 * Check if a given object implements the PatchedProfileRequest interface.
 */
export function instanceOfPatchedProfileRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedProfileRequestFromJSON(json: any): PatchedProfileRequest {
    return PatchedProfileRequestFromJSONTyped(json, false);
}

export function PatchedProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProfileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'image': !exists(json, 'image') ? undefined : json['image'],
        'imageSmall': !exists(json, 'image_small') ? undefined : json['image_small'],
        'imageMedium': !exists(json, 'image_medium') ? undefined : json['image_medium'],
        'emailOptin': !exists(json, 'email_optin') ? undefined : json['email_optin'],
        'tocOptin': !exists(json, 'toc_optin') ? undefined : json['toc_optin'],
        'bio': !exists(json, 'bio') ? undefined : json['bio'],
        'headline': !exists(json, 'headline') ? undefined : json['headline'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'topicInterests': !exists(json, 'topic_interests') ? undefined : json['topic_interests'],
        'goals': !exists(json, 'goals') ? undefined : ((json['goals'] as Array<any>).map(GoalsEnumFromJSON)),
        'currentEducation': !exists(json, 'current_education') ? undefined : PatchedProfileRequestCurrentEducationFromJSON(json['current_education']),
        'certificateDesired': !exists(json, 'certificate_desired') ? undefined : PatchedProfileRequestCertificateDesiredFromJSON(json['certificate_desired']),
        'timeCommitment': !exists(json, 'time_commitment') ? undefined : PatchedProfileRequestTimeCommitmentFromJSON(json['time_commitment']),
        'delivery': !exists(json, 'delivery') ? undefined : ((json['delivery'] as Array<any>).map(DeliveryEnumFromJSON)),
    };
}

export function PatchedProfileRequestToJSON(value?: PatchedProfileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image': value.image,
        'image_small': value.imageSmall,
        'image_medium': value.imageMedium,
        'email_optin': value.emailOptin,
        'toc_optin': value.tocOptin,
        'bio': value.bio,
        'headline': value.headline,
        'location': value.location,
        'topic_interests': value.topicInterests,
        'goals': value.goals === undefined ? undefined : ((value.goals as Array<any>).map(GoalsEnumToJSON)),
        'current_education': PatchedProfileRequestCurrentEducationToJSON(value.currentEducation),
        'certificate_desired': PatchedProfileRequestCertificateDesiredToJSON(value.certificateDesired),
        'time_commitment': PatchedProfileRequestTimeCommitmentToJSON(value.timeCommitment),
        'delivery': value.delivery === undefined ? undefined : ((value.delivery as Array<any>).map(DeliveryEnumToJSON)),
    };
}

