/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const PodcastEpisodeResourceResourceTypeEnum = {
  PodcastEpisode: "podcast_episode",
} as const
export type PodcastEpisodeResourceResourceTypeEnum =
  (typeof PodcastEpisodeResourceResourceTypeEnum)[keyof typeof PodcastEpisodeResourceResourceTypeEnum]

export function PodcastEpisodeResourceResourceTypeEnumFromJSON(
  json: any,
): PodcastEpisodeResourceResourceTypeEnum {
  return PodcastEpisodeResourceResourceTypeEnumFromJSONTyped(json, false)
}

export function PodcastEpisodeResourceResourceTypeEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PodcastEpisodeResourceResourceTypeEnum {
  return json as PodcastEpisodeResourceResourceTypeEnum
}

export function PodcastEpisodeResourceResourceTypeEnumToJSON(
  value?: PodcastEpisodeResourceResourceTypeEnum | null,
): any {
  return value as any
}
