/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeliveryEnum } from './DeliveryEnum';
import {
    DeliveryEnumFromJSON,
    DeliveryEnumFromJSONTyped,
    DeliveryEnumToJSON,
} from './DeliveryEnum';
import type { GoalsEnum } from './GoalsEnum';
import {
    GoalsEnumFromJSON,
    GoalsEnumFromJSONTyped,
    GoalsEnumToJSON,
} from './GoalsEnum';
import type { LearningResourceTopic } from './LearningResourceTopic';
import {
    LearningResourceTopicFromJSON,
    LearningResourceTopicFromJSONTyped,
    LearningResourceTopicToJSON,
} from './LearningResourceTopic';
import type { PatchedProfileRequestCertificateDesired } from './PatchedProfileRequestCertificateDesired';
import {
    PatchedProfileRequestCertificateDesiredFromJSON,
    PatchedProfileRequestCertificateDesiredFromJSONTyped,
    PatchedProfileRequestCertificateDesiredToJSON,
} from './PatchedProfileRequestCertificateDesired';
import type { PatchedProfileRequestCurrentEducation } from './PatchedProfileRequestCurrentEducation';
import {
    PatchedProfileRequestCurrentEducationFromJSON,
    PatchedProfileRequestCurrentEducationFromJSONTyped,
    PatchedProfileRequestCurrentEducationToJSON,
} from './PatchedProfileRequestCurrentEducation';
import type { PatchedProfileRequestTimeCommitment } from './PatchedProfileRequestTimeCommitment';
import {
    PatchedProfileRequestTimeCommitmentFromJSON,
    PatchedProfileRequestTimeCommitmentFromJSONTyped,
    PatchedProfileRequestTimeCommitmentToJSON,
} from './PatchedProfileRequestTimeCommitment';
import type { PreferencesSearch } from './PreferencesSearch';
import {
    PreferencesSearchFromJSON,
    PreferencesSearchFromJSONTyped,
    PreferencesSearchToJSON,
} from './PreferencesSearch';

/**
 * Serializer for Profile
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * Get the user's name
     * @type {string}
     * @memberof Profile
     */
    readonly name: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    image?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    imageSmall?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    imageMedium?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    readonly imageFile: string | null;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    readonly imageSmallFile: string | null;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    readonly imageMediumFile: string | null;
    /**
     * Custom getter for small profile image
     * @type {string}
     * @memberof Profile
     */
    readonly profileImageSmall: string;
    /**
     * Custom getter for medium profile image
     * @type {string}
     * @memberof Profile
     */
    readonly profileImageMedium: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    headline?: string | null;
    /**
     * Custom getter for the username
     * @type {string}
     * @memberof Profile
     */
    readonly username: string;
    /**
     * Custom getter for location text
     * @type {string}
     * @memberof Profile
     */
    readonly placename: string;
    /**
     * 
     * @type {Array<LearningResourceTopic>}
     * @memberof Profile
     */
    topicInterests?: Array<LearningResourceTopic>;
    /**
     * 
     * @type {Array<GoalsEnum>}
     * @memberof Profile
     */
    goals?: Array<GoalsEnum>;
    /**
     * 
     * @type {PatchedProfileRequestCurrentEducation}
     * @memberof Profile
     */
    currentEducation?: PatchedProfileRequestCurrentEducation;
    /**
     * 
     * @type {PatchedProfileRequestCertificateDesired}
     * @memberof Profile
     */
    certificateDesired?: PatchedProfileRequestCertificateDesired;
    /**
     * 
     * @type {PatchedProfileRequestTimeCommitment}
     * @memberof Profile
     */
    timeCommitment?: PatchedProfileRequestTimeCommitment;
    /**
     * 
     * @type {Array<DeliveryEnum>}
     * @memberof Profile
     */
    delivery?: Array<DeliveryEnum>;
    /**
     * 
     * @type {PreferencesSearch}
     * @memberof Profile
     */
    readonly preferenceSearchFilters: PreferencesSearch;
}

/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "imageFile" in value;
    isInstance = isInstance && "imageSmallFile" in value;
    isInstance = isInstance && "imageMediumFile" in value;
    isInstance = isInstance && "profileImageSmall" in value;
    isInstance = isInstance && "profileImageMedium" in value;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "placename" in value;
    isInstance = isInstance && "preferenceSearchFilters" in value;

    return isInstance;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'imageSmall': !exists(json, 'image_small') ? undefined : json['image_small'],
        'imageMedium': !exists(json, 'image_medium') ? undefined : json['image_medium'],
        'imageFile': json['image_file'],
        'imageSmallFile': json['image_small_file'],
        'imageMediumFile': json['image_medium_file'],
        'profileImageSmall': json['profile_image_small'],
        'profileImageMedium': json['profile_image_medium'],
        'bio': !exists(json, 'bio') ? undefined : json['bio'],
        'headline': !exists(json, 'headline') ? undefined : json['headline'],
        'username': json['username'],
        'placename': json['placename'],
        'topicInterests': !exists(json, 'topic_interests') ? undefined : ((json['topic_interests'] as Array<any>).map(LearningResourceTopicFromJSON)),
        'goals': !exists(json, 'goals') ? undefined : ((json['goals'] as Array<any>).map(GoalsEnumFromJSON)),
        'currentEducation': !exists(json, 'current_education') ? undefined : PatchedProfileRequestCurrentEducationFromJSON(json['current_education']),
        'certificateDesired': !exists(json, 'certificate_desired') ? undefined : PatchedProfileRequestCertificateDesiredFromJSON(json['certificate_desired']),
        'timeCommitment': !exists(json, 'time_commitment') ? undefined : PatchedProfileRequestTimeCommitmentFromJSON(json['time_commitment']),
        'delivery': !exists(json, 'delivery') ? undefined : ((json['delivery'] as Array<any>).map(DeliveryEnumFromJSON)),
        'preferenceSearchFilters': PreferencesSearchFromJSON(json['preference_search_filters']),
    };
}

export function ProfileToJSON(value?: Profile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image': value.image,
        'image_small': value.imageSmall,
        'image_medium': value.imageMedium,
        'bio': value.bio,
        'headline': value.headline,
        'topic_interests': value.topicInterests === undefined ? undefined : ((value.topicInterests as Array<any>).map(LearningResourceTopicToJSON)),
        'goals': value.goals === undefined ? undefined : ((value.goals as Array<any>).map(GoalsEnumToJSON)),
        'current_education': PatchedProfileRequestCurrentEducationToJSON(value.currentEducation),
        'certificate_desired': PatchedProfileRequestCertificateDesiredToJSON(value.certificateDesired),
        'time_commitment': PatchedProfileRequestTimeCommitmentToJSON(value.timeCommitment),
        'delivery': value.delivery === undefined ? undefined : ((value.delivery as Array<any>).map(DeliveryEnumToJSON)),
    };
}

