/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for Program Certificates
 * @export
 * @interface ProgramCertificate
 */
export interface ProgramCertificate {
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    readonly recordHash: string;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    readonly programLetterGenerateUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    readonly programLetterShareUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    programTitle: string;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    userFullName?: string;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    userEmail: string;
    /**
     * 
     * @type {number}
     * @memberof ProgramCertificate
     */
    userEdxorgId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProgramCertificate
     */
    micromastersProgramId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProgramCertificate
     */
    mitxonlineProgramId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    userEdxorgUsername?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    userGender?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    userAddressCity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    userFirstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    userLastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    userYearOfBirth?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    userCountry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    userAddressPostalCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    userStreetAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    userAddressStateOrTerritory?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProgramCertificate
     */
    userMitxonlineUsername?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ProgramCertificate
     */
    programCompletionTimestamp?: Date | null;
}

/**
 * Check if a given object implements the ProgramCertificate interface.
 */
export function instanceOfProgramCertificate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "recordHash" in value;
    isInstance = isInstance && "programLetterGenerateUrl" in value;
    isInstance = isInstance && "programLetterShareUrl" in value;
    isInstance = isInstance && "programTitle" in value;
    isInstance = isInstance && "userEmail" in value;

    return isInstance;
}

export function ProgramCertificateFromJSON(json: any): ProgramCertificate {
    return ProgramCertificateFromJSONTyped(json, false);
}

export function ProgramCertificateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProgramCertificate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recordHash': json['record_hash'],
        'programLetterGenerateUrl': json['program_letter_generate_url'],
        'programLetterShareUrl': json['program_letter_share_url'],
        'programTitle': json['program_title'],
        'userFullName': !exists(json, 'user_full_name') ? undefined : json['user_full_name'],
        'userEmail': json['user_email'],
        'userEdxorgId': !exists(json, 'user_edxorg_id') ? undefined : json['user_edxorg_id'],
        'micromastersProgramId': !exists(json, 'micromasters_program_id') ? undefined : json['micromasters_program_id'],
        'mitxonlineProgramId': !exists(json, 'mitxonline_program_id') ? undefined : json['mitxonline_program_id'],
        'userEdxorgUsername': !exists(json, 'user_edxorg_username') ? undefined : json['user_edxorg_username'],
        'userGender': !exists(json, 'user_gender') ? undefined : json['user_gender'],
        'userAddressCity': !exists(json, 'user_address_city') ? undefined : json['user_address_city'],
        'userFirstName': !exists(json, 'user_first_name') ? undefined : json['user_first_name'],
        'userLastName': !exists(json, 'user_last_name') ? undefined : json['user_last_name'],
        'userYearOfBirth': !exists(json, 'user_year_of_birth') ? undefined : json['user_year_of_birth'],
        'userCountry': !exists(json, 'user_country') ? undefined : json['user_country'],
        'userAddressPostalCode': !exists(json, 'user_address_postal_code') ? undefined : json['user_address_postal_code'],
        'userStreetAddress': !exists(json, 'user_street_address') ? undefined : json['user_street_address'],
        'userAddressStateOrTerritory': !exists(json, 'user_address_state_or_territory') ? undefined : json['user_address_state_or_territory'],
        'userMitxonlineUsername': !exists(json, 'user_mitxonline_username') ? undefined : json['user_mitxonline_username'],
        'programCompletionTimestamp': !exists(json, 'program_completion_timestamp') ? undefined : (json['program_completion_timestamp'] === null ? null : new Date(json['program_completion_timestamp'])),
    };
}

export function ProgramCertificateToJSON(value?: ProgramCertificate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'program_title': value.programTitle,
        'user_full_name': value.userFullName,
        'user_email': value.userEmail,
        'user_edxorg_id': value.userEdxorgId,
        'micromasters_program_id': value.micromastersProgramId,
        'mitxonline_program_id': value.mitxonlineProgramId,
        'user_edxorg_username': value.userEdxorgUsername,
        'user_gender': value.userGender,
        'user_address_city': value.userAddressCity,
        'user_first_name': value.userFirstName,
        'user_last_name': value.userLastName,
        'user_year_of_birth': value.userYearOfBirth,
        'user_country': value.userCountry,
        'user_address_postal_code': value.userAddressPostalCode,
        'user_street_address': value.userStreetAddress,
        'user_address_state_or_territory': value.userAddressStateOrTerritory,
        'user_mitxonline_username': value.userMitxonlineUsername,
        'program_completion_timestamp': value.programCompletionTimestamp === undefined ? undefined : (value.programCompletionTimestamp === null ? null : value.programCompletionTimestamp.toISOString()),
    };
}

