/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `news` - news
 * * `events` - events
 * @export
 */
export const ResourceTypeEnum = {
  News: "news",
  Events: "events",
} as const
export type ResourceTypeEnum =
  (typeof ResourceTypeEnum)[keyof typeof ResourceTypeEnum]

export function ResourceTypeEnumFromJSON(json: any): ResourceTypeEnum {
  return ResourceTypeEnumFromJSONTyped(json, false)
}

export function ResourceTypeEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResourceTypeEnum {
  return json as ResourceTypeEnum
}

export function ResourceTypeEnumToJSON(value?: ResourceTypeEnum | null): any {
  return value as any
}
