/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetrieveProblemResponse
 */
export interface RetrieveProblemResponse {
    /**
     * 
     * @type {string}
     * @memberof RetrieveProblemResponse
     */
    problemSet: string;
    /**
     * 
     * @type {string}
     * @memberof RetrieveProblemResponse
     */
    solutionSet: string;
}

/**
 * Check if a given object implements the RetrieveProblemResponse interface.
 */
export function instanceOfRetrieveProblemResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "problemSet" in value;
    isInstance = isInstance && "solutionSet" in value;

    return isInstance;
}

export function RetrieveProblemResponseFromJSON(json: any): RetrieveProblemResponse {
    return RetrieveProblemResponseFromJSONTyped(json, false);
}

export function RetrieveProblemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveProblemResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'problemSet': json['problem_set'],
        'solutionSet': json['solution_set'],
    };
}

export function RetrieveProblemResponseToJSON(value?: RetrieveProblemResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'problem_set': value.problemSet,
        'solution_set': value.solutionSet,
    };
}

