/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `facebook` - facebook
 * * `linkedin` - linkedin
 * * `personal` - personal
 * * `twitter` - twitter
 * @export
 */
export const SiteTypeEnum = {
  Facebook: "facebook",
  Linkedin: "linkedin",
  Personal: "personal",
  Twitter: "twitter",
} as const
export type SiteTypeEnum = (typeof SiteTypeEnum)[keyof typeof SiteTypeEnum]

export function SiteTypeEnumFromJSON(json: any): SiteTypeEnum {
  return SiteTypeEnumFromJSONTyped(json, false)
}

export function SiteTypeEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SiteTypeEnum {
  return json as SiteTypeEnum
}

export function SiteTypeEnumToJSON(value?: SiteTypeEnum | null): any {
  return value as any
}
