/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 * Serializer for SubChannels
 * @export
 * @interface SubChannel
 */
export interface SubChannel {
  /**
   *
   * @type {string}
   * @memberof SubChannel
   */
  readonly parentChannel: string
  /**
   *
   * @type {string}
   * @memberof SubChannel
   */
  readonly channel: string
  /**
   *
   * @type {number}
   * @memberof SubChannel
   */
  position?: number
}

/**
 * Check if a given object implements the SubChannel interface.
 */
export function instanceOfSubChannel(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "parentChannel" in value
  isInstance = isInstance && "channel" in value

  return isInstance
}

export function SubChannelFromJSON(json: any): SubChannel {
  return SubChannelFromJSONTyped(json, false)
}

export function SubChannelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SubChannel {
  if (json === undefined || json === null) {
    return json
  }
  return {
    parentChannel: json["parent_channel"],
    channel: json["channel"],
    position: !exists(json, "position") ? undefined : json["position"],
  }
}

export function SubChannelToJSON(value?: SubChannel | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    position: value.position,
  }
}
