/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `0-to-5-hours` - <5 hours/week
 * * `5-to-10-hours` - 5-10 hours/week
 * * `10-to-20-hours` - 10-20 hours/week
 * * `20-to-30-hours` - 20-30 hours/week
 * * `30-plus-hours` - 30+ hours/week
 * @export
 */
export const TimeCommitmentEnum = {
    _0To5Hours: '0-to-5-hours',
    _5To10Hours: '5-to-10-hours',
    _10To20Hours: '10-to-20-hours',
    _20To30Hours: '20-to-30-hours',
    _30PlusHours: '30-plus-hours'
} as const;
export type TimeCommitmentEnum = typeof TimeCommitmentEnum[keyof typeof TimeCommitmentEnum];


export function TimeCommitmentEnumFromJSON(json: any): TimeCommitmentEnum {
    return TimeCommitmentEnumFromJSONTyped(json, false);
}

export function TimeCommitmentEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeCommitmentEnum {
    return json as TimeCommitmentEnum;
}

export function TimeCommitmentEnumToJSON(value?: TimeCommitmentEnum | null): any {
    return value as any;
}

