/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `topic` - Topic
 * @export
 */
export const TopicChannelTypeEnum = {
  Topic: "topic",
} as const
export type TopicChannelTypeEnum =
  (typeof TopicChannelTypeEnum)[keyof typeof TopicChannelTypeEnum]

export function TopicChannelTypeEnumFromJSON(json: any): TopicChannelTypeEnum {
  return TopicChannelTypeEnumFromJSONTyped(json, false)
}

export function TopicChannelTypeEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TopicChannelTypeEnum {
  return json as TopicChannelTypeEnum
}

export function TopicChannelTypeEnumToJSON(
  value?: TopicChannelTypeEnum | null,
): any {
  return value as any
}
