/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const VideoResourceResourceTypeEnum = {
  Video: "video",
} as const
export type VideoResourceResourceTypeEnum =
  (typeof VideoResourceResourceTypeEnum)[keyof typeof VideoResourceResourceTypeEnum]

export function VideoResourceResourceTypeEnumFromJSON(
  json: any,
): VideoResourceResourceTypeEnum {
  return VideoResourceResourceTypeEnumFromJSONTyped(json, false)
}

export function VideoResourceResourceTypeEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VideoResourceResourceTypeEnum {
  return json as VideoResourceResourceTypeEnum
}

export function VideoResourceResourceTypeEnumToJSON(
  value?: VideoResourceResourceTypeEnum | null,
): any {
  return value as any
}
