/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { VideoChannel } from "./VideoChannel"
import {
  VideoChannelFromJSON,
  VideoChannelFromJSONTyped,
  VideoChannelToJSON,
} from "./VideoChannel"

/**
 * Serializer for the VideoPlaylist model
 * @export
 * @interface VideoPlaylist
 */
export interface VideoPlaylist {
  /**
   *
   * @type {number}
   * @memberof VideoPlaylist
   */
  readonly id: number
  /**
   *
   * @type {VideoChannel}
   * @memberof VideoPlaylist
   */
  readonly channel: VideoChannel | null
  /**
   *
   * @type {number}
   * @memberof VideoPlaylist
   */
  videoCount: number
}

/**
 * Check if a given object implements the VideoPlaylist interface.
 */
export function instanceOfVideoPlaylist(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "channel" in value
  isInstance = isInstance && "videoCount" in value

  return isInstance
}

export function VideoPlaylistFromJSON(json: any): VideoPlaylist {
  return VideoPlaylistFromJSONTyped(json, false)
}

export function VideoPlaylistFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VideoPlaylist {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json["id"],
    channel: VideoChannelFromJSON(json["channel"]),
    videoCount: json["video_count"],
  }
}

export function VideoPlaylistToJSON(value?: VideoPlaylist | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    video_count: value.videoCount,
  }
}
