/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AvailabilityEnum } from './AvailabilityEnum';
import {
    AvailabilityEnumFromJSON,
    AvailabilityEnumFromJSONTyped,
    AvailabilityEnumToJSON,
} from './AvailabilityEnum';
import type { CourseResourceCertificationType } from './CourseResourceCertificationType';
import {
    CourseResourceCertificationTypeFromJSON,
    CourseResourceCertificationTypeFromJSONTyped,
    CourseResourceCertificationTypeToJSON,
} from './CourseResourceCertificationType';
import type { CourseResourceDeliveryInner } from './CourseResourceDeliveryInner';
import {
    CourseResourceDeliveryInnerFromJSON,
    CourseResourceDeliveryInnerFromJSONTyped,
    CourseResourceDeliveryInnerToJSON,
} from './CourseResourceDeliveryInner';
import type { CourseResourceFormatInner } from './CourseResourceFormatInner';
import {
    CourseResourceFormatInnerFromJSON,
    CourseResourceFormatInnerFromJSONTyped,
    CourseResourceFormatInnerToJSON,
} from './CourseResourceFormatInner';
import type { CourseResourcePaceInner } from './CourseResourcePaceInner';
import {
    CourseResourcePaceInnerFromJSON,
    CourseResourcePaceInnerFromJSONTyped,
    CourseResourcePaceInnerToJSON,
} from './CourseResourcePaceInner';
import type { LearningResourceDepartment } from './LearningResourceDepartment';
import {
    LearningResourceDepartmentFromJSON,
    LearningResourceDepartmentFromJSONTyped,
    LearningResourceDepartmentToJSON,
} from './LearningResourceDepartment';
import type { LearningResourceImage } from './LearningResourceImage';
import {
    LearningResourceImageFromJSON,
    LearningResourceImageFromJSONTyped,
    LearningResourceImageToJSON,
} from './LearningResourceImage';
import type { LearningResourceOfferor } from './LearningResourceOfferor';
import {
    LearningResourceOfferorFromJSON,
    LearningResourceOfferorFromJSONTyped,
    LearningResourceOfferorToJSON,
} from './LearningResourceOfferor';
import type { LearningResourcePlatform } from './LearningResourcePlatform';
import {
    LearningResourcePlatformFromJSON,
    LearningResourcePlatformFromJSONTyped,
    LearningResourcePlatformToJSON,
} from './LearningResourcePlatform';
import type { LearningResourcePrice } from './LearningResourcePrice';
import {
    LearningResourcePriceFromJSON,
    LearningResourcePriceFromJSONTyped,
    LearningResourcePriceToJSON,
} from './LearningResourcePrice';
import type { LearningResourceRelationshipChildField } from './LearningResourceRelationshipChildField';
import {
    LearningResourceRelationshipChildFieldFromJSON,
    LearningResourceRelationshipChildFieldFromJSONTyped,
    LearningResourceRelationshipChildFieldToJSON,
} from './LearningResourceRelationshipChildField';
import type { LearningResourceRun } from './LearningResourceRun';
import {
    LearningResourceRunFromJSON,
    LearningResourceRunFromJSONTyped,
    LearningResourceRunToJSON,
} from './LearningResourceRun';
import type { LearningResourceTopic } from './LearningResourceTopic';
import {
    LearningResourceTopicFromJSON,
    LearningResourceTopicFromJSONTyped,
    LearningResourceTopicToJSON,
} from './LearningResourceTopic';
import type { MicroLearningPathRelationship } from './MicroLearningPathRelationship';
import {
    MicroLearningPathRelationshipFromJSON,
    MicroLearningPathRelationshipFromJSONTyped,
    MicroLearningPathRelationshipToJSON,
} from './MicroLearningPathRelationship';
import type { MicroUserListRelationship } from './MicroUserListRelationship';
import {
    MicroUserListRelationshipFromJSON,
    MicroUserListRelationshipFromJSONTyped,
    MicroUserListRelationshipToJSON,
} from './MicroUserListRelationship';
import type { VideoPlaylist } from './VideoPlaylist';
import {
    VideoPlaylistFromJSON,
    VideoPlaylistFromJSONTyped,
    VideoPlaylistToJSON,
} from './VideoPlaylist';
import type { VideoPlaylistResourceResourceTypeEnum } from './VideoPlaylistResourceResourceTypeEnum';
import {
    VideoPlaylistResourceResourceTypeEnumFromJSON,
    VideoPlaylistResourceResourceTypeEnumFromJSONTyped,
    VideoPlaylistResourceResourceTypeEnumToJSON,
} from './VideoPlaylistResourceResourceTypeEnum';

/**
 * Serializer for video playlist resources
 * @export
 * @interface VideoPlaylistResource
 */
export interface VideoPlaylistResource {
    /**
     * 
     * @type {number}
     * @memberof VideoPlaylistResource
     */
    readonly id: number;
    /**
     * 
     * @type {Array<LearningResourceTopic>}
     * @memberof VideoPlaylistResource
     */
    topics?: Array<LearningResourceTopic>;
    /**
     * 
     * @type {number}
     * @memberof VideoPlaylistResource
     */
    readonly position: number | null;
    /**
     * 
     * @type {LearningResourceOfferor}
     * @memberof VideoPlaylistResource
     */
    readonly offeredBy: LearningResourceOfferor | null;
    /**
     * 
     * @type {LearningResourcePlatform}
     * @memberof VideoPlaylistResource
     */
    readonly platform: LearningResourcePlatform | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof VideoPlaylistResource
     */
    readonly courseFeature: Array<string> | null;
    /**
     * 
     * @type {Array<LearningResourceDepartment>}
     * @memberof VideoPlaylistResource
     */
    readonly departments: Array<LearningResourceDepartment> | null;
    /**
     * 
     * @type {boolean}
     * @memberof VideoPlaylistResource
     */
    readonly certification: boolean;
    /**
     * 
     * @type {CourseResourceCertificationType}
     * @memberof VideoPlaylistResource
     */
    certificationType: CourseResourceCertificationType;
    /**
     * 
     * @type {Array<string>}
     * @memberof VideoPlaylistResource
     */
    readonly prices: Array<string>;
    /**
     * 
     * @type {Array<LearningResourcePrice>}
     * @memberof VideoPlaylistResource
     */
    readonly resourcePrices: Array<LearningResourcePrice>;
    /**
     * 
     * @type {Array<LearningResourceRun>}
     * @memberof VideoPlaylistResource
     */
    readonly runs: Array<LearningResourceRun> | null;
    /**
     * 
     * @type {LearningResourceImage}
     * @memberof VideoPlaylistResource
     */
    readonly image: LearningResourceImage | null;
    /**
     * 
     * @type {Array<MicroLearningPathRelationship>}
     * @memberof VideoPlaylistResource
     */
    readonly learningPathParents: Array<MicroLearningPathRelationship>;
    /**
     * 
     * @type {Array<MicroUserListRelationship>}
     * @memberof VideoPlaylistResource
     */
    readonly userListParents: Array<MicroUserListRelationship>;
    /**
     * 
     * @type {number}
     * @memberof VideoPlaylistResource
     */
    readonly views: number;
    /**
     * 
     * @type {Array<CourseResourceDeliveryInner>}
     * @memberof VideoPlaylistResource
     */
    readonly delivery: Array<CourseResourceDeliveryInner>;
    /**
     * Return true if the resource is free/has a free option
     * @type {boolean}
     * @memberof VideoPlaylistResource
     */
    readonly free: boolean;
    /**
     * Return the resource category of the resource
     * @type {string}
     * @memberof VideoPlaylistResource
     */
    readonly resourceCategory: string;
    /**
     * 
     * @type {Array<CourseResourceFormatInner>}
     * @memberof VideoPlaylistResource
     */
    readonly format: Array<CourseResourceFormatInner>;
    /**
     * 
     * @type {Array<CourseResourcePaceInner>}
     * @memberof VideoPlaylistResource
     */
    readonly pace: Array<CourseResourcePaceInner>;
    /**
     * 
     * @type {LearningResourceRelationshipChildField}
     * @memberof VideoPlaylistResource
     */
    readonly children: LearningResourceRelationshipChildField | null;
    /**
     * 
     * @type {VideoPlaylistResourceResourceTypeEnum}
     * @memberof VideoPlaylistResource
     */
    readonly resourceType: VideoPlaylistResourceResourceTypeEnum;
    /**
     * 
     * @type {VideoPlaylist}
     * @memberof VideoPlaylistResource
     */
    readonly videoPlaylist: VideoPlaylist;
    /**
     * 
     * @type {string}
     * @memberof VideoPlaylistResource
     */
    readableId: string;
    /**
     * 
     * @type {string}
     * @memberof VideoPlaylistResource
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof VideoPlaylistResource
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoPlaylistResource
     */
    fullDescription?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof VideoPlaylistResource
     */
    lastModified?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof VideoPlaylistResource
     */
    published?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof VideoPlaylistResource
     */
    languages?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof VideoPlaylistResource
     */
    url?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof VideoPlaylistResource
     */
    ocwTopics?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof VideoPlaylistResource
     */
    readonly professional: boolean;
    /**
     * 
     * @type {Date}
     * @memberof VideoPlaylistResource
     */
    nextStartDate?: Date | null;
    /**
     * 
     * @type {AvailabilityEnum}
     * @memberof VideoPlaylistResource
     */
    availability?: AvailabilityEnum | null;
    /**
     * 
     * @type {number}
     * @memberof VideoPlaylistResource
     */
    completeness?: number;
    /**
     * 
     * @type {boolean}
     * @memberof VideoPlaylistResource
     */
    licenseCc?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VideoPlaylistResource
     */
    testMode?: boolean;
    /**
     * 
     * @type {string}
     * @memberof VideoPlaylistResource
     */
    continuingEdCredits?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoPlaylistResource
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoPlaylistResource
     */
    duration?: string;
    /**
     * 
     * @type {number}
     * @memberof VideoPlaylistResource
     */
    minWeeks?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VideoPlaylistResource
     */
    maxWeeks?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VideoPlaylistResource
     */
    timeCommitment?: string;
    /**
     * 
     * @type {number}
     * @memberof VideoPlaylistResource
     */
    minWeeklyHours?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VideoPlaylistResource
     */
    maxWeeklyHours?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof VideoPlaylistResource
     */
    readonly requireSummaries: boolean;
}

/**
 * Check if a given object implements the VideoPlaylistResource interface.
 */
export function instanceOfVideoPlaylistResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "position" in value;
    isInstance = isInstance && "offeredBy" in value;
    isInstance = isInstance && "platform" in value;
    isInstance = isInstance && "courseFeature" in value;
    isInstance = isInstance && "departments" in value;
    isInstance = isInstance && "certification" in value;
    isInstance = isInstance && "certificationType" in value;
    isInstance = isInstance && "prices" in value;
    isInstance = isInstance && "resourcePrices" in value;
    isInstance = isInstance && "runs" in value;
    isInstance = isInstance && "image" in value;
    isInstance = isInstance && "learningPathParents" in value;
    isInstance = isInstance && "userListParents" in value;
    isInstance = isInstance && "views" in value;
    isInstance = isInstance && "delivery" in value;
    isInstance = isInstance && "free" in value;
    isInstance = isInstance && "resourceCategory" in value;
    isInstance = isInstance && "format" in value;
    isInstance = isInstance && "pace" in value;
    isInstance = isInstance && "children" in value;
    isInstance = isInstance && "resourceType" in value;
    isInstance = isInstance && "videoPlaylist" in value;
    isInstance = isInstance && "readableId" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "professional" in value;
    isInstance = isInstance && "requireSummaries" in value;

    return isInstance;
}

export function VideoPlaylistResourceFromJSON(json: any): VideoPlaylistResource {
    return VideoPlaylistResourceFromJSONTyped(json, false);
}

export function VideoPlaylistResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoPlaylistResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'topics': !exists(json, 'topics') ? undefined : ((json['topics'] as Array<any>).map(LearningResourceTopicFromJSON)),
        'position': json['position'],
        'offeredBy': LearningResourceOfferorFromJSON(json['offered_by']),
        'platform': LearningResourcePlatformFromJSON(json['platform']),
        'courseFeature': json['course_feature'],
        'departments': (json['departments'] === null ? null : (json['departments'] as Array<any>).map(LearningResourceDepartmentFromJSON)),
        'certification': json['certification'],
        'certificationType': CourseResourceCertificationTypeFromJSON(json['certification_type']),
        'prices': json['prices'],
        'resourcePrices': ((json['resource_prices'] as Array<any>).map(LearningResourcePriceFromJSON)),
        'runs': (json['runs'] === null ? null : (json['runs'] as Array<any>).map(LearningResourceRunFromJSON)),
        'image': LearningResourceImageFromJSON(json['image']),
        'learningPathParents': ((json['learning_path_parents'] as Array<any>).map(MicroLearningPathRelationshipFromJSON)),
        'userListParents': ((json['user_list_parents'] as Array<any>).map(MicroUserListRelationshipFromJSON)),
        'views': json['views'],
        'delivery': ((json['delivery'] as Array<any>).map(CourseResourceDeliveryInnerFromJSON)),
        'free': json['free'],
        'resourceCategory': json['resource_category'],
        'format': ((json['format'] as Array<any>).map(CourseResourceFormatInnerFromJSON)),
        'pace': ((json['pace'] as Array<any>).map(CourseResourcePaceInnerFromJSON)),
        'children': LearningResourceRelationshipChildFieldFromJSON(json['children']),
        'resourceType': VideoPlaylistResourceResourceTypeEnumFromJSON(json['resource_type']),
        'videoPlaylist': VideoPlaylistFromJSON(json['video_playlist']),
        'readableId': json['readable_id'],
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'fullDescription': !exists(json, 'full_description') ? undefined : json['full_description'],
        'lastModified': !exists(json, 'last_modified') ? undefined : (json['last_modified'] === null ? null : new Date(json['last_modified'])),
        'published': !exists(json, 'published') ? undefined : json['published'],
        'languages': !exists(json, 'languages') ? undefined : json['languages'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'ocwTopics': !exists(json, 'ocw_topics') ? undefined : json['ocw_topics'],
        'professional': json['professional'],
        'nextStartDate': !exists(json, 'next_start_date') ? undefined : (json['next_start_date'] === null ? null : new Date(json['next_start_date'])),
        'availability': !exists(json, 'availability') ? undefined : AvailabilityEnumFromJSON(json['availability']),
        'completeness': !exists(json, 'completeness') ? undefined : json['completeness'],
        'licenseCc': !exists(json, 'license_cc') ? undefined : json['license_cc'],
        'testMode': !exists(json, 'test_mode') ? undefined : json['test_mode'],
        'continuingEdCredits': !exists(json, 'continuing_ed_credits') ? undefined : json['continuing_ed_credits'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'minWeeks': !exists(json, 'min_weeks') ? undefined : json['min_weeks'],
        'maxWeeks': !exists(json, 'max_weeks') ? undefined : json['max_weeks'],
        'timeCommitment': !exists(json, 'time_commitment') ? undefined : json['time_commitment'],
        'minWeeklyHours': !exists(json, 'min_weekly_hours') ? undefined : json['min_weekly_hours'],
        'maxWeeklyHours': !exists(json, 'max_weekly_hours') ? undefined : json['max_weekly_hours'],
        'requireSummaries': json['require_summaries'],
    };
}

export function VideoPlaylistResourceToJSON(value?: VideoPlaylistResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topics': value.topics === undefined ? undefined : ((value.topics as Array<any>).map(LearningResourceTopicToJSON)),
        'certification_type': CourseResourceCertificationTypeToJSON(value.certificationType),
        'readable_id': value.readableId,
        'title': value.title,
        'description': value.description,
        'full_description': value.fullDescription,
        'last_modified': value.lastModified === undefined ? undefined : (value.lastModified === null ? null : value.lastModified.toISOString()),
        'published': value.published,
        'languages': value.languages,
        'url': value.url,
        'ocw_topics': value.ocwTopics,
        'next_start_date': value.nextStartDate === undefined ? undefined : (value.nextStartDate === null ? null : value.nextStartDate.toISOString()),
        'availability': AvailabilityEnumToJSON(value.availability),
        'completeness': value.completeness,
        'license_cc': value.licenseCc,
        'test_mode': value.testMode,
        'continuing_ed_credits': value.continuingEdCredits,
        'location': value.location,
        'duration': value.duration,
        'min_weeks': value.minWeeks,
        'max_weeks': value.maxWeeks,
        'time_commitment': value.timeCommitment,
        'min_weekly_hours': value.minWeeklyHours,
        'max_weekly_hours': value.maxWeeklyHours,
    };
}

