/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { WidgetInstance } from "./WidgetInstance"
import {
  WidgetInstanceFromJSON,
  WidgetInstanceFromJSONTyped,
  WidgetInstanceToJSON,
} from "./WidgetInstance"

/**
 * Serializer for WidgetLists
 * @export
 * @interface WidgetListRequest
 */
export interface WidgetListRequest {
  /**
   *
   * @type {Array<WidgetInstance>}
   * @memberof WidgetListRequest
   */
  widgets?: Array<WidgetInstance> | null
}

/**
 * Check if a given object implements the WidgetListRequest interface.
 */
export function instanceOfWidgetListRequest(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function WidgetListRequestFromJSON(json: any): WidgetListRequest {
  return WidgetListRequestFromJSONTyped(json, false)
}

export function WidgetListRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WidgetListRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    widgets: !exists(json, "widgets")
      ? undefined
      : json["widgets"] === null
        ? null
        : (json["widgets"] as Array<any>).map(WidgetInstanceFromJSON),
  }
}

export function WidgetListRequestToJSON(value?: WidgetListRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    widgets:
      value.widgets === undefined
        ? undefined
        : value.widgets === null
          ? null
          : (value.widgets as Array<any>).map(WidgetInstanceToJSON),
  }
}
