/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime"
import type { ProgramCertificate } from "../models/index"
import {
  ProgramCertificateFromJSON,
  ProgramCertificateToJSON,
} from "../models/index"

export interface ProgramCertificatesListRequest {
  micromasters_program_id?: number
  program_title?: string
}

/**
 *
 */
export class ProgramCertificatesApi extends runtime.BaseAPI {
  /**
   * View for listing program certificates for a user (includes program letter links)
   */
  async programCertificatesListRaw(
    requestParameters: ProgramCertificatesListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ProgramCertificate>>> {
    const queryParameters: any = {}

    if (requestParameters.micromasters_program_id !== undefined) {
      queryParameters["micromasters_program_id"] =
        requestParameters.micromasters_program_id
    }

    if (requestParameters.program_title !== undefined) {
      queryParameters["program_title"] = requestParameters.program_title
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/v0/program_certificates/`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ProgramCertificateFromJSON),
    )
  }

  /**
   * View for listing program certificates for a user (includes program letter links)
   */
  async programCertificatesList(
    requestParameters: ProgramCertificatesListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ProgramCertificate>> {
    const response = await this.programCertificatesListRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }
}
