/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v0)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LearningResourcesVectorSearchResponse,
} from '../models/index';
import {
    LearningResourcesVectorSearchResponseFromJSON,
    LearningResourcesVectorSearchResponseToJSON,
} from '../models/index';

export interface VectorLearningResourcesSearchRetrieveRequest {
    certification?: boolean | null;
    certification_type?: Array<VectorLearningResourcesSearchRetrieveCertificationTypeEnum>;
    course_feature?: Array<string>;
    delivery?: Array<VectorLearningResourcesSearchRetrieveDeliveryEnum>;
    department?: Array<VectorLearningResourcesSearchRetrieveDepartmentEnum>;
    free?: boolean | null;
    level?: Array<VectorLearningResourcesSearchRetrieveLevelEnum>;
    limit?: number;
    ocw_topic?: Array<string>;
    offered_by?: Array<VectorLearningResourcesSearchRetrieveOfferedByEnum>;
    offset?: number;
    platform?: Array<VectorLearningResourcesSearchRetrievePlatformEnum>;
    professional?: boolean | null;
    q?: string;
    readable_id?: string;
    resource_category?: Array<VectorLearningResourcesSearchRetrieveResourceCategoryEnum>;
    resource_type?: Array<VectorLearningResourcesSearchRetrieveResourceTypeEnum>;
    topic?: Array<string>;
}

/**
 * 
 */
export class VectorLearningResourcesSearchApi extends runtime.BaseAPI {

    /**
     * Vector Search for learning resources
     * Vector Search
     */
    async vectorLearningResourcesSearchRetrieveRaw(requestParameters: VectorLearningResourcesSearchRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LearningResourcesVectorSearchResponse>> {
        const queryParameters: any = {};

        if (requestParameters.certification !== undefined) {
            queryParameters['certification'] = requestParameters.certification;
        }

        if (requestParameters.certification_type) {
            queryParameters['certification_type'] = requestParameters.certification_type;
        }

        if (requestParameters.course_feature) {
            queryParameters['course_feature'] = requestParameters.course_feature;
        }

        if (requestParameters.delivery) {
            queryParameters['delivery'] = requestParameters.delivery;
        }

        if (requestParameters.department) {
            queryParameters['department'] = requestParameters.department;
        }

        if (requestParameters.free !== undefined) {
            queryParameters['free'] = requestParameters.free;
        }

        if (requestParameters.level) {
            queryParameters['level'] = requestParameters.level;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.ocw_topic) {
            queryParameters['ocw_topic'] = requestParameters.ocw_topic;
        }

        if (requestParameters.offered_by) {
            queryParameters['offered_by'] = requestParameters.offered_by;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.platform) {
            queryParameters['platform'] = requestParameters.platform;
        }

        if (requestParameters.professional !== undefined) {
            queryParameters['professional'] = requestParameters.professional;
        }

        if (requestParameters.q !== undefined) {
            queryParameters['q'] = requestParameters.q;
        }

        if (requestParameters.readable_id !== undefined) {
            queryParameters['readable_id'] = requestParameters.readable_id;
        }

        if (requestParameters.resource_category) {
            queryParameters['resource_category'] = requestParameters.resource_category;
        }

        if (requestParameters.resource_type) {
            queryParameters['resource_type'] = requestParameters.resource_type;
        }

        if (requestParameters.topic) {
            queryParameters['topic'] = requestParameters.topic;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v0/vector_learning_resources_search/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LearningResourcesVectorSearchResponseFromJSON(jsonValue));
    }

    /**
     * Vector Search for learning resources
     * Vector Search
     */
    async vectorLearningResourcesSearchRetrieve(requestParameters: VectorLearningResourcesSearchRetrieveRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LearningResourcesVectorSearchResponse> {
        const response = await this.vectorLearningResourcesSearchRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const VectorLearningResourcesSearchRetrieveCertificationTypeEnum = {
    Micromasters: 'micromasters',
    Professional: 'professional',
    Completion: 'completion',
    None: 'none'
} as const;
export type VectorLearningResourcesSearchRetrieveCertificationTypeEnum = typeof VectorLearningResourcesSearchRetrieveCertificationTypeEnum[keyof typeof VectorLearningResourcesSearchRetrieveCertificationTypeEnum];
/**
 * @export
 */
export const VectorLearningResourcesSearchRetrieveDeliveryEnum = {
    Online: 'online',
    Hybrid: 'hybrid',
    InPerson: 'in_person',
    Offline: 'offline'
} as const;
export type VectorLearningResourcesSearchRetrieveDeliveryEnum = typeof VectorLearningResourcesSearchRetrieveDeliveryEnum[keyof typeof VectorLearningResourcesSearchRetrieveDeliveryEnum];
/**
 * @export
 */
export const VectorLearningResourcesSearchRetrieveDepartmentEnum = {
    _1: '1',
    _2: '2',
    _3: '3',
    _4: '4',
    _5: '5',
    _6: '6',
    _7: '7',
    _8: '8',
    _9: '9',
    _10: '10',
    _11: '11',
    _12: '12',
    _14: '14',
    _15: '15',
    _16: '16',
    _17: '17',
    _18: '18',
    _20: '20',
    _21A: '21A',
    _21G: '21G',
    _21H: '21H',
    _21L: '21L',
    _21M: '21M',
    _22: '22',
    _24: '24',
    Cc: 'CC',
    CmsW: 'CMS-W',
    Ec: 'EC',
    Es: 'ES',
    Esd: 'ESD',
    Hst: 'HST',
    Ids: 'IDS',
    Mas: 'MAS',
    Pe: 'PE',
    Sp: 'SP',
    Sts: 'STS',
    Wgs: 'WGS'
} as const;
export type VectorLearningResourcesSearchRetrieveDepartmentEnum = typeof VectorLearningResourcesSearchRetrieveDepartmentEnum[keyof typeof VectorLearningResourcesSearchRetrieveDepartmentEnum];
/**
 * @export
 */
export const VectorLearningResourcesSearchRetrieveLevelEnum = {
    Undergraduate: 'undergraduate',
    Graduate: 'graduate',
    HighSchool: 'high_school',
    Noncredit: 'noncredit',
    Advanced: 'advanced',
    Intermediate: 'intermediate',
    Introductory: 'introductory'
} as const;
export type VectorLearningResourcesSearchRetrieveLevelEnum = typeof VectorLearningResourcesSearchRetrieveLevelEnum[keyof typeof VectorLearningResourcesSearchRetrieveLevelEnum];
/**
 * @export
 */
export const VectorLearningResourcesSearchRetrieveOfferedByEnum = {
    Mitx: 'mitx',
    Ocw: 'ocw',
    Bootcamps: 'bootcamps',
    Xpro: 'xpro',
    Mitpe: 'mitpe',
    See: 'see'
} as const;
export type VectorLearningResourcesSearchRetrieveOfferedByEnum = typeof VectorLearningResourcesSearchRetrieveOfferedByEnum[keyof typeof VectorLearningResourcesSearchRetrieveOfferedByEnum];
/**
 * @export
 */
export const VectorLearningResourcesSearchRetrievePlatformEnum = {
    Edx: 'edx',
    Ocw: 'ocw',
    Oll: 'oll',
    Mitxonline: 'mitxonline',
    Bootcamps: 'bootcamps',
    Xpro: 'xpro',
    Csail: 'csail',
    Mitpe: 'mitpe',
    See: 'see',
    Scc: 'scc',
    Ctl: 'ctl',
    Whu: 'whu',
    Susskind: 'susskind',
    Globalalumni: 'globalalumni',
    Simplilearn: 'simplilearn',
    Emeritus: 'emeritus',
    Podcast: 'podcast',
    Youtube: 'youtube',
    Canvas: 'canvas'
} as const;
export type VectorLearningResourcesSearchRetrievePlatformEnum = typeof VectorLearningResourcesSearchRetrievePlatformEnum[keyof typeof VectorLearningResourcesSearchRetrievePlatformEnum];
/**
 * @export
 */
export const VectorLearningResourcesSearchRetrieveResourceCategoryEnum = {
    Course: 'course',
    Program: 'program',
    LearningMaterial: 'learning_material'
} as const;
export type VectorLearningResourcesSearchRetrieveResourceCategoryEnum = typeof VectorLearningResourcesSearchRetrieveResourceCategoryEnum[keyof typeof VectorLearningResourcesSearchRetrieveResourceCategoryEnum];
/**
 * @export
 */
export const VectorLearningResourcesSearchRetrieveResourceTypeEnum = {
    Course: 'course',
    Program: 'program',
    LearningPath: 'learning_path',
    Podcast: 'podcast',
    PodcastEpisode: 'podcast_episode',
    Video: 'video',
    VideoPlaylist: 'video_playlist'
} as const;
export type VectorLearningResourcesSearchRetrieveResourceTypeEnum = typeof VectorLearningResourcesSearchRetrieveResourceTypeEnum[keyof typeof VectorLearningResourcesSearchRetrieveResourceTypeEnum];
