/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for LearningResourceInstructor model
 * @export
 * @interface ArticleRequest
 */
export interface ArticleRequest {
    /**
     * 
     * @type {string}
     * @memberof ArticleRequest
     */
    html: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleRequest
     */
    title: string;
}

/**
 * Check if a given object implements the ArticleRequest interface.
 */
export function instanceOfArticleRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "html" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function ArticleRequestFromJSON(json: any): ArticleRequest {
    return ArticleRequestFromJSONTyped(json, false);
}

export function ArticleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'html': json['html'],
        'title': json['title'],
    };
}

export function ArticleRequestToJSON(value?: ArticleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'html': value.html,
        'title': value.title,
    };
}

