/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 * Serializer for LearningResourceInstructor model
 * @export
 * @interface Article
 */
export interface Article {
  /**
   *
   * @type {string}
   * @memberof Article
   */
  html: string
  /**
   *
   * @type {number}
   * @memberof Article
   */
  readonly id: number
  /**
   *
   * @type {string}
   * @memberof Article
   */
  title: string
}

/**
 * Check if a given object implements the Article interface.
 */
export function instanceOfArticle(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "html" in value
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "title" in value

  return isInstance
}

export function ArticleFromJSON(json: any): Article {
  return ArticleFromJSONTyped(json, false)
}

export function ArticleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Article {
  if (json === undefined || json === null) {
    return json
  }
  return {
    html: json["html"],
    id: json["id"],
    title: json["title"],
  }
}

export function ArticleToJSON(value?: Article | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    html: value.html,
    title: value.title,
  }
}
