/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `dated` - Dated
 * * `anytime` - Anytime
 * @export
 */
export const AvailabilityEnum = {
    Dated: 'dated',
    Anytime: 'anytime'
} as const;
export type AvailabilityEnum = typeof AvailabilityEnum[keyof typeof AvailabilityEnum];


export function AvailabilityEnumFromJSON(json: any): AvailabilityEnum {
    return AvailabilityEnumFromJSONTyped(json, false);
}

export function AvailabilityEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvailabilityEnum {
    return json as AvailabilityEnum;
}

export function AvailabilityEnumToJSON(value?: AvailabilityEnum | null): any {
    return value as any;
}

