/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentFile } from './ContentFile';
import {
    ContentFileFromJSON,
    ContentFileFromJSONTyped,
    ContentFileToJSON,
} from './ContentFile';
import type { ContentFileSearchResponseMetadata } from './ContentFileSearchResponseMetadata';
import {
    ContentFileSearchResponseMetadataFromJSON,
    ContentFileSearchResponseMetadataFromJSONTyped,
    ContentFileSearchResponseMetadataToJSON,
} from './ContentFileSearchResponseMetadata';

/**
 * SearchResponseSerializer with OpenAPI annotations for Content Files search
 * @export
 * @interface ContentFileSearchResponse
 */
export interface ContentFileSearchResponse {
    /**
     * 
     * @type {number}
     * @memberof ContentFileSearchResponse
     */
    readonly count: number;
    /**
     * 
     * @type {string}
     * @memberof ContentFileSearchResponse
     */
    readonly next: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentFileSearchResponse
     */
    readonly previous: string | null;
    /**
     * 
     * @type {Array<ContentFile>}
     * @memberof ContentFileSearchResponse
     */
    readonly results: Array<ContentFile>;
    /**
     * 
     * @type {ContentFileSearchResponseMetadata}
     * @memberof ContentFileSearchResponse
     */
    metadata: ContentFileSearchResponseMetadata;
}

/**
 * Check if a given object implements the ContentFileSearchResponse interface.
 */
export function instanceOfContentFileSearchResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "next" in value;
    isInstance = isInstance && "previous" in value;
    isInstance = isInstance && "results" in value;
    isInstance = isInstance && "metadata" in value;

    return isInstance;
}

export function ContentFileSearchResponseFromJSON(json: any): ContentFileSearchResponse {
    return ContentFileSearchResponseFromJSONTyped(json, false);
}

export function ContentFileSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentFileSearchResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'results': ((json['results'] as Array<any>).map(ContentFileFromJSON)),
        'metadata': ContentFileSearchResponseMetadataFromJSON(json['metadata']),
    };
}

export function ContentFileSearchResponseToJSON(value?: ContentFileSearchResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ContentFileSearchResponseMetadataToJSON(value.metadata),
    };
}

