/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SourceEnum } from './SourceEnum';
import {
    SourceEnumFromJSON,
    SourceEnumFromJSONTyped,
    SourceEnumToJSON,
} from './SourceEnum';

/**
 * Serializer for ContentFile webhook requests.
 * @export
 * @interface ContentFileWebHookRequest
 */
export interface ContentFileWebHookRequest {
    /**
     * 
     * @type {string}
     * @memberof ContentFileWebHookRequest
     */
    contentPath?: string;
    /**
     * 
     * @type {SourceEnum}
     * @memberof ContentFileWebHookRequest
     */
    source: SourceEnum;
    /**
     * 
     * @type {string}
     * @memberof ContentFileWebHookRequest
     */
    courseId?: string;
}

/**
 * Check if a given object implements the ContentFileWebHookRequest interface.
 */
export function instanceOfContentFileWebHookRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "source" in value;

    return isInstance;
}

export function ContentFileWebHookRequestFromJSON(json: any): ContentFileWebHookRequest {
    return ContentFileWebHookRequestFromJSONTyped(json, false);
}

export function ContentFileWebHookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentFileWebHookRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contentPath': !exists(json, 'content_path') ? undefined : json['content_path'],
        'source': SourceEnumFromJSON(json['source']),
        'courseId': !exists(json, 'course_id') ? undefined : json['course_id'],
    };
}

export function ContentFileWebHookRequestToJSON(value?: ContentFileWebHookRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content_path': value.contentPath,
        'source': SourceEnumToJSON(value.source),
        'course_id': value.courseId,
    };
}

