/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { ContentFileSearchResponseMetadataAggregationsValueInner } from "./ContentFileSearchResponseMetadataAggregationsValueInner"
import {
  ContentFileSearchResponseMetadataAggregationsValueInnerFromJSON,
  ContentFileSearchResponseMetadataAggregationsValueInnerFromJSONTyped,
  ContentFileSearchResponseMetadataAggregationsValueInnerToJSON,
} from "./ContentFileSearchResponseMetadataAggregationsValueInner"

/**
 *
 * @export
 * @interface ContentFileSearchResponseMetadata
 */
export interface ContentFileSearchResponseMetadata {
  /**
   *
   * @type {{ [key: string]: Array<ContentFileSearchResponseMetadataAggregationsValueInner>; }}
   * @memberof ContentFileSearchResponseMetadata
   */
  aggregations: {
    [
      key: string
    ]: Array<ContentFileSearchResponseMetadataAggregationsValueInner>
  }
  /**
   *
   * @type {Array<string>}
   * @memberof ContentFileSearchResponseMetadata
   */
  suggestions: Array<string>
}

/**
 * Check if a given object implements the ContentFileSearchResponseMetadata interface.
 */
export function instanceOfContentFileSearchResponseMetadata(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "aggregations" in value
  isInstance = isInstance && "suggestions" in value

  return isInstance
}

export function ContentFileSearchResponseMetadataFromJSON(
  json: any,
): ContentFileSearchResponseMetadata {
  return ContentFileSearchResponseMetadataFromJSONTyped(json, false)
}

export function ContentFileSearchResponseMetadataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ContentFileSearchResponseMetadata {
  if (json === undefined || json === null) {
    return json
  }
  return {
    aggregations: json["aggregations"],
    suggestions: json["suggestions"],
  }
}

export function ContentFileSearchResponseMetadataToJSON(
  value?: ContentFileSearchResponseMetadata | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    aggregations: value.aggregations,
    suggestions: value.suggestions,
  }
}
