/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { LearningResourceDepartment } from "./LearningResourceDepartment"
import {
  LearningResourceDepartmentFromJSON,
  LearningResourceDepartmentFromJSONTyped,
  LearningResourceDepartmentToJSON,
} from "./LearningResourceDepartment"

/**
 * Serializer for CourseNumber
 * @export
 * @interface CourseNumber
 */
export interface CourseNumber {
  /**
   *
   * @type {string}
   * @memberof CourseNumber
   */
  value: string
  /**
   *
   * @type {LearningResourceDepartment}
   * @memberof CourseNumber
   */
  department: LearningResourceDepartment
  /**
   *
   * @type {string}
   * @memberof CourseNumber
   */
  listingType: string
}

/**
 * Check if a given object implements the CourseNumber interface.
 */
export function instanceOfCourseNumber(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "value" in value
  isInstance = isInstance && "department" in value
  isInstance = isInstance && "listingType" in value

  return isInstance
}

export function CourseNumberFromJSON(json: any): CourseNumber {
  return CourseNumberFromJSONTyped(json, false)
}

export function CourseNumberFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CourseNumber {
  if (json === undefined || json === null) {
    return json
  }
  return {
    value: json["value"],
    department: LearningResourceDepartmentFromJSON(json["department"]),
    listingType: json["listing_type"],
  }
}

export function CourseNumberToJSON(value?: CourseNumber | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    value: value.value,
    department: LearningResourceDepartmentToJSON(value.department),
    listing_type: value.listingType,
  }
}
