/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseResourceCertificationType
 */
export interface CourseResourceCertificationType {
    /**
     * 
     * @type {string}
     * @memberof CourseResourceCertificationType
     */
    code: CourseResourceCertificationTypeCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof CourseResourceCertificationType
     */
    name: string;
}


/**
 * @export
 */
export const CourseResourceCertificationTypeCodeEnum = {
    Micromasters: 'micromasters',
    Professional: 'professional',
    Completion: 'completion',
    None: 'none'
} as const;
export type CourseResourceCertificationTypeCodeEnum = typeof CourseResourceCertificationTypeCodeEnum[keyof typeof CourseResourceCertificationTypeCodeEnum];


/**
 * Check if a given object implements the CourseResourceCertificationType interface.
 */
export function instanceOfCourseResourceCertificationType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CourseResourceCertificationTypeFromJSON(json: any): CourseResourceCertificationType {
    return CourseResourceCertificationTypeFromJSONTyped(json, false);
}

export function CourseResourceCertificationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseResourceCertificationType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
    };
}

export function CourseResourceCertificationTypeToJSON(value?: CourseResourceCertificationType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'name': value.name,
    };
}

