/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LearningResourceDepartmentRequest } from './LearningResourceDepartmentRequest';
import {
    LearningResourceDepartmentRequestFromJSON,
    LearningResourceDepartmentRequestFromJSONTyped,
    LearningResourceDepartmentRequestToJSON,
} from './LearningResourceDepartmentRequest';

/**
 * Serializer for CourseNumber
 * @export
 * @interface CourseNumberRequest
 */
export interface CourseNumberRequest {
    /**
     * 
     * @type {string}
     * @memberof CourseNumberRequest
     */
    value: string;
    /**
     * 
     * @type {LearningResourceDepartmentRequest}
     * @memberof CourseNumberRequest
     */
    department: LearningResourceDepartmentRequest;
    /**
     * 
     * @type {string}
     * @memberof CourseNumberRequest
     */
    listingType: string;
}

/**
 * Check if a given object implements the CourseNumberRequest interface.
 */
export function instanceOfCourseNumberRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "department" in value;
    isInstance = isInstance && "listingType" in value;

    return isInstance;
}

export function CourseNumberRequestFromJSON(json: any): CourseNumberRequest {
    return CourseNumberRequestFromJSONTyped(json, false);
}

export function CourseNumberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseNumberRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
        'department': LearningResourceDepartmentRequestFromJSON(json['department']),
        'listingType': json['listing_type'],
    };
}

export function CourseNumberRequestToJSON(value?: CourseNumberRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'department': LearningResourceDepartmentRequestToJSON(value.department),
        'listing_type': value.listingType,
    };
}

