/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CourseNumberRequest } from './CourseNumberRequest';
import {
    CourseNumberRequestFromJSON,
    CourseNumberRequestFromJSONTyped,
    CourseNumberRequestToJSON,
} from './CourseNumberRequest';

/**
 * Serializer for the Course model
 * @export
 * @interface CourseRequest
 */
export interface CourseRequest {
    /**
     * 
     * @type {Array<CourseNumberRequest>}
     * @memberof CourseRequest
     */
    courseNumbers: Array<CourseNumberRequest> | null;
}

/**
 * Check if a given object implements the CourseRequest interface.
 */
export function instanceOfCourseRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "courseNumbers" in value;

    return isInstance;
}

export function CourseRequestFromJSON(json: any): CourseRequest {
    return CourseRequestFromJSONTyped(json, false);
}

export function CourseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courseNumbers': (json['course_numbers'] === null ? null : (json['course_numbers'] as Array<any>).map(CourseNumberRequestFromJSON)),
    };
}

export function CourseRequestToJSON(value?: CourseRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'course_numbers': (value.courseNumbers === null ? null : (value.courseNumbers as Array<any>).map(CourseNumberRequestToJSON)),
    };
}

