/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `1` - Civil and Environmental Engineering
 * * `2` - Mechanical Engineering
 * * `3` - Materials Science and Engineering
 * * `4` - Architecture
 * * `5` - Chemistry
 * * `6` - Electrical Engineering and Computer Science
 * * `7` - Biology
 * * `8` - Physics
 * * `9` - Brain and Cognitive Sciences
 * * `10` - Chemical Engineering
 * * `11` - Urban Studies and Planning
 * * `12` - Earth, Atmospheric, and Planetary Sciences
 * * `14` - Economics
 * * `15` - Management
 * * `16` - Aeronautics and Astronautics
 * * `17` - Political Science
 * * `18` - Mathematics
 * * `20` - Biological Engineering
 * * `21A` - Anthropology
 * * `21G` - Global Languages
 * * `21H` - History
 * * `21L` - Literature
 * * `21M` - Music and Theater Arts
 * * `22` - Nuclear Science and Engineering
 * * `24` - Linguistics and Philosophy
 * * `CC` - Concourse
 * * `CMS-W` - Comparative Media Studies/Writing
 * * `EC` - Edgerton Center
 * * `ES` - Experimental Study Group
 * * `ESD` - Engineering Systems Division
 * * `HST` - Medical Engineering and Science
 * * `IDS` - Data, Systems, and Society
 * * `MAS` - Media Arts and Sciences
 * * `PE` - Athletics, Physical Education and Recreation
 * * `SP` - Special Programs
 * * `STS` - Science, Technology, and Society
 * * `WGS` - Women's and Gender Studies
 * @export
 */
export const DepartmentEnum = {
  _1: "1",
  _2: "2",
  _3: "3",
  _4: "4",
  _5: "5",
  _6: "6",
  _7: "7",
  _8: "8",
  _9: "9",
  _10: "10",
  _11: "11",
  _12: "12",
  _14: "14",
  _15: "15",
  _16: "16",
  _17: "17",
  _18: "18",
  _20: "20",
  _21A: "21A",
  _21G: "21G",
  _21H: "21H",
  _21L: "21L",
  _21M: "21M",
  _22: "22",
  _24: "24",
  Cc: "CC",
  CmsW: "CMS-W",
  Ec: "EC",
  Es: "ES",
  Esd: "ESD",
  Hst: "HST",
  Ids: "IDS",
  Mas: "MAS",
  Pe: "PE",
  Sp: "SP",
  Sts: "STS",
  Wgs: "WGS",
} as const
export type DepartmentEnum =
  (typeof DepartmentEnum)[keyof typeof DepartmentEnum]

export function DepartmentEnumFromJSON(json: any): DepartmentEnum {
  return DepartmentEnumFromJSONTyped(json, false)
}

export function DepartmentEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DepartmentEnum {
  return json as DepartmentEnum
}

export function DepartmentEnumToJSON(value?: DepartmentEnum | null): any {
  return value as any
}
