/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentFileSearchResponseMetadata } from './ContentFileSearchResponseMetadata';
import {
    ContentFileSearchResponseMetadataFromJSON,
    ContentFileSearchResponseMetadataFromJSONTyped,
    ContentFileSearchResponseMetadataToJSON,
} from './ContentFileSearchResponseMetadata';
import type { LearningResource } from './LearningResource';
import {
    LearningResourceFromJSON,
    LearningResourceFromJSONTyped,
    LearningResourceToJSON,
} from './LearningResource';

/**
 * SearchResponseSerializer with OpenAPI annotations for Learning Resources
 * search
 * @export
 * @interface LearningResourcesSearchResponse
 */
export interface LearningResourcesSearchResponse {
    /**
     * 
     * @type {number}
     * @memberof LearningResourcesSearchResponse
     */
    readonly count: number;
    /**
     * 
     * @type {string}
     * @memberof LearningResourcesSearchResponse
     */
    readonly next: string | null;
    /**
     * 
     * @type {string}
     * @memberof LearningResourcesSearchResponse
     */
    readonly previous: string | null;
    /**
     * 
     * @type {Array<LearningResource>}
     * @memberof LearningResourcesSearchResponse
     */
    readonly results: Array<LearningResource>;
    /**
     * 
     * @type {ContentFileSearchResponseMetadata}
     * @memberof LearningResourcesSearchResponse
     */
    metadata: ContentFileSearchResponseMetadata;
}

/**
 * Check if a given object implements the LearningResourcesSearchResponse interface.
 */
export function instanceOfLearningResourcesSearchResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "next" in value;
    isInstance = isInstance && "previous" in value;
    isInstance = isInstance && "results" in value;
    isInstance = isInstance && "metadata" in value;

    return isInstance;
}

export function LearningResourcesSearchResponseFromJSON(json: any): LearningResourcesSearchResponse {
    return LearningResourcesSearchResponseFromJSONTyped(json, false);
}

export function LearningResourcesSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningResourcesSearchResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'results': ((json['results'] as Array<any>).map(LearningResourceFromJSON)),
        'metadata': ContentFileSearchResponseMetadataFromJSON(json['metadata']),
    };
}

export function LearningResourcesSearchResponseToJSON(value?: LearningResourcesSearchResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ContentFileSearchResponseMetadataToJSON(value.metadata),
    };
}

