/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for LearningResourceInstructor model
 * @export
 * @interface LearningResourceInstructorRequest
 */
export interface LearningResourceInstructorRequest {
    /**
     * 
     * @type {string}
     * @memberof LearningResourceInstructorRequest
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LearningResourceInstructorRequest
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LearningResourceInstructorRequest
     */
    fullName?: string | null;
}

/**
 * Check if a given object implements the LearningResourceInstructorRequest interface.
 */
export function instanceOfLearningResourceInstructorRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LearningResourceInstructorRequestFromJSON(json: any): LearningResourceInstructorRequest {
    return LearningResourceInstructorRequestFromJSONTyped(json, false);
}

export function LearningResourceInstructorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningResourceInstructorRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'fullName': !exists(json, 'full_name') ? undefined : json['full_name'],
    };
}

export function LearningResourceInstructorRequestToJSON(value?: LearningResourceInstructorRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first_name': value.firstName,
        'last_name': value.lastName,
        'full_name': value.fullName,
    };
}

