/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for LearningResourceImage
 * @export
 * @interface LearningResourceImage
 */
export interface LearningResourceImage {
    /**
     * 
     * @type {number}
     * @memberof LearningResourceImage
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof LearningResourceImage
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof LearningResourceImage
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LearningResourceImage
     */
    alt?: string | null;
}

/**
 * Check if a given object implements the LearningResourceImage interface.
 */
export function instanceOfLearningResourceImage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function LearningResourceImageFromJSON(json: any): LearningResourceImage {
    return LearningResourceImageFromJSONTyped(json, false);
}

export function LearningResourceImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningResourceImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'alt': !exists(json, 'alt') ? undefined : json['alt'],
    };
}

export function LearningResourceImageToJSON(value?: LearningResourceImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'description': value.description,
        'alt': value.alt,
    };
}

