/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for LearningResourceOfferor with basic details
 * @export
 * @interface LearningResourceOfferorRequest
 */
export interface LearningResourceOfferorRequest {
    /**
     * 
     * @type {string}
     * @memberof LearningResourceOfferorRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof LearningResourceOfferorRequest
     */
    name: string;
}

/**
 * Check if a given object implements the LearningResourceOfferorRequest interface.
 */
export function instanceOfLearningResourceOfferorRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function LearningResourceOfferorRequestFromJSON(json: any): LearningResourceOfferorRequest {
    return LearningResourceOfferorRequestFromJSONTyped(json, false);
}

export function LearningResourceOfferorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningResourceOfferorRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
    };
}

export function LearningResourceOfferorRequestToJSON(value?: LearningResourceOfferorRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'name': value.name,
    };
}

