/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for LearningResourceTopic model
 * @export
 * @interface LearningResourceTopic
 */
export interface LearningResourceTopic {
    /**
     * 
     * @type {number}
     * @memberof LearningResourceTopic
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof LearningResourceTopic
     */
    name: string;
    /**
     * The icon to display for the topic.
     * @type {string}
     * @memberof LearningResourceTopic
     */
    icon?: string;
    /**
     * 
     * @type {number}
     * @memberof LearningResourceTopic
     */
    parent?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LearningResourceTopic
     */
    readonly channelUrl: string | null;
}

/**
 * Check if a given object implements the LearningResourceTopic interface.
 */
export function instanceOfLearningResourceTopic(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "channelUrl" in value;

    return isInstance;
}

export function LearningResourceTopicFromJSON(json: any): LearningResourceTopic {
    return LearningResourceTopicFromJSONTyped(json, false);
}

export function LearningResourceTopicFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningResourceTopic {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'parent': !exists(json, 'parent') ? undefined : json['parent'],
        'channelUrl': json['channel_url'],
    };
}

export function LearningResourceTopicToJSON(value?: LearningResourceTopic | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'icon': value.icon,
        'parent': value.parent,
    };
}

