/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { AvailabilityEnum } from "./AvailabilityEnum"
import {
  AvailabilityEnumFromJSON,
  AvailabilityEnumFromJSONTyped,
  AvailabilityEnumToJSON,
} from "./AvailabilityEnum"
import type { LearningResourceRunLevelInner } from "./LearningResourceRunLevelInner"
import {
  LearningResourceRunLevelInnerFromJSON,
  LearningResourceRunLevelInnerFromJSONTyped,
  LearningResourceRunLevelInnerToJSON,
} from "./LearningResourceRunLevelInner"

/**
 * Serializer for the LearningResourceRun model
 * @export
 * @interface LearningResourceRunRequest
 */
export interface LearningResourceRunRequest {
  /**
   *
   * @type {Array<LearningResourceRunLevelInner>}
   * @memberof LearningResourceRunRequest
   */
  level: Array<LearningResourceRunLevelInner>
  /**
   *
   * @type {string}
   * @memberof LearningResourceRunRequest
   */
  runId: string
  /**
   *
   * @type {string}
   * @memberof LearningResourceRunRequest
   */
  title: string
  /**
   *
   * @type {string}
   * @memberof LearningResourceRunRequest
   */
  description?: string | null
  /**
   *
   * @type {string}
   * @memberof LearningResourceRunRequest
   */
  fullDescription?: string | null
  /**
   *
   * @type {Date}
   * @memberof LearningResourceRunRequest
   */
  lastModified?: Date | null
  /**
   *
   * @type {boolean}
   * @memberof LearningResourceRunRequest
   */
  published?: boolean
  /**
   *
   * @type {Array<string>}
   * @memberof LearningResourceRunRequest
   */
  languages?: Array<string> | null
  /**
   *
   * @type {string}
   * @memberof LearningResourceRunRequest
   */
  url?: string | null
  /**
   *
   * @type {string}
   * @memberof LearningResourceRunRequest
   */
  slug?: string | null
  /**
   *
   * @type {string}
   * @memberof LearningResourceRunRequest
   */
  semester?: string | null
  /**
   *
   * @type {number}
   * @memberof LearningResourceRunRequest
   */
  year?: number | null
  /**
   *
   * @type {Date}
   * @memberof LearningResourceRunRequest
   */
  startDate?: Date | null
  /**
   *
   * @type {Date}
   * @memberof LearningResourceRunRequest
   */
  endDate?: Date | null
  /**
   *
   * @type {Date}
   * @memberof LearningResourceRunRequest
   */
  enrollmentStart?: Date | null
  /**
   *
   * @type {Date}
   * @memberof LearningResourceRunRequest
   */
  enrollmentEnd?: Date | null
  /**
   *
   * @type {Array<string>}
   * @memberof LearningResourceRunRequest
   */
  prices?: Array<string> | null
  /**
   *
   * @type {string}
   * @memberof LearningResourceRunRequest
   */
  checksum?: string | null
  /**
   *
   * @type {AvailabilityEnum}
   * @memberof LearningResourceRunRequest
   */
  availability?: AvailabilityEnum | null
  /**
   *
   * @type {string}
   * @memberof LearningResourceRunRequest
   */
  location?: string
  /**
   *
   * @type {string}
   * @memberof LearningResourceRunRequest
   */
  duration?: string
  /**
   *
   * @type {number}
   * @memberof LearningResourceRunRequest
   */
  minWeeks?: number | null
  /**
   *
   * @type {number}
   * @memberof LearningResourceRunRequest
   */
  maxWeeks?: number | null
  /**
   *
   * @type {string}
   * @memberof LearningResourceRunRequest
   */
  timeCommitment?: string
  /**
   *
   * @type {number}
   * @memberof LearningResourceRunRequest
   */
  minWeeklyHours?: number | null
  /**
   *
   * @type {number}
   * @memberof LearningResourceRunRequest
   */
  maxWeeklyHours?: number | null
}

/**
 * Check if a given object implements the LearningResourceRunRequest interface.
 */
export function instanceOfLearningResourceRunRequest(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "level" in value
  isInstance = isInstance && "runId" in value
  isInstance = isInstance && "title" in value

  return isInstance
}

export function LearningResourceRunRequestFromJSON(
  json: any,
): LearningResourceRunRequest {
  return LearningResourceRunRequestFromJSONTyped(json, false)
}

export function LearningResourceRunRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LearningResourceRunRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    level: (json["level"] as Array<any>).map(
      LearningResourceRunLevelInnerFromJSON,
    ),
    runId: json["run_id"],
    title: json["title"],
    description: !exists(json, "description") ? undefined : json["description"],
    fullDescription: !exists(json, "full_description")
      ? undefined
      : json["full_description"],
    lastModified: !exists(json, "last_modified")
      ? undefined
      : json["last_modified"] === null
        ? null
        : new Date(json["last_modified"]),
    published: !exists(json, "published") ? undefined : json["published"],
    languages: !exists(json, "languages") ? undefined : json["languages"],
    url: !exists(json, "url") ? undefined : json["url"],
    slug: !exists(json, "slug") ? undefined : json["slug"],
    semester: !exists(json, "semester") ? undefined : json["semester"],
    year: !exists(json, "year") ? undefined : json["year"],
    startDate: !exists(json, "start_date")
      ? undefined
      : json["start_date"] === null
        ? null
        : new Date(json["start_date"]),
    endDate: !exists(json, "end_date")
      ? undefined
      : json["end_date"] === null
        ? null
        : new Date(json["end_date"]),
    enrollmentStart: !exists(json, "enrollment_start")
      ? undefined
      : json["enrollment_start"] === null
        ? null
        : new Date(json["enrollment_start"]),
    enrollmentEnd: !exists(json, "enrollment_end")
      ? undefined
      : json["enrollment_end"] === null
        ? null
        : new Date(json["enrollment_end"]),
    prices: !exists(json, "prices") ? undefined : json["prices"],
    checksum: !exists(json, "checksum") ? undefined : json["checksum"],
    availability: !exists(json, "availability")
      ? undefined
      : AvailabilityEnumFromJSON(json["availability"]),
    location: !exists(json, "location") ? undefined : json["location"],
    duration: !exists(json, "duration") ? undefined : json["duration"],
    minWeeks: !exists(json, "min_weeks") ? undefined : json["min_weeks"],
    maxWeeks: !exists(json, "max_weeks") ? undefined : json["max_weeks"],
    timeCommitment: !exists(json, "time_commitment")
      ? undefined
      : json["time_commitment"],
    minWeeklyHours: !exists(json, "min_weekly_hours")
      ? undefined
      : json["min_weekly_hours"],
    maxWeeklyHours: !exists(json, "max_weekly_hours")
      ? undefined
      : json["max_weekly_hours"],
  }
}

export function LearningResourceRunRequestToJSON(
  value?: LearningResourceRunRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    level: (value.level as Array<any>).map(LearningResourceRunLevelInnerToJSON),
    run_id: value.runId,
    title: value.title,
    description: value.description,
    full_description: value.fullDescription,
    last_modified:
      value.lastModified === undefined
        ? undefined
        : value.lastModified === null
          ? null
          : value.lastModified.toISOString(),
    published: value.published,
    languages: value.languages,
    url: value.url,
    slug: value.slug,
    semester: value.semester,
    year: value.year,
    start_date:
      value.startDate === undefined
        ? undefined
        : value.startDate === null
          ? null
          : value.startDate.toISOString(),
    end_date:
      value.endDate === undefined
        ? undefined
        : value.endDate === null
          ? null
          : value.endDate.toISOString(),
    enrollment_start:
      value.enrollmentStart === undefined
        ? undefined
        : value.enrollmentStart === null
          ? null
          : value.enrollmentStart.toISOString(),
    enrollment_end:
      value.enrollmentEnd === undefined
        ? undefined
        : value.enrollmentEnd === null
          ? null
          : value.enrollmentEnd.toISOString(),
    prices: value.prices,
    checksum: value.checksum,
    availability: AvailabilityEnumToJSON(value.availability),
    location: value.location,
    duration: value.duration,
    min_weeks: value.minWeeks,
    max_weeks: value.maxWeeks,
    time_commitment: value.timeCommitment,
    min_weekly_hours: value.minWeeklyHours,
    max_weekly_hours: value.maxWeeklyHours,
  }
}
