/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Base serializer for LearningResourceSchool model, minus departments list
 * 
 * The absence of the departments list is to avoid a circular serialization structure.
 * @export
 * @interface LearningResourceBaseSchool
 */
export interface LearningResourceBaseSchool {
    /**
     * 
     * @type {number}
     * @memberof LearningResourceBaseSchool
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof LearningResourceBaseSchool
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LearningResourceBaseSchool
     */
    url: string;
}

/**
 * Check if a given object implements the LearningResourceBaseSchool interface.
 */
export function instanceOfLearningResourceBaseSchool(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function LearningResourceBaseSchoolFromJSON(json: any): LearningResourceBaseSchool {
    return LearningResourceBaseSchoolFromJSONTyped(json, false);
}

export function LearningResourceBaseSchoolFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningResourceBaseSchool {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'url': json['url'],
    };
}

export function LearningResourceBaseSchoolToJSON(value?: LearningResourceBaseSchool | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'url': value.url,
    };
}

