/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 * Full serializer for LearningResourceDepartment, including school
 * @export
 * @interface LearningResourceDepartmentRequest
 */
export interface LearningResourceDepartmentRequest {
  /**
   *
   * @type {string}
   * @memberof LearningResourceDepartmentRequest
   */
  departmentId: string
  /**
   *
   * @type {string}
   * @memberof LearningResourceDepartmentRequest
   */
  name: string
}

/**
 * Check if a given object implements the LearningResourceDepartmentRequest interface.
 */
export function instanceOfLearningResourceDepartmentRequest(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "departmentId" in value
  isInstance = isInstance && "name" in value

  return isInstance
}

export function LearningResourceDepartmentRequestFromJSON(
  json: any,
): LearningResourceDepartmentRequest {
  return LearningResourceDepartmentRequestFromJSONTyped(json, false)
}

export function LearningResourceDepartmentRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LearningResourceDepartmentRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    departmentId: json["department_id"],
    name: json["name"],
  }
}

export function LearningResourceDepartmentRequestToJSON(
  value?: LearningResourceDepartmentRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    department_id: value.departmentId,
    name: value.name,
  }
}
