/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Minimal serializer for LearningResource - returns only essential fields
 * for sitemap generation and other use cases requiring minimal data transfer.
 * @export
 * @interface LearningResourceSummary
 */
export interface LearningResourceSummary {
    /**
     * 
     * @type {number}
     * @memberof LearningResourceSummary
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof LearningResourceSummary
     */
    lastModified?: Date | null;
}

/**
 * Check if a given object implements the LearningResourceSummary interface.
 */
export function instanceOfLearningResourceSummary(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function LearningResourceSummaryFromJSON(json: any): LearningResourceSummary {
    return LearningResourceSummaryFromJSONTyped(json, false);
}

export function LearningResourceSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningResourceSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'lastModified': !exists(json, 'last_modified') ? undefined : (json['last_modified'] === null ? null : new Date(json['last_modified'])),
    };
}

export function LearningResourceSummaryToJSON(value?: LearningResourceSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'last_modified': value.lastModified === undefined ? undefined : (value.lastModified === null ? null : value.lastModified.toISOString()),
    };
}

