/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LearningResource } from './LearningResource';
import {
    LearningResourceFromJSON,
    LearningResourceFromJSONTyped,
    LearningResourceToJSON,
} from './LearningResource';
import type { RelationTypeEnum } from './RelationTypeEnum';
import {
    RelationTypeEnumFromJSON,
    RelationTypeEnumFromJSONTyped,
    RelationTypeEnumToJSON,
} from './RelationTypeEnum';

/**
 * CRUD serializer for LearningResourceRelationship
 * @export
 * @interface LearningResourceRelationship
 */
export interface LearningResourceRelationship {
    /**
     * 
     * @type {number}
     * @memberof LearningResourceRelationship
     */
    readonly id: number;
    /**
     * 
     * @type {LearningResource}
     * @memberof LearningResourceRelationship
     */
    readonly resource: LearningResource;
    /**
     * 
     * @type {number}
     * @memberof LearningResourceRelationship
     */
    position?: number;
    /**
     * 
     * @type {RelationTypeEnum}
     * @memberof LearningResourceRelationship
     */
    relationType?: RelationTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof LearningResourceRelationship
     */
    parent: number;
    /**
     * 
     * @type {number}
     * @memberof LearningResourceRelationship
     */
    child: number;
}

/**
 * Check if a given object implements the LearningResourceRelationship interface.
 */
export function instanceOfLearningResourceRelationship(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "resource" in value;
    isInstance = isInstance && "parent" in value;
    isInstance = isInstance && "child" in value;

    return isInstance;
}

export function LearningResourceRelationshipFromJSON(json: any): LearningResourceRelationship {
    return LearningResourceRelationshipFromJSONTyped(json, false);
}

export function LearningResourceRelationshipFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningResourceRelationship {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'resource': LearningResourceFromJSON(json['resource']),
        'position': !exists(json, 'position') ? undefined : json['position'],
        'relationType': !exists(json, 'relation_type') ? undefined : RelationTypeEnumFromJSON(json['relation_type']),
        'parent': json['parent'],
        'child': json['child'],
    };
}

export function LearningResourceRelationshipToJSON(value?: LearningResourceRelationship | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'position': value.position,
        'relation_type': RelationTypeEnumToJSON(value.relationType),
        'parent': value.parent,
        'child': value.child,
    };
}

