/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CourseResource } from './CourseResource';
import {
    instanceOfCourseResource,
    CourseResourceFromJSON,
    CourseResourceFromJSONTyped,
    CourseResourceToJSON,
} from './CourseResource';
import type { LearningPathResource } from './LearningPathResource';
import {
    instanceOfLearningPathResource,
    LearningPathResourceFromJSON,
    LearningPathResourceFromJSONTyped,
    LearningPathResourceToJSON,
} from './LearningPathResource';
import type { PodcastEpisodeResource } from './PodcastEpisodeResource';
import {
    instanceOfPodcastEpisodeResource,
    PodcastEpisodeResourceFromJSON,
    PodcastEpisodeResourceFromJSONTyped,
    PodcastEpisodeResourceToJSON,
} from './PodcastEpisodeResource';
import type { PodcastResource } from './PodcastResource';
import {
    instanceOfPodcastResource,
    PodcastResourceFromJSON,
    PodcastResourceFromJSONTyped,
    PodcastResourceToJSON,
} from './PodcastResource';
import type { ProgramResource } from './ProgramResource';
import {
    instanceOfProgramResource,
    ProgramResourceFromJSON,
    ProgramResourceFromJSONTyped,
    ProgramResourceToJSON,
} from './ProgramResource';
import type { VideoPlaylistResource } from './VideoPlaylistResource';
import {
    instanceOfVideoPlaylistResource,
    VideoPlaylistResourceFromJSON,
    VideoPlaylistResourceFromJSONTyped,
    VideoPlaylistResourceToJSON,
} from './VideoPlaylistResource';
import type { VideoResource } from './VideoResource';
import {
    instanceOfVideoResource,
    VideoResourceFromJSON,
    VideoResourceFromJSONTyped,
    VideoResourceToJSON,
} from './VideoResource';

/**
 * @type LearningResource
 * 
 * @export
 */
export type LearningResource = { resourceType: 'course' } & CourseResource | { resourceType: 'learning_path' } & LearningPathResource | { resourceType: 'podcast' } & PodcastResource | { resourceType: 'podcast_episode' } & PodcastEpisodeResource | { resourceType: 'program' } & ProgramResource | { resourceType: 'video' } & VideoResource | { resourceType: 'video_playlist' } & VideoPlaylistResource;

export function LearningResourceFromJSON(json: any): LearningResource {
    return LearningResourceFromJSONTyped(json, false);
}

export function LearningResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['resource_type']) {
        case 'course':
            return {...CourseResourceFromJSONTyped(json, true), resourceType: 'course'};
        case 'learning_path':
            return {...LearningPathResourceFromJSONTyped(json, true), resourceType: 'learning_path'};
        case 'podcast':
            return {...PodcastResourceFromJSONTyped(json, true), resourceType: 'podcast'};
        case 'podcast_episode':
            return {...PodcastEpisodeResourceFromJSONTyped(json, true), resourceType: 'podcast_episode'};
        case 'program':
            return {...ProgramResourceFromJSONTyped(json, true), resourceType: 'program'};
        case 'video':
            return {...VideoResourceFromJSONTyped(json, true), resourceType: 'video'};
        case 'video_playlist':
            return {...VideoPlaylistResourceFromJSONTyped(json, true), resourceType: 'video_playlist'};
        default:
            throw new Error(`No variant of LearningResource exists with 'resourceType=${json['resourceType']}'`);
    }
}

export function LearningResourceToJSON(value?: LearningResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['resourceType']) {
        case 'course':
            return CourseResourceToJSON(value);
        case 'learning_path':
            return LearningPathResourceToJSON(value);
        case 'podcast':
            return PodcastResourceToJSON(value);
        case 'podcast_episode':
            return PodcastEpisodeResourceToJSON(value);
        case 'program':
            return ProgramResourceToJSON(value);
        case 'video':
            return VideoResourceToJSON(value);
        case 'video_playlist':
            return VideoPlaylistResourceToJSON(value);
        default:
            throw new Error(`No variant of LearningResource exists with 'resourceType=${value['resourceType']}'`);
    }

}

