/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for LearningResourceContentTag
 * @export
 * @interface LearningResourceContentTag
 */
export interface LearningResourceContentTag {
    /**
     * 
     * @type {number}
     * @memberof LearningResourceContentTag
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof LearningResourceContentTag
     */
    name: string;
}

/**
 * Check if a given object implements the LearningResourceContentTag interface.
 */
export function instanceOfLearningResourceContentTag(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function LearningResourceContentTagFromJSON(json: any): LearningResourceContentTag {
    return LearningResourceContentTagFromJSONTyped(json, false);
}

export function LearningResourceContentTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningResourceContentTag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function LearningResourceContentTagToJSON(value?: LearningResourceContentTag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

