/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 * Serializer for LearningResourcePlatform
 * @export
 * @interface LearningResourcePlatformRequest
 */
export interface LearningResourcePlatformRequest {
  /**
   *
   * @type {string}
   * @memberof LearningResourcePlatformRequest
   */
  code: string
  /**
   *
   * @type {string}
   * @memberof LearningResourcePlatformRequest
   */
  name?: string
}

/**
 * Check if a given object implements the LearningResourcePlatformRequest interface.
 */
export function instanceOfLearningResourcePlatformRequest(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "code" in value

  return isInstance
}

export function LearningResourcePlatformRequestFromJSON(
  json: any,
): LearningResourcePlatformRequest {
  return LearningResourcePlatformRequestFromJSONTyped(json, false)
}

export function LearningResourcePlatformRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LearningResourcePlatformRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    code: json["code"],
    name: !exists(json, "name") ? undefined : json["name"],
  }
}

export function LearningResourcePlatformRequestToJSON(
  value?: LearningResourcePlatformRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    code: value.code,
    name: value.name,
  }
}
