/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 * Serializer containing only parent and child ids for a learning path relationship
 * @export
 * @interface MicroLearningPathRelationship
 */
export interface MicroLearningPathRelationship {
  /**
   *
   * @type {number}
   * @memberof MicroLearningPathRelationship
   */
  readonly id: number
  /**
   * The id of the parent learning resource
   * @type {number}
   * @memberof MicroLearningPathRelationship
   */
  readonly parent: number
  /**
   *
   * @type {number}
   * @memberof MicroLearningPathRelationship
   */
  readonly child: number
}

/**
 * Check if a given object implements the MicroLearningPathRelationship interface.
 */
export function instanceOfMicroLearningPathRelationship(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "parent" in value
  isInstance = isInstance && "child" in value

  return isInstance
}

export function MicroLearningPathRelationshipFromJSON(
  json: any,
): MicroLearningPathRelationship {
  return MicroLearningPathRelationshipFromJSONTyped(json, false)
}

export function MicroLearningPathRelationshipFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MicroLearningPathRelationship {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json["id"],
    parent: json["parent"],
    child: json["child"],
  }
}

export function MicroLearningPathRelationshipToJSON(
  value?: MicroLearningPathRelationship | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {}
}
