/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LearningResourceDepartment } from './LearningResourceDepartment';
import {
    LearningResourceDepartmentFromJSON,
    LearningResourceDepartmentFromJSONTyped,
    LearningResourceDepartmentToJSON,
} from './LearningResourceDepartment';

/**
 * 
 * @export
 * @interface PaginatedLearningResourceDepartmentList
 */
export interface PaginatedLearningResourceDepartmentList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLearningResourceDepartmentList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLearningResourceDepartmentList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLearningResourceDepartmentList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<LearningResourceDepartment>}
     * @memberof PaginatedLearningResourceDepartmentList
     */
    results: Array<LearningResourceDepartment>;
}

/**
 * Check if a given object implements the PaginatedLearningResourceDepartmentList interface.
 */
export function instanceOfPaginatedLearningResourceDepartmentList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function PaginatedLearningResourceDepartmentListFromJSON(json: any): PaginatedLearningResourceDepartmentList {
    return PaginatedLearningResourceDepartmentListFromJSONTyped(json, false);
}

export function PaginatedLearningResourceDepartmentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLearningResourceDepartmentList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(LearningResourceDepartmentFromJSON)),
    };
}

export function PaginatedLearningResourceDepartmentListToJSON(value?: PaginatedLearningResourceDepartmentList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(LearningResourceDepartmentToJSON)),
    };
}

