/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LearningResourceRelationship } from './LearningResourceRelationship';
import {
    LearningResourceRelationshipFromJSON,
    LearningResourceRelationshipFromJSONTyped,
    LearningResourceRelationshipToJSON,
} from './LearningResourceRelationship';

/**
 * 
 * @export
 * @interface PaginatedLearningResourceRelationshipList
 */
export interface PaginatedLearningResourceRelationshipList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLearningResourceRelationshipList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLearningResourceRelationshipList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLearningResourceRelationshipList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<LearningResourceRelationship>}
     * @memberof PaginatedLearningResourceRelationshipList
     */
    results: Array<LearningResourceRelationship>;
}

/**
 * Check if a given object implements the PaginatedLearningResourceRelationshipList interface.
 */
export function instanceOfPaginatedLearningResourceRelationshipList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function PaginatedLearningResourceRelationshipListFromJSON(json: any): PaginatedLearningResourceRelationshipList {
    return PaginatedLearningResourceRelationshipListFromJSONTyped(json, false);
}

export function PaginatedLearningResourceRelationshipListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLearningResourceRelationshipList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(LearningResourceRelationshipFromJSON)),
    };
}

export function PaginatedLearningResourceRelationshipListToJSON(value?: PaginatedLearningResourceRelationshipList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(LearningResourceRelationshipToJSON)),
    };
}

