/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LearningResourceSummary } from './LearningResourceSummary';
import {
    LearningResourceSummaryFromJSON,
    LearningResourceSummaryFromJSONTyped,
    LearningResourceSummaryToJSON,
} from './LearningResourceSummary';

/**
 * 
 * @export
 * @interface PaginatedLearningResourceSummaryList
 */
export interface PaginatedLearningResourceSummaryList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLearningResourceSummaryList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLearningResourceSummaryList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLearningResourceSummaryList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<LearningResourceSummary>}
     * @memberof PaginatedLearningResourceSummaryList
     */
    results: Array<LearningResourceSummary>;
}

/**
 * Check if a given object implements the PaginatedLearningResourceSummaryList interface.
 */
export function instanceOfPaginatedLearningResourceSummaryList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function PaginatedLearningResourceSummaryListFromJSON(json: any): PaginatedLearningResourceSummaryList {
    return PaginatedLearningResourceSummaryListFromJSONTyped(json, false);
}

export function PaginatedLearningResourceSummaryListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLearningResourceSummaryList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(LearningResourceSummaryFromJSON)),
    };
}

export function PaginatedLearningResourceSummaryListToJSON(value?: PaginatedLearningResourceSummaryList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(LearningResourceSummaryToJSON)),
    };
}

