/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LearningResource } from './LearningResource';
import {
    LearningResourceFromJSON,
    LearningResourceFromJSONTyped,
    LearningResourceToJSON,
} from './LearningResource';

/**
 * 
 * @export
 * @interface PaginatedLearningResourceList
 */
export interface PaginatedLearningResourceList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLearningResourceList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLearningResourceList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLearningResourceList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<LearningResource>}
     * @memberof PaginatedLearningResourceList
     */
    results: Array<LearningResource>;
}

/**
 * Check if a given object implements the PaginatedLearningResourceList interface.
 */
export function instanceOfPaginatedLearningResourceList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function PaginatedLearningResourceListFromJSON(json: any): PaginatedLearningResourceList {
    return PaginatedLearningResourceListFromJSONTyped(json, false);
}

export function PaginatedLearningResourceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLearningResourceList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(LearningResourceFromJSON)),
    };
}

export function PaginatedLearningResourceListToJSON(value?: PaginatedLearningResourceList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(LearningResourceToJSON)),
    };
}

