/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { RelationTypeEnum } from "./RelationTypeEnum"
import {
  RelationTypeEnumFromJSON,
  RelationTypeEnumFromJSONTyped,
  RelationTypeEnumToJSON,
} from "./RelationTypeEnum"

/**
 * CRUD serializer for LearningResourceRelationship
 * @export
 * @interface PatchedLearningResourceRelationshipRequest
 */
export interface PatchedLearningResourceRelationshipRequest {
  /**
   *
   * @type {number}
   * @memberof PatchedLearningResourceRelationshipRequest
   */
  position?: number
  /**
   *
   * @type {RelationTypeEnum}
   * @memberof PatchedLearningResourceRelationshipRequest
   */
  relationType?: RelationTypeEnum
  /**
   *
   * @type {number}
   * @memberof PatchedLearningResourceRelationshipRequest
   */
  parent?: number
  /**
   *
   * @type {number}
   * @memberof PatchedLearningResourceRelationshipRequest
   */
  child?: number
}

/**
 * Check if a given object implements the PatchedLearningResourceRelationshipRequest interface.
 */
export function instanceOfPatchedLearningResourceRelationshipRequest(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function PatchedLearningResourceRelationshipRequestFromJSON(
  json: any,
): PatchedLearningResourceRelationshipRequest {
  return PatchedLearningResourceRelationshipRequestFromJSONTyped(json, false)
}

export function PatchedLearningResourceRelationshipRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PatchedLearningResourceRelationshipRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    position: !exists(json, "position") ? undefined : json["position"],
    relationType: !exists(json, "relation_type")
      ? undefined
      : RelationTypeEnumFromJSON(json["relation_type"]),
    parent: !exists(json, "parent") ? undefined : json["parent"],
    child: !exists(json, "child") ? undefined : json["child"],
  }
}

export function PatchedLearningResourceRelationshipRequestToJSON(
  value?: PatchedLearningResourceRelationshipRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    position: value.position,
    relation_type: RelationTypeEnumToJSON(value.relationType),
    parent: value.parent,
    child: value.child,
  }
}
