/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 * Specialized serializer for a LearningPath relationship
 * @export
 * @interface PatchedLearningPathRelationshipRequest
 */
export interface PatchedLearningPathRelationshipRequest {
  /**
   *
   * @type {number}
   * @memberof PatchedLearningPathRelationshipRequest
   */
  position?: number
  /**
   *
   * @type {number}
   * @memberof PatchedLearningPathRelationshipRequest
   */
  parent?: number
  /**
   *
   * @type {number}
   * @memberof PatchedLearningPathRelationshipRequest
   */
  child?: number
}

/**
 * Check if a given object implements the PatchedLearningPathRelationshipRequest interface.
 */
export function instanceOfPatchedLearningPathRelationshipRequest(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function PatchedLearningPathRelationshipRequestFromJSON(
  json: any,
): PatchedLearningPathRelationshipRequest {
  return PatchedLearningPathRelationshipRequestFromJSONTyped(json, false)
}

export function PatchedLearningPathRelationshipRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PatchedLearningPathRelationshipRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    position: !exists(json, "position") ? undefined : json["position"],
    parent: !exists(json, "parent") ? undefined : json["parent"],
    child: !exists(json, "child") ? undefined : json["child"],
  }
}

export function PatchedLearningPathRelationshipRequestToJSON(
  value?: PatchedLearningPathRelationshipRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    position: value.position,
    parent: value.parent,
    child: value.child,
  }
}
