/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SourceTypeEnum } from './SourceTypeEnum';
import {
    SourceTypeEnumFromJSON,
    SourceTypeEnumFromJSONTyped,
    SourceTypeEnumToJSON,
} from './SourceTypeEnum';

/**
 * Serializer for PercolateQuery objects
 * @export
 * @interface PercolateQuery
 */
export interface PercolateQuery {
    /**
     * 
     * @type {number}
     * @memberof PercolateQuery
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof PercolateQuery
     */
    readonly sourceDescription: string;
    /**
     * 
     * @type {string}
     * @memberof PercolateQuery
     */
    readonly sourceLabel: string;
    /**
     * 
     * @type {any}
     * @memberof PercolateQuery
     */
    originalQuery: any | null;
    /**
     * 
     * @type {any}
     * @memberof PercolateQuery
     */
    query: any | null;
    /**
     * 
     * @type {SourceTypeEnum}
     * @memberof PercolateQuery
     */
    sourceType: SourceTypeEnum;
    /**
     * Friendly display label for the query
     * @type {string}
     * @memberof PercolateQuery
     */
    displayLabel?: string;
}

/**
 * Check if a given object implements the PercolateQuery interface.
 */
export function instanceOfPercolateQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "sourceDescription" in value;
    isInstance = isInstance && "sourceLabel" in value;
    isInstance = isInstance && "originalQuery" in value;
    isInstance = isInstance && "query" in value;
    isInstance = isInstance && "sourceType" in value;

    return isInstance;
}

export function PercolateQueryFromJSON(json: any): PercolateQuery {
    return PercolateQueryFromJSONTyped(json, false);
}

export function PercolateQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PercolateQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sourceDescription': json['source_description'],
        'sourceLabel': json['source_label'],
        'originalQuery': json['original_query'],
        'query': json['query'],
        'sourceType': SourceTypeEnumFromJSON(json['source_type']),
        'displayLabel': !exists(json, 'display_label') ? undefined : json['display_label'],
    };
}

export function PercolateQueryToJSON(value?: PercolateQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'original_query': value.originalQuery,
        'query': value.query,
        'source_type': SourceTypeEnumToJSON(value.sourceType),
        'display_label': value.displayLabel,
    };
}

