/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { AvailabilityEnum } from "./AvailabilityEnum"
import {
  AvailabilityEnumFromJSON,
  AvailabilityEnumFromJSONTyped,
  AvailabilityEnumToJSON,
} from "./AvailabilityEnum"
import type { CourseResourceCertificationType } from "./CourseResourceCertificationType"
import {
  CourseResourceCertificationTypeFromJSON,
  CourseResourceCertificationTypeFromJSONTyped,
  CourseResourceCertificationTypeToJSON,
} from "./CourseResourceCertificationType"
import type { CourseResourceDeliveryInner } from "./CourseResourceDeliveryInner"
import {
  CourseResourceDeliveryInnerFromJSON,
  CourseResourceDeliveryInnerFromJSONTyped,
  CourseResourceDeliveryInnerToJSON,
} from "./CourseResourceDeliveryInner"
import type { CourseResourceFormatInner } from "./CourseResourceFormatInner"
import {
  CourseResourceFormatInnerFromJSON,
  CourseResourceFormatInnerFromJSONTyped,
  CourseResourceFormatInnerToJSON,
} from "./CourseResourceFormatInner"
import type { CourseResourcePaceInner } from "./CourseResourcePaceInner"
import {
  CourseResourcePaceInnerFromJSON,
  CourseResourcePaceInnerFromJSONTyped,
  CourseResourcePaceInnerToJSON,
} from "./CourseResourcePaceInner"
import type { LearningResourceDepartment } from "./LearningResourceDepartment"
import {
  LearningResourceDepartmentFromJSON,
  LearningResourceDepartmentFromJSONTyped,
  LearningResourceDepartmentToJSON,
} from "./LearningResourceDepartment"
import type { LearningResourceImage } from "./LearningResourceImage"
import {
  LearningResourceImageFromJSON,
  LearningResourceImageFromJSONTyped,
  LearningResourceImageToJSON,
} from "./LearningResourceImage"
import type { LearningResourceOfferor } from "./LearningResourceOfferor"
import {
  LearningResourceOfferorFromJSON,
  LearningResourceOfferorFromJSONTyped,
  LearningResourceOfferorToJSON,
} from "./LearningResourceOfferor"
import type { LearningResourcePlatform } from "./LearningResourcePlatform"
import {
  LearningResourcePlatformFromJSON,
  LearningResourcePlatformFromJSONTyped,
  LearningResourcePlatformToJSON,
} from "./LearningResourcePlatform"
import type { LearningResourcePrice } from "./LearningResourcePrice"
import {
  LearningResourcePriceFromJSON,
  LearningResourcePriceFromJSONTyped,
  LearningResourcePriceToJSON,
} from "./LearningResourcePrice"
import type { LearningResourceRelationshipChildField } from "./LearningResourceRelationshipChildField"
import {
  LearningResourceRelationshipChildFieldFromJSON,
  LearningResourceRelationshipChildFieldFromJSONTyped,
  LearningResourceRelationshipChildFieldToJSON,
} from "./LearningResourceRelationshipChildField"
import type { LearningResourceRun } from "./LearningResourceRun"
import {
  LearningResourceRunFromJSON,
  LearningResourceRunFromJSONTyped,
  LearningResourceRunToJSON,
} from "./LearningResourceRun"
import type { LearningResourceTopic } from "./LearningResourceTopic"
import {
  LearningResourceTopicFromJSON,
  LearningResourceTopicFromJSONTyped,
  LearningResourceTopicToJSON,
} from "./LearningResourceTopic"
import type { MicroLearningPathRelationship } from "./MicroLearningPathRelationship"
import {
  MicroLearningPathRelationshipFromJSON,
  MicroLearningPathRelationshipFromJSONTyped,
  MicroLearningPathRelationshipToJSON,
} from "./MicroLearningPathRelationship"
import type { MicroUserListRelationship } from "./MicroUserListRelationship"
import {
  MicroUserListRelationshipFromJSON,
  MicroUserListRelationshipFromJSONTyped,
  MicroUserListRelationshipToJSON,
} from "./MicroUserListRelationship"
import type { PodcastEpisode } from "./PodcastEpisode"
import {
  PodcastEpisodeFromJSON,
  PodcastEpisodeFromJSONTyped,
  PodcastEpisodeToJSON,
} from "./PodcastEpisode"
import type { PodcastEpisodeResourceResourceTypeEnum } from "./PodcastEpisodeResourceResourceTypeEnum"
import {
  PodcastEpisodeResourceResourceTypeEnumFromJSON,
  PodcastEpisodeResourceResourceTypeEnumFromJSONTyped,
  PodcastEpisodeResourceResourceTypeEnumToJSON,
} from "./PodcastEpisodeResourceResourceTypeEnum"

/**
 * Serializer for podcast episode resources
 * @export
 * @interface PodcastEpisodeResource
 */
export interface PodcastEpisodeResource {
  /**
   *
   * @type {number}
   * @memberof PodcastEpisodeResource
   */
  readonly id: number
  /**
   *
   * @type {Array<LearningResourceTopic>}
   * @memberof PodcastEpisodeResource
   */
  topics?: Array<LearningResourceTopic>
  /**
   *
   * @type {number}
   * @memberof PodcastEpisodeResource
   */
  readonly position: number | null
  /**
   *
   * @type {LearningResourceOfferor}
   * @memberof PodcastEpisodeResource
   */
  readonly offeredBy: LearningResourceOfferor | null
  /**
   *
   * @type {LearningResourcePlatform}
   * @memberof PodcastEpisodeResource
   */
  readonly platform: LearningResourcePlatform | null
  /**
   *
   * @type {Array<string>}
   * @memberof PodcastEpisodeResource
   */
  readonly courseFeature: Array<string> | null
  /**
   *
   * @type {Array<LearningResourceDepartment>}
   * @memberof PodcastEpisodeResource
   */
  readonly departments: Array<LearningResourceDepartment> | null
  /**
   *
   * @type {boolean}
   * @memberof PodcastEpisodeResource
   */
  readonly certification: boolean
  /**
   *
   * @type {CourseResourceCertificationType}
   * @memberof PodcastEpisodeResource
   */
  certificationType: CourseResourceCertificationType
  /**
   *
   * @type {Array<string>}
   * @memberof PodcastEpisodeResource
   */
  readonly prices: Array<string>
  /**
   *
   * @type {Array<LearningResourcePrice>}
   * @memberof PodcastEpisodeResource
   */
  readonly resourcePrices: Array<LearningResourcePrice>
  /**
   *
   * @type {Array<LearningResourceRun>}
   * @memberof PodcastEpisodeResource
   */
  readonly runs: Array<LearningResourceRun> | null
  /**
   *
   * @type {LearningResourceImage}
   * @memberof PodcastEpisodeResource
   */
  readonly image: LearningResourceImage | null
  /**
   *
   * @type {Array<MicroLearningPathRelationship>}
   * @memberof PodcastEpisodeResource
   */
  readonly learningPathParents: Array<MicroLearningPathRelationship>
  /**
   *
   * @type {Array<MicroUserListRelationship>}
   * @memberof PodcastEpisodeResource
   */
  readonly userListParents: Array<MicroUserListRelationship>
  /**
   *
   * @type {number}
   * @memberof PodcastEpisodeResource
   */
  readonly views: number
  /**
   *
   * @type {Array<CourseResourceDeliveryInner>}
   * @memberof PodcastEpisodeResource
   */
  readonly delivery: Array<CourseResourceDeliveryInner>
  /**
   * Return true if the resource is free/has a free option
   * @type {boolean}
   * @memberof PodcastEpisodeResource
   */
  readonly free: boolean
  /**
   * Return the resource category of the resource
   * @type {string}
   * @memberof PodcastEpisodeResource
   */
  readonly resourceCategory: string
  /**
   *
   * @type {Array<CourseResourceFormatInner>}
   * @memberof PodcastEpisodeResource
   */
  readonly format: Array<CourseResourceFormatInner>
  /**
   *
   * @type {Array<CourseResourcePaceInner>}
   * @memberof PodcastEpisodeResource
   */
  readonly pace: Array<CourseResourcePaceInner>
  /**
   *
   * @type {LearningResourceRelationshipChildField}
   * @memberof PodcastEpisodeResource
   */
  readonly children: LearningResourceRelationshipChildField | null
  /**
   *
   * @type {PodcastEpisodeResourceResourceTypeEnum}
   * @memberof PodcastEpisodeResource
   */
  readonly resourceType: PodcastEpisodeResourceResourceTypeEnum
  /**
   *
   * @type {PodcastEpisode}
   * @memberof PodcastEpisodeResource
   */
  readonly podcastEpisode: PodcastEpisode
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResource
   */
  readableId: string
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResource
   */
  title: string
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResource
   */
  description?: string | null
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResource
   */
  fullDescription?: string | null
  /**
   *
   * @type {Date}
   * @memberof PodcastEpisodeResource
   */
  lastModified?: Date | null
  /**
   *
   * @type {boolean}
   * @memberof PodcastEpisodeResource
   */
  published?: boolean
  /**
   *
   * @type {Array<string>}
   * @memberof PodcastEpisodeResource
   */
  languages?: Array<string> | null
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResource
   */
  url?: string | null
  /**
   *
   * @type {Array<string>}
   * @memberof PodcastEpisodeResource
   */
  ocwTopics?: Array<string>
  /**
   *
   * @type {boolean}
   * @memberof PodcastEpisodeResource
   */
  readonly professional: boolean
  /**
   *
   * @type {Date}
   * @memberof PodcastEpisodeResource
   */
  nextStartDate?: Date | null
  /**
   *
   * @type {AvailabilityEnum}
   * @memberof PodcastEpisodeResource
   */
  availability?: AvailabilityEnum | null
  /**
   *
   * @type {number}
   * @memberof PodcastEpisodeResource
   */
  completeness?: number
  /**
   *
   * @type {boolean}
   * @memberof PodcastEpisodeResource
   */
  licenseCc?: boolean
  /**
   *
   * @type {boolean}
   * @memberof PodcastEpisodeResource
   */
  testMode?: boolean
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResource
   */
  continuingEdCredits?: string | null
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResource
   */
  location?: string
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResource
   */
  duration?: string
  /**
   *
   * @type {number}
   * @memberof PodcastEpisodeResource
   */
  minWeeks?: number | null
  /**
   *
   * @type {number}
   * @memberof PodcastEpisodeResource
   */
  maxWeeks?: number | null
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResource
   */
  timeCommitment?: string
  /**
   *
   * @type {number}
   * @memberof PodcastEpisodeResource
   */
  minWeeklyHours?: number | null
  /**
   *
   * @type {number}
   * @memberof PodcastEpisodeResource
   */
  maxWeeklyHours?: number | null
  /**
   *
   * @type {boolean}
   * @memberof PodcastEpisodeResource
   */
  readonly requireSummaries: boolean
}

/**
 * Check if a given object implements the PodcastEpisodeResource interface.
 */
export function instanceOfPodcastEpisodeResource(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "position" in value
  isInstance = isInstance && "offeredBy" in value
  isInstance = isInstance && "platform" in value
  isInstance = isInstance && "courseFeature" in value
  isInstance = isInstance && "departments" in value
  isInstance = isInstance && "certification" in value
  isInstance = isInstance && "certificationType" in value
  isInstance = isInstance && "prices" in value
  isInstance = isInstance && "resourcePrices" in value
  isInstance = isInstance && "runs" in value
  isInstance = isInstance && "image" in value
  isInstance = isInstance && "learningPathParents" in value
  isInstance = isInstance && "userListParents" in value
  isInstance = isInstance && "views" in value
  isInstance = isInstance && "delivery" in value
  isInstance = isInstance && "free" in value
  isInstance = isInstance && "resourceCategory" in value
  isInstance = isInstance && "format" in value
  isInstance = isInstance && "pace" in value
  isInstance = isInstance && "children" in value
  isInstance = isInstance && "resourceType" in value
  isInstance = isInstance && "podcastEpisode" in value
  isInstance = isInstance && "readableId" in value
  isInstance = isInstance && "title" in value
  isInstance = isInstance && "professional" in value
  isInstance = isInstance && "requireSummaries" in value

  return isInstance
}

export function PodcastEpisodeResourceFromJSON(
  json: any,
): PodcastEpisodeResource {
  return PodcastEpisodeResourceFromJSONTyped(json, false)
}

export function PodcastEpisodeResourceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PodcastEpisodeResource {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json["id"],
    topics: !exists(json, "topics")
      ? undefined
      : (json["topics"] as Array<any>).map(LearningResourceTopicFromJSON),
    position: json["position"],
    offeredBy: LearningResourceOfferorFromJSON(json["offered_by"]),
    platform: LearningResourcePlatformFromJSON(json["platform"]),
    courseFeature: json["course_feature"],
    departments:
      json["departments"] === null
        ? null
        : (json["departments"] as Array<any>).map(
            LearningResourceDepartmentFromJSON,
          ),
    certification: json["certification"],
    certificationType: CourseResourceCertificationTypeFromJSON(
      json["certification_type"],
    ),
    prices: json["prices"],
    resourcePrices: (json["resource_prices"] as Array<any>).map(
      LearningResourcePriceFromJSON,
    ),
    runs:
      json["runs"] === null
        ? null
        : (json["runs"] as Array<any>).map(LearningResourceRunFromJSON),
    image: LearningResourceImageFromJSON(json["image"]),
    learningPathParents: (json["learning_path_parents"] as Array<any>).map(
      MicroLearningPathRelationshipFromJSON,
    ),
    userListParents: (json["user_list_parents"] as Array<any>).map(
      MicroUserListRelationshipFromJSON,
    ),
    views: json["views"],
    delivery: (json["delivery"] as Array<any>).map(
      CourseResourceDeliveryInnerFromJSON,
    ),
    free: json["free"],
    resourceCategory: json["resource_category"],
    format: (json["format"] as Array<any>).map(
      CourseResourceFormatInnerFromJSON,
    ),
    pace: (json["pace"] as Array<any>).map(CourseResourcePaceInnerFromJSON),
    children: LearningResourceRelationshipChildFieldFromJSON(json["children"]),
    resourceType: PodcastEpisodeResourceResourceTypeEnumFromJSON(
      json["resource_type"],
    ),
    podcastEpisode: PodcastEpisodeFromJSON(json["podcast_episode"]),
    readableId: json["readable_id"],
    title: json["title"],
    description: !exists(json, "description") ? undefined : json["description"],
    fullDescription: !exists(json, "full_description")
      ? undefined
      : json["full_description"],
    lastModified: !exists(json, "last_modified")
      ? undefined
      : json["last_modified"] === null
        ? null
        : new Date(json["last_modified"]),
    published: !exists(json, "published") ? undefined : json["published"],
    languages: !exists(json, "languages") ? undefined : json["languages"],
    url: !exists(json, "url") ? undefined : json["url"],
    ocwTopics: !exists(json, "ocw_topics") ? undefined : json["ocw_topics"],
    professional: json["professional"],
    nextStartDate: !exists(json, "next_start_date")
      ? undefined
      : json["next_start_date"] === null
        ? null
        : new Date(json["next_start_date"]),
    availability: !exists(json, "availability")
      ? undefined
      : AvailabilityEnumFromJSON(json["availability"]),
    completeness: !exists(json, "completeness")
      ? undefined
      : json["completeness"],
    licenseCc: !exists(json, "license_cc") ? undefined : json["license_cc"],
    testMode: !exists(json, "test_mode") ? undefined : json["test_mode"],
    continuingEdCredits: !exists(json, "continuing_ed_credits")
      ? undefined
      : json["continuing_ed_credits"],
    location: !exists(json, "location") ? undefined : json["location"],
    duration: !exists(json, "duration") ? undefined : json["duration"],
    minWeeks: !exists(json, "min_weeks") ? undefined : json["min_weeks"],
    maxWeeks: !exists(json, "max_weeks") ? undefined : json["max_weeks"],
    timeCommitment: !exists(json, "time_commitment")
      ? undefined
      : json["time_commitment"],
    minWeeklyHours: !exists(json, "min_weekly_hours")
      ? undefined
      : json["min_weekly_hours"],
    maxWeeklyHours: !exists(json, "max_weekly_hours")
      ? undefined
      : json["max_weekly_hours"],
    requireSummaries: json["require_summaries"],
  }
}

export function PodcastEpisodeResourceToJSON(
  value?: PodcastEpisodeResource | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    topics:
      value.topics === undefined
        ? undefined
        : (value.topics as Array<any>).map(LearningResourceTopicToJSON),
    certification_type: CourseResourceCertificationTypeToJSON(
      value.certificationType,
    ),
    readable_id: value.readableId,
    title: value.title,
    description: value.description,
    full_description: value.fullDescription,
    last_modified:
      value.lastModified === undefined
        ? undefined
        : value.lastModified === null
          ? null
          : value.lastModified.toISOString(),
    published: value.published,
    languages: value.languages,
    url: value.url,
    ocw_topics: value.ocwTopics,
    next_start_date:
      value.nextStartDate === undefined
        ? undefined
        : value.nextStartDate === null
          ? null
          : value.nextStartDate.toISOString(),
    availability: AvailabilityEnumToJSON(value.availability),
    completeness: value.completeness,
    license_cc: value.licenseCc,
    test_mode: value.testMode,
    continuing_ed_credits: value.continuingEdCredits,
    location: value.location,
    duration: value.duration,
    min_weeks: value.minWeeks,
    max_weeks: value.maxWeeks,
    time_commitment: value.timeCommitment,
    min_weekly_hours: value.minWeeklyHours,
    max_weekly_hours: value.maxWeeklyHours,
  }
}
