/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { AvailabilityEnum } from "./AvailabilityEnum"
import {
  AvailabilityEnumFromJSON,
  AvailabilityEnumFromJSONTyped,
  AvailabilityEnumToJSON,
} from "./AvailabilityEnum"
import type { LearningResourceTopic } from "./LearningResourceTopic"
import {
  LearningResourceTopicFromJSON,
  LearningResourceTopicFromJSONTyped,
  LearningResourceTopicToJSON,
} from "./LearningResourceTopic"

/**
 * Serializer for podcast episode resources
 * @export
 * @interface PodcastEpisodeResourceRequest
 */
export interface PodcastEpisodeResourceRequest {
  /**
   *
   * @type {Array<LearningResourceTopic>}
   * @memberof PodcastEpisodeResourceRequest
   */
  topics?: Array<LearningResourceTopic>
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResourceRequest
   */
  readableId: string
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResourceRequest
   */
  title: string
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResourceRequest
   */
  description?: string | null
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResourceRequest
   */
  fullDescription?: string | null
  /**
   *
   * @type {Date}
   * @memberof PodcastEpisodeResourceRequest
   */
  lastModified?: Date | null
  /**
   *
   * @type {boolean}
   * @memberof PodcastEpisodeResourceRequest
   */
  published?: boolean
  /**
   *
   * @type {Array<string>}
   * @memberof PodcastEpisodeResourceRequest
   */
  languages?: Array<string> | null
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResourceRequest
   */
  url?: string | null
  /**
   *
   * @type {Array<string>}
   * @memberof PodcastEpisodeResourceRequest
   */
  ocwTopics?: Array<string>
  /**
   *
   * @type {Date}
   * @memberof PodcastEpisodeResourceRequest
   */
  nextStartDate?: Date | null
  /**
   *
   * @type {AvailabilityEnum}
   * @memberof PodcastEpisodeResourceRequest
   */
  availability?: AvailabilityEnum | null
  /**
   *
   * @type {number}
   * @memberof PodcastEpisodeResourceRequest
   */
  completeness?: number
  /**
   *
   * @type {boolean}
   * @memberof PodcastEpisodeResourceRequest
   */
  licenseCc?: boolean
  /**
   *
   * @type {boolean}
   * @memberof PodcastEpisodeResourceRequest
   */
  testMode?: boolean
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResourceRequest
   */
  continuingEdCredits?: string | null
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResourceRequest
   */
  location?: string
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResourceRequest
   */
  duration?: string
  /**
   *
   * @type {number}
   * @memberof PodcastEpisodeResourceRequest
   */
  minWeeks?: number | null
  /**
   *
   * @type {number}
   * @memberof PodcastEpisodeResourceRequest
   */
  maxWeeks?: number | null
  /**
   *
   * @type {string}
   * @memberof PodcastEpisodeResourceRequest
   */
  timeCommitment?: string
  /**
   *
   * @type {number}
   * @memberof PodcastEpisodeResourceRequest
   */
  minWeeklyHours?: number | null
  /**
   *
   * @type {number}
   * @memberof PodcastEpisodeResourceRequest
   */
  maxWeeklyHours?: number | null
}

/**
 * Check if a given object implements the PodcastEpisodeResourceRequest interface.
 */
export function instanceOfPodcastEpisodeResourceRequest(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "readableId" in value
  isInstance = isInstance && "title" in value

  return isInstance
}

export function PodcastEpisodeResourceRequestFromJSON(
  json: any,
): PodcastEpisodeResourceRequest {
  return PodcastEpisodeResourceRequestFromJSONTyped(json, false)
}

export function PodcastEpisodeResourceRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PodcastEpisodeResourceRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    topics: !exists(json, "topics")
      ? undefined
      : (json["topics"] as Array<any>).map(LearningResourceTopicFromJSON),
    readableId: json["readable_id"],
    title: json["title"],
    description: !exists(json, "description") ? undefined : json["description"],
    fullDescription: !exists(json, "full_description")
      ? undefined
      : json["full_description"],
    lastModified: !exists(json, "last_modified")
      ? undefined
      : json["last_modified"] === null
        ? null
        : new Date(json["last_modified"]),
    published: !exists(json, "published") ? undefined : json["published"],
    languages: !exists(json, "languages") ? undefined : json["languages"],
    url: !exists(json, "url") ? undefined : json["url"],
    ocwTopics: !exists(json, "ocw_topics") ? undefined : json["ocw_topics"],
    nextStartDate: !exists(json, "next_start_date")
      ? undefined
      : json["next_start_date"] === null
        ? null
        : new Date(json["next_start_date"]),
    availability: !exists(json, "availability")
      ? undefined
      : AvailabilityEnumFromJSON(json["availability"]),
    completeness: !exists(json, "completeness")
      ? undefined
      : json["completeness"],
    licenseCc: !exists(json, "license_cc") ? undefined : json["license_cc"],
    testMode: !exists(json, "test_mode") ? undefined : json["test_mode"],
    continuingEdCredits: !exists(json, "continuing_ed_credits")
      ? undefined
      : json["continuing_ed_credits"],
    location: !exists(json, "location") ? undefined : json["location"],
    duration: !exists(json, "duration") ? undefined : json["duration"],
    minWeeks: !exists(json, "min_weeks") ? undefined : json["min_weeks"],
    maxWeeks: !exists(json, "max_weeks") ? undefined : json["max_weeks"],
    timeCommitment: !exists(json, "time_commitment")
      ? undefined
      : json["time_commitment"],
    minWeeklyHours: !exists(json, "min_weekly_hours")
      ? undefined
      : json["min_weekly_hours"],
    maxWeeklyHours: !exists(json, "max_weekly_hours")
      ? undefined
      : json["max_weekly_hours"],
  }
}

export function PodcastEpisodeResourceRequestToJSON(
  value?: PodcastEpisodeResourceRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    topics:
      value.topics === undefined
        ? undefined
        : (value.topics as Array<any>).map(LearningResourceTopicToJSON),
    readable_id: value.readableId,
    title: value.title,
    description: value.description,
    full_description: value.fullDescription,
    last_modified:
      value.lastModified === undefined
        ? undefined
        : value.lastModified === null
          ? null
          : value.lastModified.toISOString(),
    published: value.published,
    languages: value.languages,
    url: value.url,
    ocw_topics: value.ocwTopics,
    next_start_date:
      value.nextStartDate === undefined
        ? undefined
        : value.nextStartDate === null
          ? null
          : value.nextStartDate.toISOString(),
    availability: AvailabilityEnumToJSON(value.availability),
    completeness: value.completeness,
    license_cc: value.licenseCc,
    test_mode: value.testMode,
    continuing_ed_credits: value.continuingEdCredits,
    location: value.location,
    duration: value.duration,
    min_weeks: value.minWeeks,
    max_weeks: value.maxWeeks,
    time_commitment: value.timeCommitment,
    min_weekly_hours: value.minWeeklyHours,
    max_weekly_hours: value.maxWeeklyHours,
  }
}
