/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `private` - private
 * * `unlisted` - unlisted
 * @export
 */
export const PrivacyLevelEnum = {
  Private: "private",
  Unlisted: "unlisted",
} as const
export type PrivacyLevelEnum =
  (typeof PrivacyLevelEnum)[keyof typeof PrivacyLevelEnum]

export function PrivacyLevelEnumFromJSON(json: any): PrivacyLevelEnum {
  return PrivacyLevelEnumFromJSONTyped(json, false)
}

export function PrivacyLevelEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrivacyLevelEnum {
  return json as PrivacyLevelEnum
}

export function PrivacyLevelEnumToJSON(value?: PrivacyLevelEnum | null): any {
  return value as any
}
