/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Seriializer for program letter template data which is configured in
 * micromasters
 * @export
 * @interface ProgramLetterTemplateField
 */
export interface ProgramLetterTemplateField {
    /**
     * 
     * @type {number}
     * @memberof ProgramLetterTemplateField
     */
    id: number;
    /**
     * 
     * @type {any}
     * @memberof ProgramLetterTemplateField
     */
    meta: any | null;
    /**
     * 
     * @type {string}
     * @memberof ProgramLetterTemplateField
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof ProgramLetterTemplateField
     */
    programId: number;
    /**
     * 
     * @type {any}
     * @memberof ProgramLetterTemplateField
     */
    programLetterFooter: any | null;
    /**
     * 
     * @type {string}
     * @memberof ProgramLetterTemplateField
     */
    programLetterFooterText: string;
    /**
     * 
     * @type {string}
     * @memberof ProgramLetterTemplateField
     */
    programLetterHeaderText: string;
    /**
     * 
     * @type {string}
     * @memberof ProgramLetterTemplateField
     */
    programLetterText: string;
    /**
     * 
     * @type {any}
     * @memberof ProgramLetterTemplateField
     */
    programLetterLogo: any | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof ProgramLetterTemplateField
     */
    programLetterSignatories: Array<any>;
}

/**
 * Check if a given object implements the ProgramLetterTemplateField interface.
 */
export function instanceOfProgramLetterTemplateField(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "meta" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "programId" in value;
    isInstance = isInstance && "programLetterFooter" in value;
    isInstance = isInstance && "programLetterFooterText" in value;
    isInstance = isInstance && "programLetterHeaderText" in value;
    isInstance = isInstance && "programLetterText" in value;
    isInstance = isInstance && "programLetterLogo" in value;
    isInstance = isInstance && "programLetterSignatories" in value;

    return isInstance;
}

export function ProgramLetterTemplateFieldFromJSON(json: any): ProgramLetterTemplateField {
    return ProgramLetterTemplateFieldFromJSONTyped(json, false);
}

export function ProgramLetterTemplateFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProgramLetterTemplateField {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'meta': json['meta'],
        'title': json['title'],
        'programId': json['program_id'],
        'programLetterFooter': json['program_letter_footer'],
        'programLetterFooterText': json['program_letter_footer_text'],
        'programLetterHeaderText': json['program_letter_header_text'],
        'programLetterText': json['program_letter_text'],
        'programLetterLogo': json['program_letter_logo'],
        'programLetterSignatories': json['program_letter_signatories'],
    };
}

export function ProgramLetterTemplateFieldToJSON(value?: ProgramLetterTemplateField | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'meta': value.meta,
        'title': value.title,
        'program_id': value.programId,
        'program_letter_footer': value.programLetterFooter,
        'program_letter_footer_text': value.programLetterFooterText,
        'program_letter_header_text': value.programLetterHeaderText,
        'program_letter_text': value.programLetterText,
        'program_letter_logo': value.programLetterLogo,
        'program_letter_signatories': value.programLetterSignatories,
    };
}

