/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `PROGRAM_COURSES` - Program Courses
 * * `LEARNING_PATH_ITEMS` - Learning Path Items
 * * `PODCAST_EPISODES` - Podcast Episodes
 * * `PLAYLIST_VIDEOS` - Playlist Videos
 * @export
 */
export const RelationTypeEnum = {
    ProgramCourses: 'PROGRAM_COURSES',
    LearningPathItems: 'LEARNING_PATH_ITEMS',
    PodcastEpisodes: 'PODCAST_EPISODES',
    PlaylistVideos: 'PLAYLIST_VIDEOS'
} as const;
export type RelationTypeEnum = typeof RelationTypeEnum[keyof typeof RelationTypeEnum];


export function RelationTypeEnumFromJSON(json: any): RelationTypeEnum {
    return RelationTypeEnumFromJSONTyped(json, false);
}

export function RelationTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationTypeEnum {
    return json as RelationTypeEnum;
}

export function RelationTypeEnumToJSON(value?: RelationTypeEnum | null): any {
    return value as any;
}

