/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `course` - course
 * * `program` - program
 * * `learning_path` - learning_path
 * * `podcast` - podcast
 * * `podcast_episode` - podcast_episode
 * * `video` - video
 * * `video_playlist` - video_playlist
 * @export
 */
export const ResourceTypeEnum = {
  Course: "course",
  Program: "program",
  LearningPath: "learning_path",
  Podcast: "podcast",
  PodcastEpisode: "podcast_episode",
  Video: "video",
  VideoPlaylist: "video_playlist",
} as const
export type ResourceTypeEnum =
  (typeof ResourceTypeEnum)[keyof typeof ResourceTypeEnum]

export function ResourceTypeEnumFromJSON(json: any): ResourceTypeEnum {
  return ResourceTypeEnumFromJSONTyped(json, false)
}

export function ResourceTypeEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResourceTypeEnum {
  return json as ResourceTypeEnum
}

export function ResourceTypeEnumToJSON(value?: ResourceTypeEnum | null): any {
  return value as any
}
