/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `best_fields` - best_fields
 * * `most_fields` - most_fields
 * * `phrase` - phrase
 * 
 * * `best_fields` - best_fields
 * * `most_fields` - most_fields
 * * `phrase` - phrase
 * @export
 */
export const SearchModeEnum = {
    BestFields: 'best_fields',
    MostFields: 'most_fields',
    Phrase: 'phrase'
} as const;
export type SearchModeEnum = typeof SearchModeEnum[keyof typeof SearchModeEnum];


export function SearchModeEnumFromJSON(json: any): SearchModeEnum {
    return SearchModeEnumFromJSONTyped(json, false);
}

export function SearchModeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchModeEnum {
    return json as SearchModeEnum;
}

export function SearchModeEnumToJSON(value?: SearchModeEnum | null): any {
    return value as any;
}

