/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * * `featured` - Featured
 * * `id` - Object ID ascending
 * * `-id` - Object ID descending
 * * `readable_id` - Readable ID ascending
 * * `-readable_id` - Readable ID descending
 * * `last_modified` - Last Modified Date ascending
 * * `-last_modified` - Last Modified Date descending
 * * `new` - Newest resources first
 * * `start_date` - Start Date ascending
 * * `-start_date` - Start Date descending
 * * `mitcoursenumber` - MIT course number ascending
 * * `-mitcoursenumber` - MIT course number descending
 * * `views` - Popularity ascending
 * * `-views` - Popularity descending
 * * `upcoming` - Next start date ascending
 * @export
 */
export const SortbyEnum = {
  Featured: "featured",
  Id: "id",
  Id2: "-id",
  ReadableId: "readable_id",
  ReadableId2: "-readable_id",
  LastModified: "last_modified",
  LastModified2: "-last_modified",
  New: "new",
  StartDate: "start_date",
  StartDate2: "-start_date",
  Mitcoursenumber: "mitcoursenumber",
  Mitcoursenumber2: "-mitcoursenumber",
  Views: "views",
  Views2: "-views",
  Upcoming: "upcoming",
} as const
export type SortbyEnum = (typeof SortbyEnum)[keyof typeof SortbyEnum]

export function SortbyEnumFromJSON(json: any): SortbyEnum {
  return SortbyEnumFromJSONTyped(json, false)
}

export function SortbyEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SortbyEnum {
  return json as SortbyEnum
}

export function SortbyEnumToJSON(value?: SortbyEnum | null): any {
  return value as any
}
