/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 * Serializer for the Video model
 * @export
 * @interface VideoRequest
 */
export interface VideoRequest {
  /**
   *
   * @type {string}
   * @memberof VideoRequest
   */
  duration: string
  /**
   *
   * @type {string}
   * @memberof VideoRequest
   */
  transcript?: string
}

/**
 * Check if a given object implements the VideoRequest interface.
 */
export function instanceOfVideoRequest(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "duration" in value

  return isInstance
}

export function VideoRequestFromJSON(json: any): VideoRequest {
  return VideoRequestFromJSONTyped(json, false)
}

export function VideoRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VideoRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    duration: json["duration"],
    transcript: !exists(json, "transcript") ? undefined : json["transcript"],
  }
}

export function VideoRequestToJSON(value?: VideoRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    duration: value.duration,
    transcript: value.transcript,
  }
}
