/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for the VideoPlaylist model
 * @export
 * @interface VideoPlaylistRequest
 */
export interface VideoPlaylistRequest {
    /**
     * 
     * @type {number}
     * @memberof VideoPlaylistRequest
     */
    videoCount: number;
}

/**
 * Check if a given object implements the VideoPlaylistRequest interface.
 */
export function instanceOfVideoPlaylistRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "videoCount" in value;

    return isInstance;
}

export function VideoPlaylistRequestFromJSON(json: any): VideoPlaylistRequest {
    return VideoPlaylistRequestFromJSONTyped(json, false);
}

export function VideoPlaylistRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoPlaylistRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'videoCount': json['video_count'],
    };
}

export function VideoPlaylistRequestToJSON(value?: VideoPlaylistRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'video_count': value.videoCount,
    };
}

