/* tslint:disable */
/* eslint-disable */
/**
 * MIT Learn API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v1)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 * Serializer for webhook responses.
 * @export
 * @interface WebhookResponse
 */
export interface WebhookResponse {
  /**
   *
   * @type {string}
   * @memberof WebhookResponse
   */
  status: string
  /**
   *
   * @type {string}
   * @memberof WebhookResponse
   */
  message?: string
  /**
   *
   * @type {string}
   * @memberof WebhookResponse
   */
  error?: string
}

/**
 * Check if a given object implements the WebhookResponse interface.
 */
export function instanceOfWebhookResponse(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "status" in value

  return isInstance
}

export function WebhookResponseFromJSON(json: any): WebhookResponse {
  return WebhookResponseFromJSONTyped(json, false)
}

export function WebhookResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WebhookResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    status: json["status"],
    message: !exists(json, "message") ? undefined : json["message"],
    error: !exists(json, "error") ? undefined : json["error"],
  }
}

export function WebhookResponseToJSON(value?: WebhookResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    status: value.status,
    message: value.message,
    error: value.error,
  }
}
